# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from proto import market_data_pb2 as proto_dot_market__data__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in proto/market_data_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class MarketDataServiceStub(object):
    """MarketDataService provides market data via gRPC
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetPrice = channel.unary_unary(
                '/marketdata.MarketDataService/GetPrice',
                request_serializer=proto_dot_market__data__pb2.PriceRequest.SerializeToString,
                response_deserializer=proto_dot_market__data__pb2.PriceResponse.FromString,
                _registered_method=True)
        self.GetHistory = channel.unary_unary(
                '/marketdata.MarketDataService/GetHistory',
                request_serializer=proto_dot_market__data__pb2.HistoryRequest.SerializeToString,
                response_deserializer=proto_dot_market__data__pb2.HistoryResponse.FromString,
                _registered_method=True)
        self.GetInfo = channel.unary_unary(
                '/marketdata.MarketDataService/GetInfo',
                request_serializer=proto_dot_market__data__pb2.InfoRequest.SerializeToString,
                response_deserializer=proto_dot_market__data__pb2.InfoResponse.FromString,
                _registered_method=True)
        self.GetBatchPrices = channel.unary_unary(
                '/marketdata.MarketDataService/GetBatchPrices',
                request_serializer=proto_dot_market__data__pb2.BatchPriceRequest.SerializeToString,
                response_deserializer=proto_dot_market__data__pb2.BatchPriceResponse.FromString,
                _registered_method=True)


class MarketDataServiceServicer(object):
    """MarketDataService provides market data via gRPC
    """

    def GetPrice(self, request, context):
        """GetPrice returns current price for a symbol
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetHistory(self, request, context):
        """GetHistory returns historical OHLCV data
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetInfo(self, request, context):
        """GetInfo returns company/fund information
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetBatchPrices(self, request, context):
        """GetBatchPrices returns prices for multiple symbols
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MarketDataServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetPrice': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPrice,
                    request_deserializer=proto_dot_market__data__pb2.PriceRequest.FromString,
                    response_serializer=proto_dot_market__data__pb2.PriceResponse.SerializeToString,
            ),
            'GetHistory': grpc.unary_unary_rpc_method_handler(
                    servicer.GetHistory,
                    request_deserializer=proto_dot_market__data__pb2.HistoryRequest.FromString,
                    response_serializer=proto_dot_market__data__pb2.HistoryResponse.SerializeToString,
            ),
            'GetInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetInfo,
                    request_deserializer=proto_dot_market__data__pb2.InfoRequest.FromString,
                    response_serializer=proto_dot_market__data__pb2.InfoResponse.SerializeToString,
            ),
            'GetBatchPrices': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBatchPrices,
                    request_deserializer=proto_dot_market__data__pb2.BatchPriceRequest.FromString,
                    response_serializer=proto_dot_market__data__pb2.BatchPriceResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'marketdata.MarketDataService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('marketdata.MarketDataService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MarketDataService(object):
    """MarketDataService provides market data via gRPC
    """

    @staticmethod
    def GetPrice(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marketdata.MarketDataService/GetPrice',
            proto_dot_market__data__pb2.PriceRequest.SerializeToString,
            proto_dot_market__data__pb2.PriceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetHistory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marketdata.MarketDataService/GetHistory',
            proto_dot_market__data__pb2.HistoryRequest.SerializeToString,
            proto_dot_market__data__pb2.HistoryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marketdata.MarketDataService/GetInfo',
            proto_dot_market__data__pb2.InfoRequest.SerializeToString,
            proto_dot_market__data__pb2.InfoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetBatchPrices(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/marketdata.MarketDataService/GetBatchPrices',
            proto_dot_market__data__pb2.BatchPriceRequest.SerializeToString,
            proto_dot_market__data__pb2.BatchPriceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
