"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf.internal import containers as _containers
from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 10):
    from typing import TypeAlias as _TypeAlias
else:
    from typing_extensions import TypeAlias as _TypeAlias

DESCRIPTOR: _descriptor.FileDescriptor

class _Interval:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _IntervalEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_Interval.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    INTERVAL_UNSPECIFIED: _Interval.ValueType  # 0
    INTERVAL_1M: _Interval.ValueType  # 1
    INTERVAL_5M: _Interval.ValueType  # 2
    INTERVAL_15M: _Interval.ValueType  # 3
    INTERVAL_30M: _Interval.ValueType  # 4
    INTERVAL_1H: _Interval.ValueType  # 5
    INTERVAL_4H: _Interval.ValueType  # 6
    INTERVAL_1D: _Interval.ValueType  # 7

class Interval(_Interval, metaclass=_IntervalEnumTypeWrapper):
    """Interval represents candle granularity"""

INTERVAL_UNSPECIFIED: Interval.ValueType  # 0
INTERVAL_1M: Interval.ValueType  # 1
INTERVAL_5M: Interval.ValueType  # 2
INTERVAL_15M: Interval.ValueType  # 3
INTERVAL_30M: Interval.ValueType  # 4
INTERVAL_1H: Interval.ValueType  # 5
INTERVAL_4H: Interval.ValueType  # 6
INTERVAL_1D: Interval.ValueType  # 7
Global___Interval: _TypeAlias = Interval  # noqa: Y015

class _AssetType:
    ValueType = _typing.NewType("ValueType", _builtins.int)
    V: _TypeAlias = ValueType  # noqa: Y015

class _AssetTypeEnumTypeWrapper(_enum_type_wrapper._EnumTypeWrapper[_AssetType.ValueType], _builtins.type):
    DESCRIPTOR: _descriptor.EnumDescriptor
    ASSET_TYPE_UNSPECIFIED: _AssetType.ValueType  # 0
    ASSET_TYPE_STOCK: _AssetType.ValueType  # 1
    ASSET_TYPE_FUND: _AssetType.ValueType  # 2
    ASSET_TYPE_CRYPTO: _AssetType.ValueType  # 3

class AssetType(_AssetType, metaclass=_AssetTypeEnumTypeWrapper):
    """AssetType represents the type of asset"""

ASSET_TYPE_UNSPECIFIED: AssetType.ValueType  # 0
ASSET_TYPE_STOCK: AssetType.ValueType  # 1
ASSET_TYPE_FUND: AssetType.ValueType  # 2
ASSET_TYPE_CRYPTO: AssetType.ValueType  # 3
Global___AssetType: _TypeAlias = AssetType  # noqa: Y015

@_typing.final
class OHLCVBar(_message.Message):
    """OHLCVBar represents a single candlestick bar"""

    DESCRIPTOR: _descriptor.Descriptor

    TIMESTAMP_FIELD_NUMBER: _builtins.int
    OPEN_FIELD_NUMBER: _builtins.int
    HIGH_FIELD_NUMBER: _builtins.int
    LOW_FIELD_NUMBER: _builtins.int
    CLOSE_FIELD_NUMBER: _builtins.int
    VOLUME_FIELD_NUMBER: _builtins.int
    timestamp: _builtins.int
    """Unix timestamp in milliseconds"""
    open: _builtins.int
    """Price in cents"""
    high: _builtins.int
    """Price in cents"""
    low: _builtins.int
    """Price in cents"""
    close: _builtins.int
    """Price in cents"""
    volume: _builtins.float
    """Volume (float for flexibility)"""
    def __init__(
        self,
        *,
        timestamp: _builtins.int = ...,
        open: _builtins.int = ...,
        high: _builtins.int = ...,
        low: _builtins.int = ...,
        close: _builtins.int = ...,
        volume: _builtins.float = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["close", b"close", "high", b"high", "low", b"low", "open", b"open", "timestamp", b"timestamp", "volume", b"volume"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___OHLCVBar: _TypeAlias = OHLCVBar  # noqa: Y015

@_typing.final
class PriceRequest(_message.Message):
    """PriceRequest requests current price for a symbol"""

    DESCRIPTOR: _descriptor.Descriptor

    SYMBOL_FIELD_NUMBER: _builtins.int
    ASSET_TYPE_FIELD_NUMBER: _builtins.int
    symbol: _builtins.str
    asset_type: Global___AssetType.ValueType
    def __init__(
        self,
        *,
        symbol: _builtins.str = ...,
        asset_type: Global___AssetType.ValueType = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["asset_type", b"asset_type", "symbol", b"symbol"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___PriceRequest: _TypeAlias = PriceRequest  # noqa: Y015

@_typing.final
class PriceResponse(_message.Message):
    """PriceResponse returns current price data"""

    DESCRIPTOR: _descriptor.Descriptor

    SYMBOL_FIELD_NUMBER: _builtins.int
    BID_FIELD_NUMBER: _builtins.int
    ASK_FIELD_NUMBER: _builtins.int
    LAST_FIELD_NUMBER: _builtins.int
    VOLUME_FIELD_NUMBER: _builtins.int
    TIMESTAMP_FIELD_NUMBER: _builtins.int
    SOURCE_FIELD_NUMBER: _builtins.int
    symbol: _builtins.str
    bid: _builtins.int
    """Price in cents"""
    ask: _builtins.int
    """Price in cents"""
    last: _builtins.int
    """Price in cents"""
    volume: _builtins.int
    timestamp: _builtins.int
    """Unix timestamp in milliseconds"""
    source: _builtins.str
    def __init__(
        self,
        *,
        symbol: _builtins.str = ...,
        bid: _builtins.int = ...,
        ask: _builtins.int = ...,
        last: _builtins.int = ...,
        volume: _builtins.int = ...,
        timestamp: _builtins.int = ...,
        source: _builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["ask", b"ask", "bid", b"bid", "last", b"last", "source", b"source", "symbol", b"symbol", "timestamp", b"timestamp", "volume", b"volume"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___PriceResponse: _TypeAlias = PriceResponse  # noqa: Y015

@_typing.final
class HistoryRequest(_message.Message):
    """HistoryRequest requests historical candle data"""

    DESCRIPTOR: _descriptor.Descriptor

    SYMBOL_FIELD_NUMBER: _builtins.int
    ASSET_TYPE_FIELD_NUMBER: _builtins.int
    INTERVAL_FIELD_NUMBER: _builtins.int
    FROM_FIELD_NUMBER: _builtins.int
    TO_FIELD_NUMBER: _builtins.int
    LIMIT_FIELD_NUMBER: _builtins.int
    symbol: _builtins.str
    asset_type: Global___AssetType.ValueType
    interval: Global___Interval.ValueType
    to: _builtins.int
    """Unix timestamp in milliseconds"""
    limit: _builtins.int
    """Max number of candles"""
    def __init__(
        self,
        *,
        symbol: _builtins.str = ...,
        asset_type: Global___AssetType.ValueType = ...,
        interval: Global___Interval.ValueType = ...,
        to: _builtins.int = ...,
        limit: _builtins.int = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["asset_type", b"asset_type", "from", b"from", "interval", b"interval", "limit", b"limit", "symbol", b"symbol", "to", b"to"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___HistoryRequest: _TypeAlias = HistoryRequest  # noqa: Y015

@_typing.final
class HistoryResponse(_message.Message):
    """HistoryResponse returns historical candle data"""

    DESCRIPTOR: _descriptor.Descriptor

    BARS_FIELD_NUMBER: _builtins.int
    HAS_MORE_FIELD_NUMBER: _builtins.int
    NEXT_TOKEN_FIELD_NUMBER: _builtins.int
    SOURCE_FIELD_NUMBER: _builtins.int
    TIMESTAMP_FIELD_NUMBER: _builtins.int
    has_more: _builtins.bool
    next_token: _builtins.str
    source: _builtins.str
    timestamp: _builtins.int
    """Unix timestamp in milliseconds"""
    @_builtins.property
    def bars(self) -> _containers.RepeatedCompositeFieldContainer[Global___OHLCVBar]: ...
    def __init__(
        self,
        *,
        bars: _abc.Iterable[Global___OHLCVBar] | None = ...,
        has_more: _builtins.bool = ...,
        next_token: _builtins.str = ...,
        source: _builtins.str = ...,
        timestamp: _builtins.int = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["bars", b"bars", "has_more", b"has_more", "next_token", b"next_token", "source", b"source", "timestamp", b"timestamp"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___HistoryResponse: _TypeAlias = HistoryResponse  # noqa: Y015

@_typing.final
class InfoRequest(_message.Message):
    """InfoRequest requests company/fund info"""

    DESCRIPTOR: _descriptor.Descriptor

    SYMBOL_FIELD_NUMBER: _builtins.int
    ASSET_TYPE_FIELD_NUMBER: _builtins.int
    symbol: _builtins.str
    asset_type: Global___AssetType.ValueType
    def __init__(
        self,
        *,
        symbol: _builtins.str = ...,
        asset_type: Global___AssetType.ValueType = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["asset_type", b"asset_type", "symbol", b"symbol"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___InfoRequest: _TypeAlias = InfoRequest  # noqa: Y015

@_typing.final
class CompanyInfo(_message.Message):
    """CompanyInfo contains fundamental data for stocks/funds"""

    DESCRIPTOR: _descriptor.Descriptor

    SYMBOL_FIELD_NUMBER: _builtins.int
    NAME_FIELD_NUMBER: _builtins.int
    EXCHANGE_FIELD_NUMBER: _builtins.int
    SECTOR_FIELD_NUMBER: _builtins.int
    INDUSTRY_FIELD_NUMBER: _builtins.int
    CURRENCY_FIELD_NUMBER: _builtins.int
    TIMEZONE_FIELD_NUMBER: _builtins.int
    MARKET_CAP_FIELD_NUMBER: _builtins.int
    PE_RATIO_FIELD_NUMBER: _builtins.int
    DIVIDEND_YIELD_FIELD_NUMBER: _builtins.int
    BETA_FIELD_NUMBER: _builtins.int
    SHARES_OUTSTANDING_FIELD_NUMBER: _builtins.int
    REVENUE_FIELD_NUMBER: _builtins.int
    EARNINGS_FIELD_NUMBER: _builtins.int
    DEBT_FIELD_NUMBER: _builtins.int
    EPS_FIELD_NUMBER: _builtins.int
    FIFTY_TWO_WEEK_HIGH_FIELD_NUMBER: _builtins.int
    FIFTY_TWO_WEEK_LOW_FIELD_NUMBER: _builtins.int
    DESCRIPTION_FIELD_NUMBER: _builtins.int
    symbol: _builtins.str
    name: _builtins.str
    exchange: _builtins.str
    sector: _builtins.str
    industry: _builtins.str
    currency: _builtins.str
    timezone: _builtins.str
    market_cap: _builtins.int
    pe_ratio: _builtins.float
    dividend_yield: _builtins.float
    beta: _builtins.int
    shares_outstanding: _builtins.int
    revenue: _builtins.int
    earnings: _builtins.int
    debt: _builtins.int
    eps: _builtins.float
    fifty_two_week_high: _builtins.int
    fifty_two_week_low: _builtins.int
    description: _builtins.str
    def __init__(
        self,
        *,
        symbol: _builtins.str = ...,
        name: _builtins.str = ...,
        exchange: _builtins.str = ...,
        sector: _builtins.str = ...,
        industry: _builtins.str = ...,
        currency: _builtins.str = ...,
        timezone: _builtins.str = ...,
        market_cap: _builtins.int = ...,
        pe_ratio: _builtins.float = ...,
        dividend_yield: _builtins.float = ...,
        beta: _builtins.int = ...,
        shares_outstanding: _builtins.int = ...,
        revenue: _builtins.int = ...,
        earnings: _builtins.int = ...,
        debt: _builtins.int = ...,
        eps: _builtins.float = ...,
        fifty_two_week_high: _builtins.int = ...,
        fifty_two_week_low: _builtins.int = ...,
        description: _builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["beta", b"beta", "currency", b"currency", "debt", b"debt", "description", b"description", "dividend_yield", b"dividend_yield", "earnings", b"earnings", "eps", b"eps", "exchange", b"exchange", "fifty_two_week_high", b"fifty_two_week_high", "fifty_two_week_low", b"fifty_two_week_low", "industry", b"industry", "market_cap", b"market_cap", "name", b"name", "pe_ratio", b"pe_ratio", "revenue", b"revenue", "sector", b"sector", "shares_outstanding", b"shares_outstanding", "symbol", b"symbol", "timezone", b"timezone"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___CompanyInfo: _TypeAlias = CompanyInfo  # noqa: Y015

@_typing.final
class CryptoInfo(_message.Message):
    """CryptoInfo contains fundamental data for cryptocurrencies"""

    DESCRIPTOR: _descriptor.Descriptor

    SYMBOL_FIELD_NUMBER: _builtins.int
    NAME_FIELD_NUMBER: _builtins.int
    BLOCKCHAIN_FIELD_NUMBER: _builtins.int
    DECIMALS_FIELD_NUMBER: _builtins.int
    IS_STABLECOIN_FIELD_NUMBER: _builtins.int
    MARKET_CAP_FIELD_NUMBER: _builtins.int
    VOLUME_24H_FIELD_NUMBER: _builtins.int
    CIRCULATING_SUPPLY_FIELD_NUMBER: _builtins.int
    TOTAL_SUPPLY_FIELD_NUMBER: _builtins.int
    MAX_SUPPLY_FIELD_NUMBER: _builtins.int
    EPS_FIELD_NUMBER: _builtins.int
    FIFTY_TWO_WEEK_HIGH_FIELD_NUMBER: _builtins.int
    FIFTY_TWO_WEEK_LOW_FIELD_NUMBER: _builtins.int
    DESCRIPTION_FIELD_NUMBER: _builtins.int
    symbol: _builtins.str
    name: _builtins.str
    blockchain: _builtins.str
    decimals: _builtins.int
    is_stablecoin: _builtins.bool
    market_cap: _builtins.int
    volume_24h: _builtins.int
    circulating_supply: _builtins.int
    total_supply: _builtins.int
    max_supply: _builtins.int
    eps: _builtins.float
    fifty_two_week_high: _builtins.int
    fifty_two_week_low: _builtins.int
    description: _builtins.str
    def __init__(
        self,
        *,
        symbol: _builtins.str = ...,
        name: _builtins.str = ...,
        blockchain: _builtins.str = ...,
        decimals: _builtins.int = ...,
        is_stablecoin: _builtins.bool = ...,
        market_cap: _builtins.int = ...,
        volume_24h: _builtins.int = ...,
        circulating_supply: _builtins.int = ...,
        total_supply: _builtins.int = ...,
        max_supply: _builtins.int = ...,
        eps: _builtins.float = ...,
        fifty_two_week_high: _builtins.int = ...,
        fifty_two_week_low: _builtins.int = ...,
        description: _builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["blockchain", b"blockchain", "circulating_supply", b"circulating_supply", "decimals", b"decimals", "description", b"description", "eps", b"eps", "fifty_two_week_high", b"fifty_two_week_high", "fifty_two_week_low", b"fifty_two_week_low", "is_stablecoin", b"is_stablecoin", "market_cap", b"market_cap", "max_supply", b"max_supply", "name", b"name", "symbol", b"symbol", "total_supply", b"total_supply", "volume_24h", b"volume_24h"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___CryptoInfo: _TypeAlias = CryptoInfo  # noqa: Y015

@_typing.final
class InfoResponse(_message.Message):
    """InfoResponse returns company/fund info"""

    DESCRIPTOR: _descriptor.Descriptor

    COMPANY_FIELD_NUMBER: _builtins.int
    CRYPTO_FIELD_NUMBER: _builtins.int
    SOURCE_FIELD_NUMBER: _builtins.int
    TIMESTAMP_FIELD_NUMBER: _builtins.int
    source: _builtins.str
    timestamp: _builtins.int
    """Unix timestamp in milliseconds"""
    @_builtins.property
    def company(self) -> Global___CompanyInfo: ...
    @_builtins.property
    def crypto(self) -> Global___CryptoInfo: ...
    def __init__(
        self,
        *,
        company: Global___CompanyInfo | None = ...,
        crypto: Global___CryptoInfo | None = ...,
        source: _builtins.str = ...,
        timestamp: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["company", b"company", "crypto", b"crypto", "info", b"info"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["company", b"company", "crypto", b"crypto", "info", b"info", "source", b"source", "timestamp", b"timestamp"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType_info: _TypeAlias = _typing.Literal["company", "crypto"]  # noqa: Y015
    _WhichOneofArgType_info: _TypeAlias = _typing.Literal["info", b"info"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType_info) -> _WhichOneofReturnType_info | None: ...

Global___InfoResponse: _TypeAlias = InfoResponse  # noqa: Y015

@_typing.final
class BatchPriceRequest(_message.Message):
    """BatchPriceRequest requests prices for multiple symbols"""

    DESCRIPTOR: _descriptor.Descriptor

    SYMBOLS_FIELD_NUMBER: _builtins.int
    ASSET_TYPE_FIELD_NUMBER: _builtins.int
    asset_type: Global___AssetType.ValueType
    @_builtins.property
    def symbols(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]: ...
    def __init__(
        self,
        *,
        symbols: _abc.Iterable[_builtins.str] | None = ...,
        asset_type: Global___AssetType.ValueType = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["asset_type", b"asset_type", "symbols", b"symbols"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___BatchPriceRequest: _TypeAlias = BatchPriceRequest  # noqa: Y015

@_typing.final
class BatchPriceItem(_message.Message):
    """BatchPriceItem represents price for a single symbol in batch"""

    DESCRIPTOR: _descriptor.Descriptor

    SYMBOL_FIELD_NUMBER: _builtins.int
    PRICE_FIELD_NUMBER: _builtins.int
    VOLUME_FIELD_NUMBER: _builtins.int
    TIMESTAMP_FIELD_NUMBER: _builtins.int
    ERROR_FIELD_NUMBER: _builtins.int
    symbol: _builtins.str
    price: _builtins.int
    """Price in cents"""
    volume: _builtins.int
    timestamp: _builtins.int
    """Unix timestamp in milliseconds"""
    error: _builtins.str
    """Error message if failed"""
    def __init__(
        self,
        *,
        symbol: _builtins.str = ...,
        price: _builtins.int = ...,
        volume: _builtins.int = ...,
        timestamp: _builtins.int = ...,
        error: _builtins.str = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["error", b"error", "price", b"price", "symbol", b"symbol", "timestamp", b"timestamp", "volume", b"volume"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___BatchPriceItem: _TypeAlias = BatchPriceItem  # noqa: Y015

@_typing.final
class BatchPriceResponse(_message.Message):
    """BatchPriceResponse returns prices for multiple symbols"""

    DESCRIPTOR: _descriptor.Descriptor

    PRICES_FIELD_NUMBER: _builtins.int
    SOURCE_FIELD_NUMBER: _builtins.int
    TIMESTAMP_FIELD_NUMBER: _builtins.int
    source: _builtins.str
    timestamp: _builtins.int
    """Unix timestamp in milliseconds"""
    @_builtins.property
    def prices(self) -> _containers.RepeatedCompositeFieldContainer[Global___BatchPriceItem]: ...
    def __init__(
        self,
        *,
        prices: _abc.Iterable[Global___BatchPriceItem] | None = ...,
        source: _builtins.str = ...,
        timestamp: _builtins.int = ...,
    ) -> None: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["prices", b"prices", "source", b"source", "timestamp", b"timestamp"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...

Global___BatchPriceResponse: _TypeAlias = BatchPriceResponse  # noqa: Y015
