/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PortfoliosRouteImport } from './routes/portfolios'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PortfoliosCreateRouteImport } from './routes/portfolios.create'
import { Route as PortfoliosPortfolioIdRouteImport } from './routes/portfolios.$portfolioId'

const PortfoliosRoute = PortfoliosRouteImport.update({
  id: '/portfolios',
  path: '/portfolios',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfoliosCreateRoute = PortfoliosCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => PortfoliosRoute,
} as any)
const PortfoliosPortfolioIdRoute = PortfoliosPortfolioIdRouteImport.update({
  id: '/$portfolioId',
  path: '/$portfolioId',
  getParentRoute: () => PortfoliosRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/portfolios': typeof PortfoliosRouteWithChildren
  '/portfolios/$portfolioId': typeof PortfoliosPortfolioIdRoute
  '/portfolios/create': typeof PortfoliosCreateRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/portfolios': typeof PortfoliosRouteWithChildren
  '/portfolios/$portfolioId': typeof PortfoliosPortfolioIdRoute
  '/portfolios/create': typeof PortfoliosCreateRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/portfolios': typeof PortfoliosRouteWithChildren
  '/portfolios/$portfolioId': typeof PortfoliosPortfolioIdRoute
  '/portfolios/create': typeof PortfoliosCreateRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/portfolios'
    | '/portfolios/$portfolioId'
    | '/portfolios/create'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/portfolios'
    | '/portfolios/$portfolioId'
    | '/portfolios/create'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/portfolios'
    | '/portfolios/$portfolioId'
    | '/portfolios/create'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  PortfoliosRoute: typeof PortfoliosRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/portfolios': {
      id: '/portfolios'
      path: '/portfolios'
      fullPath: '/portfolios'
      preLoaderRoute: typeof PortfoliosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolios/create': {
      id: '/portfolios/create'
      path: '/create'
      fullPath: '/portfolios/create'
      preLoaderRoute: typeof PortfoliosCreateRouteImport
      parentRoute: typeof PortfoliosRoute
    }
    '/portfolios/$portfolioId': {
      id: '/portfolios/$portfolioId'
      path: '/$portfolioId'
      fullPath: '/portfolios/$portfolioId'
      preLoaderRoute: typeof PortfoliosPortfolioIdRouteImport
      parentRoute: typeof PortfoliosRoute
    }
  }
}

interface PortfoliosRouteChildren {
  PortfoliosPortfolioIdRoute: typeof PortfoliosPortfolioIdRoute
  PortfoliosCreateRoute: typeof PortfoliosCreateRoute
}

const PortfoliosRouteChildren: PortfoliosRouteChildren = {
  PortfoliosPortfolioIdRoute: PortfoliosPortfolioIdRoute,
  PortfoliosCreateRoute: PortfoliosCreateRoute,
}

const PortfoliosRouteWithChildren = PortfoliosRoute._addFileChildren(
  PortfoliosRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  PortfoliosRoute: PortfoliosRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
