// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.31.1
// source: market_data.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Interval represents candle granularity
type Interval int32

const (
	Interval_INTERVAL_UNSPECIFIED Interval = 0
	Interval_INTERVAL_1M          Interval = 1
	Interval_INTERVAL_5M          Interval = 2
	Interval_INTERVAL_15M         Interval = 3
	Interval_INTERVAL_30M         Interval = 4
	Interval_INTERVAL_1H          Interval = 5
	Interval_INTERVAL_4H          Interval = 6
	Interval_INTERVAL_1D          Interval = 7
)

// Enum value maps for Interval.
var (
	Interval_name = map[int32]string{
		0: "INTERVAL_UNSPECIFIED",
		1: "INTERVAL_1M",
		2: "INTERVAL_5M",
		3: "INTERVAL_15M",
		4: "INTERVAL_30M",
		5: "INTERVAL_1H",
		6: "INTERVAL_4H",
		7: "INTERVAL_1D",
	}
	Interval_value = map[string]int32{
		"INTERVAL_UNSPECIFIED": 0,
		"INTERVAL_1M":          1,
		"INTERVAL_5M":          2,
		"INTERVAL_15M":         3,
		"INTERVAL_30M":         4,
		"INTERVAL_1H":          5,
		"INTERVAL_4H":          6,
		"INTERVAL_1D":          7,
	}
)

func (x Interval) Enum() *Interval {
	p := new(Interval)
	*p = x
	return p
}

func (x Interval) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Interval) Descriptor() protoreflect.EnumDescriptor {
	return file_market_data_proto_enumTypes[0].Descriptor()
}

func (Interval) Type() protoreflect.EnumType {
	return &file_market_data_proto_enumTypes[0]
}

func (x Interval) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Interval.Descriptor instead.
func (Interval) EnumDescriptor() ([]byte, []int) {
	return file_market_data_proto_rawDescGZIP(), []int{0}
}

// AssetType represents the type of asset
type AssetType int32

const (
	AssetType_ASSET_TYPE_UNSPECIFIED AssetType = 0
	AssetType_ASSET_TYPE_STOCK       AssetType = 1
	AssetType_ASSET_TYPE_FUND        AssetType = 2
	AssetType_ASSET_TYPE_CRYPTO      AssetType = 3
)

// Enum value maps for AssetType.
var (
	AssetType_name = map[int32]string{
		0: "ASSET_TYPE_UNSPECIFIED",
		1: "ASSET_TYPE_STOCK",
		2: "ASSET_TYPE_FUND",
		3: "ASSET_TYPE_CRYPTO",
	}
	AssetType_value = map[string]int32{
		"ASSET_TYPE_UNSPECIFIED": 0,
		"ASSET_TYPE_STOCK":       1,
		"ASSET_TYPE_FUND":        2,
		"ASSET_TYPE_CRYPTO":      3,
	}
)

func (x AssetType) Enum() *AssetType {
	p := new(AssetType)
	*p = x
	return p
}

func (x AssetType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AssetType) Descriptor() protoreflect.EnumDescriptor {
	return file_market_data_proto_enumTypes[1].Descriptor()
}

func (AssetType) Type() protoreflect.EnumType {
	return &file_market_data_proto_enumTypes[1]
}

func (x AssetType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AssetType.Descriptor instead.
func (AssetType) EnumDescriptor() ([]byte, []int) {
	return file_market_data_proto_rawDescGZIP(), []int{1}
}

// OHLCVBar represents a single candlestick bar
type OHLCVBar struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     int64                  `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"` // Unix timestamp in milliseconds
	Open          int64                  `protobuf:"varint,2,opt,name=open,proto3" json:"open,omitempty"`           // Price in cents
	High          int64                  `protobuf:"varint,3,opt,name=high,proto3" json:"high,omitempty"`           // Price in cents
	Low           int64                  `protobuf:"varint,4,opt,name=low,proto3" json:"low,omitempty"`             // Price in cents
	Close         int64                  `protobuf:"varint,5,opt,name=close,proto3" json:"close,omitempty"`         // Price in cents
	Volume        float64                `protobuf:"fixed64,6,opt,name=volume,proto3" json:"volume,omitempty"`      // Volume (float for flexibility)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OHLCVBar) Reset() {
	*x = OHLCVBar{}
	mi := &file_market_data_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OHLCVBar) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OHLCVBar) ProtoMessage() {}

func (x *OHLCVBar) ProtoReflect() protoreflect.Message {
	mi := &file_market_data_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OHLCVBar.ProtoReflect.Descriptor instead.
func (*OHLCVBar) Descriptor() ([]byte, []int) {
	return file_market_data_proto_rawDescGZIP(), []int{0}
}

func (x *OHLCVBar) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *OHLCVBar) GetOpen() int64 {
	if x != nil {
		return x.Open
	}
	return 0
}

func (x *OHLCVBar) GetHigh() int64 {
	if x != nil {
		return x.High
	}
	return 0
}

func (x *OHLCVBar) GetLow() int64 {
	if x != nil {
		return x.Low
	}
	return 0
}

func (x *OHLCVBar) GetClose() int64 {
	if x != nil {
		return x.Close
	}
	return 0
}

func (x *OHLCVBar) GetVolume() float64 {
	if x != nil {
		return x.Volume
	}
	return 0
}

// PriceRequest requests current price for a symbol
type PriceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbol        string                 `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	AssetType     AssetType              `protobuf:"varint,2,opt,name=asset_type,json=assetType,proto3,enum=marketdata.AssetType" json:"asset_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PriceRequest) Reset() {
	*x = PriceRequest{}
	mi := &file_market_data_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PriceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PriceRequest) ProtoMessage() {}

func (x *PriceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_market_data_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PriceRequest.ProtoReflect.Descriptor instead.
func (*PriceRequest) Descriptor() ([]byte, []int) {
	return file_market_data_proto_rawDescGZIP(), []int{1}
}

func (x *PriceRequest) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *PriceRequest) GetAssetType() AssetType {
	if x != nil {
		return x.AssetType
	}
	return AssetType_ASSET_TYPE_UNSPECIFIED
}

// PriceResponse returns current price data
type PriceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbol        string                 `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Bid           int64                  `protobuf:"varint,2,opt,name=bid,proto3" json:"bid,omitempty"`   // Price in cents
	Ask           int64                  `protobuf:"varint,3,opt,name=ask,proto3" json:"ask,omitempty"`   // Price in cents
	Last          int64                  `protobuf:"varint,4,opt,name=last,proto3" json:"last,omitempty"` // Price in cents
	Volume        int64                  `protobuf:"varint,5,opt,name=volume,proto3" json:"volume,omitempty"`
	Timestamp     int64                  `protobuf:"varint,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"` // Unix timestamp in milliseconds
	Source        string                 `protobuf:"bytes,7,opt,name=source,proto3" json:"source,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PriceResponse) Reset() {
	*x = PriceResponse{}
	mi := &file_market_data_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PriceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PriceResponse) ProtoMessage() {}

func (x *PriceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_market_data_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PriceResponse.ProtoReflect.Descriptor instead.
func (*PriceResponse) Descriptor() ([]byte, []int) {
	return file_market_data_proto_rawDescGZIP(), []int{2}
}

func (x *PriceResponse) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *PriceResponse) GetBid() int64 {
	if x != nil {
		return x.Bid
	}
	return 0
}

func (x *PriceResponse) GetAsk() int64 {
	if x != nil {
		return x.Ask
	}
	return 0
}

func (x *PriceResponse) GetLast() int64 {
	if x != nil {
		return x.Last
	}
	return 0
}

func (x *PriceResponse) GetVolume() int64 {
	if x != nil {
		return x.Volume
	}
	return 0
}

func (x *PriceResponse) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *PriceResponse) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

// HistoryRequest requests historical candle data
type HistoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbol        string                 `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	AssetType     AssetType              `protobuf:"varint,2,opt,name=asset_type,json=assetType,proto3,enum=marketdata.AssetType" json:"asset_type,omitempty"`
	Interval      Interval               `protobuf:"varint,3,opt,name=interval,proto3,enum=marketdata.Interval" json:"interval,omitempty"`
	From          int64                  `protobuf:"varint,4,opt,name=from,proto3" json:"from,omitempty"`   // Unix timestamp in milliseconds
	To            int64                  `protobuf:"varint,5,opt,name=to,proto3" json:"to,omitempty"`       // Unix timestamp in milliseconds
	Limit         int32                  `protobuf:"varint,6,opt,name=limit,proto3" json:"limit,omitempty"` // Max number of candles
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HistoryRequest) Reset() {
	*x = HistoryRequest{}
	mi := &file_market_data_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HistoryRequest) ProtoMessage() {}

func (x *HistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_market_data_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HistoryRequest.ProtoReflect.Descriptor instead.
func (*HistoryRequest) Descriptor() ([]byte, []int) {
	return file_market_data_proto_rawDescGZIP(), []int{3}
}

func (x *HistoryRequest) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *HistoryRequest) GetAssetType() AssetType {
	if x != nil {
		return x.AssetType
	}
	return AssetType_ASSET_TYPE_UNSPECIFIED
}

func (x *HistoryRequest) GetInterval() Interval {
	if x != nil {
		return x.Interval
	}
	return Interval_INTERVAL_UNSPECIFIED
}

func (x *HistoryRequest) GetFrom() int64 {
	if x != nil {
		return x.From
	}
	return 0
}

func (x *HistoryRequest) GetTo() int64 {
	if x != nil {
		return x.To
	}
	return 0
}

func (x *HistoryRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

// HistoryResponse returns historical candle data
type HistoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bars          []*OHLCVBar            `protobuf:"bytes,1,rep,name=bars,proto3" json:"bars,omitempty"`
	HasMore       bool                   `protobuf:"varint,2,opt,name=has_more,json=hasMore,proto3" json:"has_more,omitempty"`
	NextToken     string                 `protobuf:"bytes,3,opt,name=next_token,json=nextToken,proto3" json:"next_token,omitempty"`
	Source        string                 `protobuf:"bytes,4,opt,name=source,proto3" json:"source,omitempty"`
	Timestamp     int64                  `protobuf:"varint,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"` // Unix timestamp in milliseconds
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HistoryResponse) Reset() {
	*x = HistoryResponse{}
	mi := &file_market_data_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HistoryResponse) ProtoMessage() {}

func (x *HistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_market_data_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HistoryResponse.ProtoReflect.Descriptor instead.
func (*HistoryResponse) Descriptor() ([]byte, []int) {
	return file_market_data_proto_rawDescGZIP(), []int{4}
}

func (x *HistoryResponse) GetBars() []*OHLCVBar {
	if x != nil {
		return x.Bars
	}
	return nil
}

func (x *HistoryResponse) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

func (x *HistoryResponse) GetNextToken() string {
	if x != nil {
		return x.NextToken
	}
	return ""
}

func (x *HistoryResponse) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *HistoryResponse) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// InfoRequest requests company/fund info
type InfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbol        string                 `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	AssetType     AssetType              `protobuf:"varint,2,opt,name=asset_type,json=assetType,proto3,enum=marketdata.AssetType" json:"asset_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InfoRequest) Reset() {
	*x = InfoRequest{}
	mi := &file_market_data_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InfoRequest) ProtoMessage() {}

func (x *InfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_market_data_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InfoRequest.ProtoReflect.Descriptor instead.
func (*InfoRequest) Descriptor() ([]byte, []int) {
	return file_market_data_proto_rawDescGZIP(), []int{5}
}

func (x *InfoRequest) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *InfoRequest) GetAssetType() AssetType {
	if x != nil {
		return x.AssetType
	}
	return AssetType_ASSET_TYPE_UNSPECIFIED
}

type SearchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	AssetType     string                 `protobuf:"bytes,2,opt,name=asset_type,json=assetType,proto3" json:"asset_type,omitempty"`
	MaxResults    int32                  `protobuf:"varint,3,opt,name=max_results,json=maxResults,proto3" json:"max_results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchRequest) Reset() {
	*x = SearchRequest{}
	mi := &file_market_data_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchRequest) ProtoMessage() {}

func (x *SearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_market_data_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchRequest.ProtoReflect.Descriptor instead.
func (*SearchRequest) Descriptor() ([]byte, []int) {
	return file_market_data_proto_rawDescGZIP(), []int{6}
}

func (x *SearchRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *SearchRequest) GetAssetType() string {
	if x != nil {
		return x.AssetType
	}
	return ""
}

func (x *SearchRequest) GetMaxResults() int32 {
	if x != nil {
		return x.MaxResults
	}
	return 0
}

type SearchResult struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Symbol             string                 `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Name               string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Exchange           string                 `protobuf:"bytes,3,opt,name=exchange,proto3" json:"exchange,omitempty"`
	ExchangeCode       string                 `protobuf:"bytes,4,opt,name=exchange_code,json=exchangeCode,proto3" json:"exchange_code,omitempty"`
	Country            string                 `protobuf:"bytes,5,opt,name=country,proto3" json:"country,omitempty"`
	Currency           string                 `protobuf:"bytes,6,opt,name=currency,proto3" json:"currency,omitempty"`
	AssetType          string                 `protobuf:"bytes,7,opt,name=asset_type,json=assetType,proto3" json:"asset_type,omitempty"`
	ProviderSource     string                 `protobuf:"bytes,8,opt,name=provider_source,json=providerSource,proto3" json:"provider_source,omitempty"`
	ProviderExternalId string                 `protobuf:"bytes,9,opt,name=provider_external_id,json=providerExternalId,proto3" json:"provider_external_id,omitempty"`
	Isin               string                 `protobuf:"bytes,10,opt,name=isin,proto3" json:"isin,omitempty"`
	Figi               string                 `protobuf:"bytes,11,opt,name=figi,proto3" json:"figi,omitempty"`
	Cusip              string                 `protobuf:"bytes,12,opt,name=cusip,proto3" json:"cusip,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *SearchResult) Reset() {
	*x = SearchResult{}
	mi := &file_market_data_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchResult) ProtoMessage() {}

func (x *SearchResult) ProtoReflect() protoreflect.Message {
	mi := &file_market_data_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchResult.ProtoReflect.Descriptor instead.
func (*SearchResult) Descriptor() ([]byte, []int) {
	return file_market_data_proto_rawDescGZIP(), []int{7}
}

func (x *SearchResult) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *SearchResult) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SearchResult) GetExchange() string {
	if x != nil {
		return x.Exchange
	}
	return ""
}

func (x *SearchResult) GetExchangeCode() string {
	if x != nil {
		return x.ExchangeCode
	}
	return ""
}

func (x *SearchResult) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *SearchResult) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *SearchResult) GetAssetType() string {
	if x != nil {
		return x.AssetType
	}
	return ""
}

func (x *SearchResult) GetProviderSource() string {
	if x != nil {
		return x.ProviderSource
	}
	return ""
}

func (x *SearchResult) GetProviderExternalId() string {
	if x != nil {
		return x.ProviderExternalId
	}
	return ""
}

func (x *SearchResult) GetIsin() string {
	if x != nil {
		return x.Isin
	}
	return ""
}

func (x *SearchResult) GetFigi() string {
	if x != nil {
		return x.Figi
	}
	return ""
}

func (x *SearchResult) GetCusip() string {
	if x != nil {
		return x.Cusip
	}
	return ""
}

type SearchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*SearchResult        `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	Provider      string                 `protobuf:"bytes,2,opt,name=provider,proto3" json:"provider,omitempty"`
	Timestamp     int64                  `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchResponse) Reset() {
	*x = SearchResponse{}
	mi := &file_market_data_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchResponse) ProtoMessage() {}

func (x *SearchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_market_data_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchResponse.ProtoReflect.Descriptor instead.
func (*SearchResponse) Descriptor() ([]byte, []int) {
	return file_market_data_proto_rawDescGZIP(), []int{8}
}

func (x *SearchResponse) GetResults() []*SearchResult {
	if x != nil {
		return x.Results
	}
	return nil
}

func (x *SearchResponse) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

func (x *SearchResponse) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// CompanyInfo contains fundamental data for stocks/funds
type CompanyInfo struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Symbol            string                 `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Name              string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Exchange          string                 `protobuf:"bytes,3,opt,name=exchange,proto3" json:"exchange,omitempty"`
	Sector            string                 `protobuf:"bytes,4,opt,name=sector,proto3" json:"sector,omitempty"`
	Industry          string                 `protobuf:"bytes,5,opt,name=industry,proto3" json:"industry,omitempty"`
	Currency          string                 `protobuf:"bytes,6,opt,name=currency,proto3" json:"currency,omitempty"`
	Timezone          string                 `protobuf:"bytes,7,opt,name=timezone,proto3" json:"timezone,omitempty"`
	MarketCap         int64                  `protobuf:"varint,8,opt,name=market_cap,json=marketCap,proto3" json:"market_cap,omitempty"`
	PeRatio           float64                `protobuf:"fixed64,9,opt,name=pe_ratio,json=peRatio,proto3" json:"pe_ratio,omitempty"`
	DividendYield     float64                `protobuf:"fixed64,10,opt,name=dividend_yield,json=dividendYield,proto3" json:"dividend_yield,omitempty"`
	Beta              int64                  `protobuf:"varint,11,opt,name=beta,proto3" json:"beta,omitempty"`
	SharesOutstanding int64                  `protobuf:"varint,12,opt,name=shares_outstanding,json=sharesOutstanding,proto3" json:"shares_outstanding,omitempty"`
	Revenue           int64                  `protobuf:"varint,13,opt,name=revenue,proto3" json:"revenue,omitempty"`
	Earnings          int64                  `protobuf:"varint,14,opt,name=earnings,proto3" json:"earnings,omitempty"`
	Debt              int64                  `protobuf:"varint,15,opt,name=debt,proto3" json:"debt,omitempty"`
	Eps               float64                `protobuf:"fixed64,16,opt,name=eps,proto3" json:"eps,omitempty"`
	FiftyTwoWeekHigh  int64                  `protobuf:"varint,17,opt,name=fifty_two_week_high,json=fiftyTwoWeekHigh,proto3" json:"fifty_two_week_high,omitempty"`
	FiftyTwoWeekLow   int64                  `protobuf:"varint,18,opt,name=fifty_two_week_low,json=fiftyTwoWeekLow,proto3" json:"fifty_two_week_low,omitempty"`
	Description       string                 `protobuf:"bytes,19,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *CompanyInfo) Reset() {
	*x = CompanyInfo{}
	mi := &file_market_data_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompanyInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompanyInfo) ProtoMessage() {}

func (x *CompanyInfo) ProtoReflect() protoreflect.Message {
	mi := &file_market_data_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompanyInfo.ProtoReflect.Descriptor instead.
func (*CompanyInfo) Descriptor() ([]byte, []int) {
	return file_market_data_proto_rawDescGZIP(), []int{9}
}

func (x *CompanyInfo) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *CompanyInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CompanyInfo) GetExchange() string {
	if x != nil {
		return x.Exchange
	}
	return ""
}

func (x *CompanyInfo) GetSector() string {
	if x != nil {
		return x.Sector
	}
	return ""
}

func (x *CompanyInfo) GetIndustry() string {
	if x != nil {
		return x.Industry
	}
	return ""
}

func (x *CompanyInfo) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *CompanyInfo) GetTimezone() string {
	if x != nil {
		return x.Timezone
	}
	return ""
}

func (x *CompanyInfo) GetMarketCap() int64 {
	if x != nil {
		return x.MarketCap
	}
	return 0
}

func (x *CompanyInfo) GetPeRatio() float64 {
	if x != nil {
		return x.PeRatio
	}
	return 0
}

func (x *CompanyInfo) GetDividendYield() float64 {
	if x != nil {
		return x.DividendYield
	}
	return 0
}

func (x *CompanyInfo) GetBeta() int64 {
	if x != nil {
		return x.Beta
	}
	return 0
}

func (x *CompanyInfo) GetSharesOutstanding() int64 {
	if x != nil {
		return x.SharesOutstanding
	}
	return 0
}

func (x *CompanyInfo) GetRevenue() int64 {
	if x != nil {
		return x.Revenue
	}
	return 0
}

func (x *CompanyInfo) GetEarnings() int64 {
	if x != nil {
		return x.Earnings
	}
	return 0
}

func (x *CompanyInfo) GetDebt() int64 {
	if x != nil {
		return x.Debt
	}
	return 0
}

func (x *CompanyInfo) GetEps() float64 {
	if x != nil {
		return x.Eps
	}
	return 0
}

func (x *CompanyInfo) GetFiftyTwoWeekHigh() int64 {
	if x != nil {
		return x.FiftyTwoWeekHigh
	}
	return 0
}

func (x *CompanyInfo) GetFiftyTwoWeekLow() int64 {
	if x != nil {
		return x.FiftyTwoWeekLow
	}
	return 0
}

func (x *CompanyInfo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

// CryptoInfo contains fundamental data for cryptocurrencies
type CryptoInfo struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Symbol            string                 `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Name              string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Blockchain        string                 `protobuf:"bytes,3,opt,name=blockchain,proto3" json:"blockchain,omitempty"`
	Decimals          int32                  `protobuf:"varint,4,opt,name=decimals,proto3" json:"decimals,omitempty"`
	IsStablecoin      bool                   `protobuf:"varint,5,opt,name=is_stablecoin,json=isStablecoin,proto3" json:"is_stablecoin,omitempty"`
	MarketCap         int64                  `protobuf:"varint,6,opt,name=market_cap,json=marketCap,proto3" json:"market_cap,omitempty"`
	Volume_24H        int64                  `protobuf:"varint,7,opt,name=volume_24h,json=volume24h,proto3" json:"volume_24h,omitempty"`
	CirculatingSupply int64                  `protobuf:"varint,8,opt,name=circulating_supply,json=circulatingSupply,proto3" json:"circulating_supply,omitempty"`
	TotalSupply       int64                  `protobuf:"varint,9,opt,name=total_supply,json=totalSupply,proto3" json:"total_supply,omitempty"`
	MaxSupply         int64                  `protobuf:"varint,10,opt,name=max_supply,json=maxSupply,proto3" json:"max_supply,omitempty"`
	Eps               float64                `protobuf:"fixed64,11,opt,name=eps,proto3" json:"eps,omitempty"`
	FiftyTwoWeekHigh  int64                  `protobuf:"varint,12,opt,name=fifty_two_week_high,json=fiftyTwoWeekHigh,proto3" json:"fifty_two_week_high,omitempty"`
	FiftyTwoWeekLow   int64                  `protobuf:"varint,13,opt,name=fifty_two_week_low,json=fiftyTwoWeekLow,proto3" json:"fifty_two_week_low,omitempty"`
	Description       string                 `protobuf:"bytes,14,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *CryptoInfo) Reset() {
	*x = CryptoInfo{}
	mi := &file_market_data_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CryptoInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CryptoInfo) ProtoMessage() {}

func (x *CryptoInfo) ProtoReflect() protoreflect.Message {
	mi := &file_market_data_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CryptoInfo.ProtoReflect.Descriptor instead.
func (*CryptoInfo) Descriptor() ([]byte, []int) {
	return file_market_data_proto_rawDescGZIP(), []int{10}
}

func (x *CryptoInfo) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *CryptoInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CryptoInfo) GetBlockchain() string {
	if x != nil {
		return x.Blockchain
	}
	return ""
}

func (x *CryptoInfo) GetDecimals() int32 {
	if x != nil {
		return x.Decimals
	}
	return 0
}

func (x *CryptoInfo) GetIsStablecoin() bool {
	if x != nil {
		return x.IsStablecoin
	}
	return false
}

func (x *CryptoInfo) GetMarketCap() int64 {
	if x != nil {
		return x.MarketCap
	}
	return 0
}

func (x *CryptoInfo) GetVolume_24H() int64 {
	if x != nil {
		return x.Volume_24H
	}
	return 0
}

func (x *CryptoInfo) GetCirculatingSupply() int64 {
	if x != nil {
		return x.CirculatingSupply
	}
	return 0
}

func (x *CryptoInfo) GetTotalSupply() int64 {
	if x != nil {
		return x.TotalSupply
	}
	return 0
}

func (x *CryptoInfo) GetMaxSupply() int64 {
	if x != nil {
		return x.MaxSupply
	}
	return 0
}

func (x *CryptoInfo) GetEps() float64 {
	if x != nil {
		return x.Eps
	}
	return 0
}

func (x *CryptoInfo) GetFiftyTwoWeekHigh() int64 {
	if x != nil {
		return x.FiftyTwoWeekHigh
	}
	return 0
}

func (x *CryptoInfo) GetFiftyTwoWeekLow() int64 {
	if x != nil {
		return x.FiftyTwoWeekLow
	}
	return 0
}

func (x *CryptoInfo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

// InfoResponse returns company/fund info
type InfoResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Info:
	//
	//	*InfoResponse_Company
	//	*InfoResponse_Crypto
	Info          isInfoResponse_Info `protobuf_oneof:"info"`
	Source        string              `protobuf:"bytes,3,opt,name=source,proto3" json:"source,omitempty"`
	Timestamp     int64               `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"` // Unix timestamp in milliseconds
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InfoResponse) Reset() {
	*x = InfoResponse{}
	mi := &file_market_data_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InfoResponse) ProtoMessage() {}

func (x *InfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_market_data_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InfoResponse.ProtoReflect.Descriptor instead.
func (*InfoResponse) Descriptor() ([]byte, []int) {
	return file_market_data_proto_rawDescGZIP(), []int{11}
}

func (x *InfoResponse) GetInfo() isInfoResponse_Info {
	if x != nil {
		return x.Info
	}
	return nil
}

func (x *InfoResponse) GetCompany() *CompanyInfo {
	if x != nil {
		if x, ok := x.Info.(*InfoResponse_Company); ok {
			return x.Company
		}
	}
	return nil
}

func (x *InfoResponse) GetCrypto() *CryptoInfo {
	if x != nil {
		if x, ok := x.Info.(*InfoResponse_Crypto); ok {
			return x.Crypto
		}
	}
	return nil
}

func (x *InfoResponse) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *InfoResponse) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type isInfoResponse_Info interface {
	isInfoResponse_Info()
}

type InfoResponse_Company struct {
	Company *CompanyInfo `protobuf:"bytes,1,opt,name=company,proto3,oneof"`
}

type InfoResponse_Crypto struct {
	Crypto *CryptoInfo `protobuf:"bytes,2,opt,name=crypto,proto3,oneof"`
}

func (*InfoResponse_Company) isInfoResponse_Info() {}

func (*InfoResponse_Crypto) isInfoResponse_Info() {}

// BatchPriceRequest requests prices for multiple symbols
type BatchPriceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbols       []string               `protobuf:"bytes,1,rep,name=symbols,proto3" json:"symbols,omitempty"`
	AssetType     AssetType              `protobuf:"varint,2,opt,name=asset_type,json=assetType,proto3,enum=marketdata.AssetType" json:"asset_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchPriceRequest) Reset() {
	*x = BatchPriceRequest{}
	mi := &file_market_data_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchPriceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchPriceRequest) ProtoMessage() {}

func (x *BatchPriceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_market_data_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchPriceRequest.ProtoReflect.Descriptor instead.
func (*BatchPriceRequest) Descriptor() ([]byte, []int) {
	return file_market_data_proto_rawDescGZIP(), []int{12}
}

func (x *BatchPriceRequest) GetSymbols() []string {
	if x != nil {
		return x.Symbols
	}
	return nil
}

func (x *BatchPriceRequest) GetAssetType() AssetType {
	if x != nil {
		return x.AssetType
	}
	return AssetType_ASSET_TYPE_UNSPECIFIED
}

// BatchPriceItem represents price for a single symbol in batch
type BatchPriceItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbol        string                 `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Price         int64                  `protobuf:"varint,2,opt,name=price,proto3" json:"price,omitempty"` // Price in cents
	Volume        int64                  `protobuf:"varint,3,opt,name=volume,proto3" json:"volume,omitempty"`
	Timestamp     int64                  `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"` // Unix timestamp in milliseconds
	Error         string                 `protobuf:"bytes,5,opt,name=error,proto3" json:"error,omitempty"`          // Error message if failed
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchPriceItem) Reset() {
	*x = BatchPriceItem{}
	mi := &file_market_data_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchPriceItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchPriceItem) ProtoMessage() {}

func (x *BatchPriceItem) ProtoReflect() protoreflect.Message {
	mi := &file_market_data_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchPriceItem.ProtoReflect.Descriptor instead.
func (*BatchPriceItem) Descriptor() ([]byte, []int) {
	return file_market_data_proto_rawDescGZIP(), []int{13}
}

func (x *BatchPriceItem) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *BatchPriceItem) GetPrice() int64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *BatchPriceItem) GetVolume() int64 {
	if x != nil {
		return x.Volume
	}
	return 0
}

func (x *BatchPriceItem) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *BatchPriceItem) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// BatchPriceResponse returns prices for multiple symbols
type BatchPriceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Prices        []*BatchPriceItem      `protobuf:"bytes,1,rep,name=prices,proto3" json:"prices,omitempty"`
	Source        string                 `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"`
	Timestamp     int64                  `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"` // Unix timestamp in milliseconds
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchPriceResponse) Reset() {
	*x = BatchPriceResponse{}
	mi := &file_market_data_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchPriceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchPriceResponse) ProtoMessage() {}

func (x *BatchPriceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_market_data_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchPriceResponse.ProtoReflect.Descriptor instead.
func (*BatchPriceResponse) Descriptor() ([]byte, []int) {
	return file_market_data_proto_rawDescGZIP(), []int{14}
}

func (x *BatchPriceResponse) GetPrices() []*BatchPriceItem {
	if x != nil {
		return x.Prices
	}
	return nil
}

func (x *BatchPriceResponse) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *BatchPriceResponse) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

var File_market_data_proto protoreflect.FileDescriptor

const file_market_data_proto_rawDesc = "" +
	"\n" +
	"\x11market_data.proto\x12\n" +
	"marketdata\"\x90\x01\n" +
	"\bOHLCVBar\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x03R\ttimestamp\x12\x12\n" +
	"\x04open\x18\x02 \x01(\x03R\x04open\x12\x12\n" +
	"\x04high\x18\x03 \x01(\x03R\x04high\x12\x10\n" +
	"\x03low\x18\x04 \x01(\x03R\x03low\x12\x14\n" +
	"\x05close\x18\x05 \x01(\x03R\x05close\x12\x16\n" +
	"\x06volume\x18\x06 \x01(\x01R\x06volume\"\\\n" +
	"\fPriceRequest\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\x124\n" +
	"\n" +
	"asset_type\x18\x02 \x01(\x0e2\x15.marketdata.AssetTypeR\tassetType\"\xad\x01\n" +
	"\rPriceResponse\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\x12\x10\n" +
	"\x03bid\x18\x02 \x01(\x03R\x03bid\x12\x10\n" +
	"\x03ask\x18\x03 \x01(\x03R\x03ask\x12\x12\n" +
	"\x04last\x18\x04 \x01(\x03R\x04last\x12\x16\n" +
	"\x06volume\x18\x05 \x01(\x03R\x06volume\x12\x1c\n" +
	"\ttimestamp\x18\x06 \x01(\x03R\ttimestamp\x12\x16\n" +
	"\x06source\x18\a \x01(\tR\x06source\"\xca\x01\n" +
	"\x0eHistoryRequest\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\x124\n" +
	"\n" +
	"asset_type\x18\x02 \x01(\x0e2\x15.marketdata.AssetTypeR\tassetType\x120\n" +
	"\binterval\x18\x03 \x01(\x0e2\x14.marketdata.IntervalR\binterval\x12\x12\n" +
	"\x04from\x18\x04 \x01(\x03R\x04from\x12\x0e\n" +
	"\x02to\x18\x05 \x01(\x03R\x02to\x12\x14\n" +
	"\x05limit\x18\x06 \x01(\x05R\x05limit\"\xab\x01\n" +
	"\x0fHistoryResponse\x12(\n" +
	"\x04bars\x18\x01 \x03(\v2\x14.marketdata.OHLCVBarR\x04bars\x12\x19\n" +
	"\bhas_more\x18\x02 \x01(\bR\ahasMore\x12\x1d\n" +
	"\n" +
	"next_token\x18\x03 \x01(\tR\tnextToken\x12\x16\n" +
	"\x06source\x18\x04 \x01(\tR\x06source\x12\x1c\n" +
	"\ttimestamp\x18\x05 \x01(\x03R\ttimestamp\"[\n" +
	"\vInfoRequest\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\x124\n" +
	"\n" +
	"asset_type\x18\x02 \x01(\x0e2\x15.marketdata.AssetTypeR\tassetType\"e\n" +
	"\rSearchRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12\x1d\n" +
	"\n" +
	"asset_type\x18\x02 \x01(\tR\tassetType\x12\x1f\n" +
	"\vmax_results\x18\x03 \x01(\x05R\n" +
	"maxResults\"\xe9\x02\n" +
	"\fSearchResult\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1a\n" +
	"\bexchange\x18\x03 \x01(\tR\bexchange\x12#\n" +
	"\rexchange_code\x18\x04 \x01(\tR\fexchangeCode\x12\x18\n" +
	"\acountry\x18\x05 \x01(\tR\acountry\x12\x1a\n" +
	"\bcurrency\x18\x06 \x01(\tR\bcurrency\x12\x1d\n" +
	"\n" +
	"asset_type\x18\a \x01(\tR\tassetType\x12'\n" +
	"\x0fprovider_source\x18\b \x01(\tR\x0eproviderSource\x120\n" +
	"\x14provider_external_id\x18\t \x01(\tR\x12providerExternalId\x12\x12\n" +
	"\x04isin\x18\n" +
	" \x01(\tR\x04isin\x12\x12\n" +
	"\x04figi\x18\v \x01(\tR\x04figi\x12\x14\n" +
	"\x05cusip\x18\f \x01(\tR\x05cusip\"~\n" +
	"\x0eSearchResponse\x122\n" +
	"\aresults\x18\x01 \x03(\v2\x18.marketdata.SearchResultR\aresults\x12\x1a\n" +
	"\bprovider\x18\x02 \x01(\tR\bprovider\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp\"\xbf\x04\n" +
	"\vCompanyInfo\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1a\n" +
	"\bexchange\x18\x03 \x01(\tR\bexchange\x12\x16\n" +
	"\x06sector\x18\x04 \x01(\tR\x06sector\x12\x1a\n" +
	"\bindustry\x18\x05 \x01(\tR\bindustry\x12\x1a\n" +
	"\bcurrency\x18\x06 \x01(\tR\bcurrency\x12\x1a\n" +
	"\btimezone\x18\a \x01(\tR\btimezone\x12\x1d\n" +
	"\n" +
	"market_cap\x18\b \x01(\x03R\tmarketCap\x12\x19\n" +
	"\bpe_ratio\x18\t \x01(\x01R\apeRatio\x12%\n" +
	"\x0edividend_yield\x18\n" +
	" \x01(\x01R\rdividendYield\x12\x12\n" +
	"\x04beta\x18\v \x01(\x03R\x04beta\x12-\n" +
	"\x12shares_outstanding\x18\f \x01(\x03R\x11sharesOutstanding\x12\x18\n" +
	"\arevenue\x18\r \x01(\x03R\arevenue\x12\x1a\n" +
	"\bearnings\x18\x0e \x01(\x03R\bearnings\x12\x12\n" +
	"\x04debt\x18\x0f \x01(\x03R\x04debt\x12\x10\n" +
	"\x03eps\x18\x10 \x01(\x01R\x03eps\x12-\n" +
	"\x13fifty_two_week_high\x18\x11 \x01(\x03R\x10fiftyTwoWeekHigh\x12+\n" +
	"\x12fifty_two_week_low\x18\x12 \x01(\x03R\x0ffiftyTwoWeekLow\x12 \n" +
	"\vdescription\x18\x13 \x01(\tR\vdescription\"\xd8\x03\n" +
	"\n" +
	"CryptoInfo\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1e\n" +
	"\n" +
	"blockchain\x18\x03 \x01(\tR\n" +
	"blockchain\x12\x1a\n" +
	"\bdecimals\x18\x04 \x01(\x05R\bdecimals\x12#\n" +
	"\ris_stablecoin\x18\x05 \x01(\bR\fisStablecoin\x12\x1d\n" +
	"\n" +
	"market_cap\x18\x06 \x01(\x03R\tmarketCap\x12\x1d\n" +
	"\n" +
	"volume_24h\x18\a \x01(\x03R\tvolume24h\x12-\n" +
	"\x12circulating_supply\x18\b \x01(\x03R\x11circulatingSupply\x12!\n" +
	"\ftotal_supply\x18\t \x01(\x03R\vtotalSupply\x12\x1d\n" +
	"\n" +
	"max_supply\x18\n" +
	" \x01(\x03R\tmaxSupply\x12\x10\n" +
	"\x03eps\x18\v \x01(\x01R\x03eps\x12-\n" +
	"\x13fifty_two_week_high\x18\f \x01(\x03R\x10fiftyTwoWeekHigh\x12+\n" +
	"\x12fifty_two_week_low\x18\r \x01(\x03R\x0ffiftyTwoWeekLow\x12 \n" +
	"\vdescription\x18\x0e \x01(\tR\vdescription\"\xb3\x01\n" +
	"\fInfoResponse\x123\n" +
	"\acompany\x18\x01 \x01(\v2\x17.marketdata.CompanyInfoH\x00R\acompany\x120\n" +
	"\x06crypto\x18\x02 \x01(\v2\x16.marketdata.CryptoInfoH\x00R\x06crypto\x12\x16\n" +
	"\x06source\x18\x03 \x01(\tR\x06source\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x03R\ttimestampB\x06\n" +
	"\x04info\"c\n" +
	"\x11BatchPriceRequest\x12\x18\n" +
	"\asymbols\x18\x01 \x03(\tR\asymbols\x124\n" +
	"\n" +
	"asset_type\x18\x02 \x01(\x0e2\x15.marketdata.AssetTypeR\tassetType\"\x8a\x01\n" +
	"\x0eBatchPriceItem\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\x12\x14\n" +
	"\x05price\x18\x02 \x01(\x03R\x05price\x12\x16\n" +
	"\x06volume\x18\x03 \x01(\x03R\x06volume\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x03R\ttimestamp\x12\x14\n" +
	"\x05error\x18\x05 \x01(\tR\x05error\"~\n" +
	"\x12BatchPriceResponse\x122\n" +
	"\x06prices\x18\x01 \x03(\v2\x1a.marketdata.BatchPriceItemR\x06prices\x12\x16\n" +
	"\x06source\x18\x02 \x01(\tR\x06source\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp*\x9d\x01\n" +
	"\bInterval\x12\x18\n" +
	"\x14INTERVAL_UNSPECIFIED\x10\x00\x12\x0f\n" +
	"\vINTERVAL_1M\x10\x01\x12\x0f\n" +
	"\vINTERVAL_5M\x10\x02\x12\x10\n" +
	"\fINTERVAL_15M\x10\x03\x12\x10\n" +
	"\fINTERVAL_30M\x10\x04\x12\x0f\n" +
	"\vINTERVAL_1H\x10\x05\x12\x0f\n" +
	"\vINTERVAL_4H\x10\x06\x12\x0f\n" +
	"\vINTERVAL_1D\x10\a*i\n" +
	"\tAssetType\x12\x1a\n" +
	"\x16ASSET_TYPE_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10ASSET_TYPE_STOCK\x10\x01\x12\x13\n" +
	"\x0fASSET_TYPE_FUND\x10\x02\x12\x15\n" +
	"\x11ASSET_TYPE_CRYPTO\x10\x032\xf6\x02\n" +
	"\x11MarketDataService\x12?\n" +
	"\bGetPrice\x12\x18.marketdata.PriceRequest\x1a\x19.marketdata.PriceResponse\x12E\n" +
	"\n" +
	"GetHistory\x12\x1a.marketdata.HistoryRequest\x1a\x1b.marketdata.HistoryResponse\x12<\n" +
	"\aGetInfo\x12\x17.marketdata.InfoRequest\x1a\x18.marketdata.InfoResponse\x12J\n" +
	"\x11SearchInstruments\x12\x19.marketdata.SearchRequest\x1a\x1a.marketdata.SearchResponse\x12O\n" +
	"\x0eGetBatchPrices\x12\x1d.marketdata.BatchPriceRequest\x1a\x1e.marketdata.BatchPriceResponseBBZ@github.com/yourorg/sigma-finance/server/internal/handler/grpc/pbb\x06proto3"

var (
	file_market_data_proto_rawDescOnce sync.Once
	file_market_data_proto_rawDescData []byte
)

func file_market_data_proto_rawDescGZIP() []byte {
	file_market_data_proto_rawDescOnce.Do(func() {
		file_market_data_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_market_data_proto_rawDesc), len(file_market_data_proto_rawDesc)))
	})
	return file_market_data_proto_rawDescData
}

var file_market_data_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_market_data_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_market_data_proto_goTypes = []any{
	(Interval)(0),              // 0: marketdata.Interval
	(AssetType)(0),             // 1: marketdata.AssetType
	(*OHLCVBar)(nil),           // 2: marketdata.OHLCVBar
	(*PriceRequest)(nil),       // 3: marketdata.PriceRequest
	(*PriceResponse)(nil),      // 4: marketdata.PriceResponse
	(*HistoryRequest)(nil),     // 5: marketdata.HistoryRequest
	(*HistoryResponse)(nil),    // 6: marketdata.HistoryResponse
	(*InfoRequest)(nil),        // 7: marketdata.InfoRequest
	(*SearchRequest)(nil),      // 8: marketdata.SearchRequest
	(*SearchResult)(nil),       // 9: marketdata.SearchResult
	(*SearchResponse)(nil),     // 10: marketdata.SearchResponse
	(*CompanyInfo)(nil),        // 11: marketdata.CompanyInfo
	(*CryptoInfo)(nil),         // 12: marketdata.CryptoInfo
	(*InfoResponse)(nil),       // 13: marketdata.InfoResponse
	(*BatchPriceRequest)(nil),  // 14: marketdata.BatchPriceRequest
	(*BatchPriceItem)(nil),     // 15: marketdata.BatchPriceItem
	(*BatchPriceResponse)(nil), // 16: marketdata.BatchPriceResponse
}
var file_market_data_proto_depIdxs = []int32{
	1,  // 0: marketdata.PriceRequest.asset_type:type_name -> marketdata.AssetType
	1,  // 1: marketdata.HistoryRequest.asset_type:type_name -> marketdata.AssetType
	0,  // 2: marketdata.HistoryRequest.interval:type_name -> marketdata.Interval
	2,  // 3: marketdata.HistoryResponse.bars:type_name -> marketdata.OHLCVBar
	1,  // 4: marketdata.InfoRequest.asset_type:type_name -> marketdata.AssetType
	9,  // 5: marketdata.SearchResponse.results:type_name -> marketdata.SearchResult
	11, // 6: marketdata.InfoResponse.company:type_name -> marketdata.CompanyInfo
	12, // 7: marketdata.InfoResponse.crypto:type_name -> marketdata.CryptoInfo
	1,  // 8: marketdata.BatchPriceRequest.asset_type:type_name -> marketdata.AssetType
	15, // 9: marketdata.BatchPriceResponse.prices:type_name -> marketdata.BatchPriceItem
	3,  // 10: marketdata.MarketDataService.GetPrice:input_type -> marketdata.PriceRequest
	5,  // 11: marketdata.MarketDataService.GetHistory:input_type -> marketdata.HistoryRequest
	7,  // 12: marketdata.MarketDataService.GetInfo:input_type -> marketdata.InfoRequest
	8,  // 13: marketdata.MarketDataService.SearchInstruments:input_type -> marketdata.SearchRequest
	14, // 14: marketdata.MarketDataService.GetBatchPrices:input_type -> marketdata.BatchPriceRequest
	4,  // 15: marketdata.MarketDataService.GetPrice:output_type -> marketdata.PriceResponse
	6,  // 16: marketdata.MarketDataService.GetHistory:output_type -> marketdata.HistoryResponse
	13, // 17: marketdata.MarketDataService.GetInfo:output_type -> marketdata.InfoResponse
	10, // 18: marketdata.MarketDataService.SearchInstruments:output_type -> marketdata.SearchResponse
	16, // 19: marketdata.MarketDataService.GetBatchPrices:output_type -> marketdata.BatchPriceResponse
	15, // [15:20] is the sub-list for method output_type
	10, // [10:15] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_market_data_proto_init() }
func file_market_data_proto_init() {
	if File_market_data_proto != nil {
		return
	}
	file_market_data_proto_msgTypes[11].OneofWrappers = []any{
		(*InfoResponse_Company)(nil),
		(*InfoResponse_Crypto)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_market_data_proto_rawDesc), len(file_market_data_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_market_data_proto_goTypes,
		DependencyIndexes: file_market_data_proto_depIdxs,
		EnumInfos:         file_market_data_proto_enumTypes,
		MessageInfos:      file_market_data_proto_msgTypes,
	}.Build()
	File_market_data_proto = out.File
	file_market_data_proto_goTypes = nil
	file_market_data_proto_depIdxs = nil
}
