/* eslint-disable */
import * as types from './graphql';
import { TypedDocumentNode as DocumentNode } from '@graphql-typed-document-node/core';

/**
 * Map of all GraphQL operations in the project.
 *
 * This map has several performance disadvantages:
 * 1. It is not tree-shakeable, so it will include all operations in the project.
 * 2. It is not minifiable, so the string of a GraphQL query will be multiple times inside the bundle.
 * 3. It does not support dead code elimination, so it will add unused operations.
 *
 * Therefore it is highly recommended to use the babel or swc plugin for production.
 * Learn more about it here: https://the-guild.dev/graphql/codegen/plugins/presets/preset-client#reducing-bundle-size
 */
type Documents = {
    "\n  query GetAssets($filter: AssetFilter, $pagination: PaginationInput, $orderBy: AssetOrder) {\n    assets(filter: $filter, pagination: $pagination, orderBy: $orderBy) {\n      id\n      name\n      symbol\n      currentValue\n      assetType {\n        id\n        name\n      }\n    }\n  }\n": typeof types.GetAssetsDocument,
    "\n  query GetAssetTypes {\n    assetTypes {\n      id\n      name\n    }\n  }\n": typeof types.GetAssetTypesDocument,
    "\n  mutation AddAssetToPortfolio($input: PortfolioAssetInput!) {\n    addAssetToPortfolio(input: $input) {\n      asset {\n        id\n        name\n        symbol\n        currentValue\n        assetType {\n          id\n          name\n        }\n      }\n      quantity\n      averagePurchasePrice\n      ownershipPct\n    }\n  }\n": typeof types.AddAssetToPortfolioDocument,
    "\n  mutation RemoveAssetFromPortfolio($portfolioID: ID!, $assetID: ID!) {\n    removeAssetFromPortfolio(portfolioID: $portfolioID, assetID: $assetID)\n  }\n": typeof types.RemoveAssetFromPortfolioDocument,
    "\n\t\t\t\tfragment PortfolioFields on Portfolio {\n\t\t\t\t\tid\n\t\t\t\t\tname\n\t\t\t\t\tdescription\n\t\t\t\t\tcreatedAt\n\t\t\t\t\tupdatedAt\n\t\t\t\t}\n\t\t\t": typeof types.PortfolioFieldsFragmentDoc,
    "\n  query GetOptimizedDashboardData($userID: ID!) {\n    portfolios(filter: { userID: $userID }) {\n      id\n      name\n      assets {\n        asset {\n          id\n          name\n          symbol\n          currentValue\n          assetType {\n            name\n          }\n        }\n        quantity\n        averagePurchasePrice\n        ownershipPct\n      }\n    }\n    transactions(\n      filter: { userID: $userID }\n      pagination: { limit: 5 }\n      orderBy: { field: TRANSACTION_DATE, direction: DESC }\n    ) {\n      id\n      transactionType\n      quantity\n      pricePerUnit\n      transactionDate\n      asset {\n        id\n        name\n        symbol\n      }\n      portfolio {\n        id\n        name\n      }\n    }\n  }\n  ": typeof types.GetOptimizedDashboardDataDocument,
    "\n  query GetPortfolioCards($userID: ID!) {\n    portfolios(filter: { userID: $userID }) {\n      id\n      name\n      assets {\n        asset {\n          id\n          currentValue\n          assetType {\n            name\n          }\n        }\n        quantity\n        averagePurchasePrice\n        ownershipPct\n      }\n    }\n  }\n  ": typeof types.GetPortfolioCardsDocument,
    "\n  query GetAssetPerformanceOptimized($userID: ID!, $limit: Int = 10) {\n    assets(\n      filter: { userID: $userID }\n      pagination: { limit: $limit }\n    ) {\n      id\n      name\n      symbol\n      currentValue\n      purchasePrice\n      assetType {\n        name\n      }\n      positions {\n        quantity\n        averagePurchasePrice\n        ownershipPct\n      }\n    }\n  }\n  ": typeof types.GetAssetPerformanceOptimizedDocument,
    "\n  query GetRecentTransactionsMinimal($userID: ID!, $limit: Int = 5) {\n    transactions(\n      filter: { userID: $userID }\n      pagination: { limit: $limit }\n      orderBy: { field: TRANSACTION_DATE, direction: DESC }\n    ) {\n      id\n      transactionType\n      quantity\n      pricePerUnit\n      transactionDate\n      asset {\n        name\n        symbol\n      }\n      portfolio {\n        name\n      }\n    }\n  }\n  ": typeof types.GetRecentTransactionsMinimalDocument,
    "\n  fragment PortfolioCoreFields on Portfolio {\n    id\n    name\n    assets {\n      asset {\n        id\n        name\n        symbol\n        currentValue\n        assetType {\n          name\n        }\n      }\n      quantity\n      averagePurchasePrice\n      ownershipPct\n    }\n  }\n  ": typeof types.PortfolioCoreFieldsFragmentDoc,
    "\n  fragment AssetCoreFields on Asset {\n    id\n    name\n    symbol\n    currentValue\n    assetType {\n      name\n    }\n  }\n  ": typeof types.AssetCoreFieldsFragmentDoc,
    "\n  fragment TransactionCoreFields on Transaction {\n    id\n    transactionType\n    quantity\n    pricePerUnit\n    transactionDate\n    asset {\n      name\n      symbol\n    }\n    portfolio {\n      name\n    }\n  }\n  ": typeof types.TransactionCoreFieldsFragmentDoc,
    "\n  fragment PortfolioCoreFields on Portfolio {\n    id\n    name\n    assets {\n      asset {\n        id\n        name\n        symbol\n        currentValue\n        assetType {\n          name\n        }\n      }\n      quantity\n      averagePurchasePrice\n      ownershipPct\n    }\n  }\n\n  fragment TransactionCoreFields on Transaction {\n    id\n    transactionType\n    quantity\n    pricePerUnit\n    transactionDate\n    asset {\n      name\n      symbol\n    }\n    portfolio {\n      name\n    }\n  }\n\n  query GetDashboardWithFragments($userID: ID!) {\n    portfolios(filter: { userID: $userID }) {\n      ...PortfolioCoreFields\n    }\n    transactions(\n      filter: { userID: $userID }\n      pagination: { limit: 5 }\n      orderBy: { field: TRANSACTION_DATE, direction: DESC }\n    ) {\n      ...TransactionCoreFields\n    }\n  }\n  ": typeof types.PortfolioCoreFieldsFragmentDoc,
    "\n  subscription DashboardDataUpdates($userID: ID!) {\n    portfolioUpdates(userID: $userID) {\n      type\n      portfolio {\n        id\n        name\n        assets {\n          asset {\n            id\n            name\n            symbol\n            currentValue\n            assetType {\n              name\n            }\n          }\n          quantity\n          averagePurchasePrice\n          ownershipPct\n        }\n      }\n    }\n  }\n  ": typeof types.DashboardDataUpdatesDocument,
    "\n  subscription TransactionUpdates($userID: ID!) {\n    transactionUpdates(userID: $userID) {\n      type\n      transaction {\n        id\n        transactionType\n        quantity\n        pricePerUnit\n        transactionDate\n        asset {\n          id\n          name\n          symbol\n        }\n        portfolio {\n          id\n          name\n        }\n      }\n    }\n  }\n": typeof types.TransactionUpdatesDocument,
    "\n  query GetDashboardCritical($userID: ID!) {\n    portfolios(filter: { userID: $userID }) {\n      id\n      name\n      assets {\n        asset {\n          id\n          name\n          symbol\n          currentValue\n          assetType {\n            name\n          }\n        }\n        quantity\n        averagePurchasePrice\n        ownershipPct\n      }\n    }\n  }\n  ": typeof types.GetDashboardCriticalDocument,
    "\n  query GetDashboardSecondary($userID: ID!) {\n    transactions(\n      filter: { userID: $userID }\n      pagination: { limit: 5 }\n      orderBy: { field: TRANSACTION_DATE, direction: DESC }\n    ) {\n      id\n      transactionType\n      quantity\n      pricePerUnit\n      transactionDate\n      asset {\n        name\n        symbol\n      }\n      portfolio {\n        name\n      }\n    }\n  }\n  ": typeof types.GetDashboardSecondaryDocument,
    "\n  query GetPortfolioSummary($portfolioId: ID!) {\n    portfolio(id: $portfolioId) {\n      id\n      name\n      analytics {\n        totalValue\n        totalGainLoss\n        totalGainLossPercent\n      }\n    }\n  }\n": typeof types.GetPortfolioSummaryDocument,
    "\n  query GetAssetAllocation($portfolioId: ID!) {\n    portfolio(id: $portfolioId) {\n      id\n      analytics {\n        assetAllocation {\n          assetType\n          value\n          percentage\n          count\n        }\n      }\n    }\n  }\n": typeof types.GetAssetAllocationDocument,
    "\n  mutation CreatePortfolio($input: CreatePortfolioInput!) {\n    createPortfolio(input: $input) {\n      id\n      name\n      description\n      createdAt\n      updatedAt\n    }\n  }\n": typeof types.CreatePortfolioDocument,
    "\n  mutation UpdatePortfolio($id: ID!, $input: UpdatePortfolioInput!) {\n    updatePortfolio(id: $id, input: $input) {\n      id\n      name\n      description\n      updatedAt\n    }\n  }\n": typeof types.UpdatePortfolioDocument,
    "\n  mutation DeletePortfolio($id: ID!) {\n    deletePortfolio(id: $id)\n  }\n": typeof types.DeletePortfolioDocument,
    "\n  mutation DuplicatePortfolio($input: DuplicatePortfolioInput!) {\n    duplicatePortfolio(input: $input) {\n      id\n      name\n      description\n      createdAt\n      updatedAt\n      assets {\n        asset {\n          id\n          name\n          symbol\n          currentValue\n          assetType {\n            name\n          }\n        }\n        quantity\n        averagePurchasePrice\n        ownershipPct\n      }\n    }\n  }\n": typeof types.DuplicatePortfolioDocument,
    "\n\tquery GetPortfoliosWithAnalytics($userID: ID!) {\n\t\tportfolios(filter: { userID: $userID }) {\n\t\t\tid\n\t\t\tname\n\t\t\tdescription\n\t\t\tassets {\n\t\t\t\tquantity\n\t\t\t}\n\t\t\tanalytics {\n\t\t\t\ttotalValue\n\t\t\t\ttotalGainLossPercent\n\t\t\t}\n\t\t}\n\t}\n": typeof types.GetPortfoliosWithAnalyticsDocument,
};
const documents: Documents = {
    "\n  query GetAssets($filter: AssetFilter, $pagination: PaginationInput, $orderBy: AssetOrder) {\n    assets(filter: $filter, pagination: $pagination, orderBy: $orderBy) {\n      id\n      name\n      symbol\n      currentValue\n      assetType {\n        id\n        name\n      }\n    }\n  }\n": types.GetAssetsDocument,
    "\n  query GetAssetTypes {\n    assetTypes {\n      id\n      name\n    }\n  }\n": types.GetAssetTypesDocument,
    "\n  mutation AddAssetToPortfolio($input: PortfolioAssetInput!) {\n    addAssetToPortfolio(input: $input) {\n      asset {\n        id\n        name\n        symbol\n        currentValue\n        assetType {\n          id\n          name\n        }\n      }\n      quantity\n      averagePurchasePrice\n      ownershipPct\n    }\n  }\n": types.AddAssetToPortfolioDocument,
    "\n  mutation RemoveAssetFromPortfolio($portfolioID: ID!, $assetID: ID!) {\n    removeAssetFromPortfolio(portfolioID: $portfolioID, assetID: $assetID)\n  }\n": types.RemoveAssetFromPortfolioDocument,
    "\n\t\t\t\tfragment PortfolioFields on Portfolio {\n\t\t\t\t\tid\n\t\t\t\t\tname\n\t\t\t\t\tdescription\n\t\t\t\t\tcreatedAt\n\t\t\t\t\tupdatedAt\n\t\t\t\t}\n\t\t\t": types.PortfolioFieldsFragmentDoc,
    "\n  query GetOptimizedDashboardData($userID: ID!) {\n    portfolios(filter: { userID: $userID }) {\n      id\n      name\n      assets {\n        asset {\n          id\n          name\n          symbol\n          currentValue\n          assetType {\n            name\n          }\n        }\n        quantity\n        averagePurchasePrice\n        ownershipPct\n      }\n    }\n    transactions(\n      filter: { userID: $userID }\n      pagination: { limit: 5 }\n      orderBy: { field: TRANSACTION_DATE, direction: DESC }\n    ) {\n      id\n      transactionType\n      quantity\n      pricePerUnit\n      transactionDate\n      asset {\n        id\n        name\n        symbol\n      }\n      portfolio {\n        id\n        name\n      }\n    }\n  }\n  ": types.GetOptimizedDashboardDataDocument,
    "\n  query GetPortfolioCards($userID: ID!) {\n    portfolios(filter: { userID: $userID }) {\n      id\n      name\n      assets {\n        asset {\n          id\n          currentValue\n          assetType {\n            name\n          }\n        }\n        quantity\n        averagePurchasePrice\n        ownershipPct\n      }\n    }\n  }\n  ": types.GetPortfolioCardsDocument,
    "\n  query GetAssetPerformanceOptimized($userID: ID!, $limit: Int = 10) {\n    assets(\n      filter: { userID: $userID }\n      pagination: { limit: $limit }\n    ) {\n      id\n      name\n      symbol\n      currentValue\n      purchasePrice\n      assetType {\n        name\n      }\n      positions {\n        quantity\n        averagePurchasePrice\n        ownershipPct\n      }\n    }\n  }\n  ": types.GetAssetPerformanceOptimizedDocument,
    "\n  query GetRecentTransactionsMinimal($userID: ID!, $limit: Int = 5) {\n    transactions(\n      filter: { userID: $userID }\n      pagination: { limit: $limit }\n      orderBy: { field: TRANSACTION_DATE, direction: DESC }\n    ) {\n      id\n      transactionType\n      quantity\n      pricePerUnit\n      transactionDate\n      asset {\n        name\n        symbol\n      }\n      portfolio {\n        name\n      }\n    }\n  }\n  ": types.GetRecentTransactionsMinimalDocument,
    "\n  fragment PortfolioCoreFields on Portfolio {\n    id\n    name\n    assets {\n      asset {\n        id\n        name\n        symbol\n        currentValue\n        assetType {\n          name\n        }\n      }\n      quantity\n      averagePurchasePrice\n      ownershipPct\n    }\n  }\n  ": types.PortfolioCoreFieldsFragmentDoc,
    "\n  fragment AssetCoreFields on Asset {\n    id\n    name\n    symbol\n    currentValue\n    assetType {\n      name\n    }\n  }\n  ": types.AssetCoreFieldsFragmentDoc,
    "\n  fragment TransactionCoreFields on Transaction {\n    id\n    transactionType\n    quantity\n    pricePerUnit\n    transactionDate\n    asset {\n      name\n      symbol\n    }\n    portfolio {\n      name\n    }\n  }\n  ": types.TransactionCoreFieldsFragmentDoc,
    "\n  fragment PortfolioCoreFields on Portfolio {\n    id\n    name\n    assets {\n      asset {\n        id\n        name\n        symbol\n        currentValue\n        assetType {\n          name\n        }\n      }\n      quantity\n      averagePurchasePrice\n      ownershipPct\n    }\n  }\n\n  fragment TransactionCoreFields on Transaction {\n    id\n    transactionType\n    quantity\n    pricePerUnit\n    transactionDate\n    asset {\n      name\n      symbol\n    }\n    portfolio {\n      name\n    }\n  }\n\n  query GetDashboardWithFragments($userID: ID!) {\n    portfolios(filter: { userID: $userID }) {\n      ...PortfolioCoreFields\n    }\n    transactions(\n      filter: { userID: $userID }\n      pagination: { limit: 5 }\n      orderBy: { field: TRANSACTION_DATE, direction: DESC }\n    ) {\n      ...TransactionCoreFields\n    }\n  }\n  ": types.PortfolioCoreFieldsFragmentDoc,
    "\n  subscription DashboardDataUpdates($userID: ID!) {\n    portfolioUpdates(userID: $userID) {\n      type\n      portfolio {\n        id\n        name\n        assets {\n          asset {\n            id\n            name\n            symbol\n            currentValue\n            assetType {\n              name\n            }\n          }\n          quantity\n          averagePurchasePrice\n          ownershipPct\n        }\n      }\n    }\n  }\n  ": types.DashboardDataUpdatesDocument,
    "\n  subscription TransactionUpdates($userID: ID!) {\n    transactionUpdates(userID: $userID) {\n      type\n      transaction {\n        id\n        transactionType\n        quantity\n        pricePerUnit\n        transactionDate\n        asset {\n          id\n          name\n          symbol\n        }\n        portfolio {\n          id\n          name\n        }\n      }\n    }\n  }\n": types.TransactionUpdatesDocument,
    "\n  query GetDashboardCritical($userID: ID!) {\n    portfolios(filter: { userID: $userID }) {\n      id\n      name\n      assets {\n        asset {\n          id\n          name\n          symbol\n          currentValue\n          assetType {\n            name\n          }\n        }\n        quantity\n        averagePurchasePrice\n        ownershipPct\n      }\n    }\n  }\n  ": types.GetDashboardCriticalDocument,
    "\n  query GetDashboardSecondary($userID: ID!) {\n    transactions(\n      filter: { userID: $userID }\n      pagination: { limit: 5 }\n      orderBy: { field: TRANSACTION_DATE, direction: DESC }\n    ) {\n      id\n      transactionType\n      quantity\n      pricePerUnit\n      transactionDate\n      asset {\n        name\n        symbol\n      }\n      portfolio {\n        name\n      }\n    }\n  }\n  ": types.GetDashboardSecondaryDocument,
    "\n  query GetPortfolioSummary($portfolioId: ID!) {\n    portfolio(id: $portfolioId) {\n      id\n      name\n      analytics {\n        totalValue\n        totalGainLoss\n        totalGainLossPercent\n      }\n    }\n  }\n": types.GetPortfolioSummaryDocument,
    "\n  query GetAssetAllocation($portfolioId: ID!) {\n    portfolio(id: $portfolioId) {\n      id\n      analytics {\n        assetAllocation {\n          assetType\n          value\n          percentage\n          count\n        }\n      }\n    }\n  }\n": types.GetAssetAllocationDocument,
    "\n  mutation CreatePortfolio($input: CreatePortfolioInput!) {\n    createPortfolio(input: $input) {\n      id\n      name\n      description\n      createdAt\n      updatedAt\n    }\n  }\n": types.CreatePortfolioDocument,
    "\n  mutation UpdatePortfolio($id: ID!, $input: UpdatePortfolioInput!) {\n    updatePortfolio(id: $id, input: $input) {\n      id\n      name\n      description\n      updatedAt\n    }\n  }\n": types.UpdatePortfolioDocument,
    "\n  mutation DeletePortfolio($id: ID!) {\n    deletePortfolio(id: $id)\n  }\n": types.DeletePortfolioDocument,
    "\n  mutation DuplicatePortfolio($input: DuplicatePortfolioInput!) {\n    duplicatePortfolio(input: $input) {\n      id\n      name\n      description\n      createdAt\n      updatedAt\n      assets {\n        asset {\n          id\n          name\n          symbol\n          currentValue\n          assetType {\n            name\n          }\n        }\n        quantity\n        averagePurchasePrice\n        ownershipPct\n      }\n    }\n  }\n": types.DuplicatePortfolioDocument,
    "\n\tquery GetPortfoliosWithAnalytics($userID: ID!) {\n\t\tportfolios(filter: { userID: $userID }) {\n\t\t\tid\n\t\t\tname\n\t\t\tdescription\n\t\t\tassets {\n\t\t\t\tquantity\n\t\t\t}\n\t\t\tanalytics {\n\t\t\t\ttotalValue\n\t\t\t\ttotalGainLossPercent\n\t\t\t}\n\t\t}\n\t}\n": types.GetPortfoliosWithAnalyticsDocument,
};

/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 *
 *
 * @example
 * ```ts
 * const query = graphql(`query GetUser($id: ID!) { user(id: $id) { name } }`);
 * ```
 *
 * The query argument is unknown!
 * Please regenerate the types.
 */
export function graphql(source: string): unknown;

/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query GetAssets($filter: AssetFilter, $pagination: PaginationInput, $orderBy: AssetOrder) {\n    assets(filter: $filter, pagination: $pagination, orderBy: $orderBy) {\n      id\n      name\n      symbol\n      currentValue\n      assetType {\n        id\n        name\n      }\n    }\n  }\n"): (typeof documents)["\n  query GetAssets($filter: AssetFilter, $pagination: PaginationInput, $orderBy: AssetOrder) {\n    assets(filter: $filter, pagination: $pagination, orderBy: $orderBy) {\n      id\n      name\n      symbol\n      currentValue\n      assetType {\n        id\n        name\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query GetAssetTypes {\n    assetTypes {\n      id\n      name\n    }\n  }\n"): (typeof documents)["\n  query GetAssetTypes {\n    assetTypes {\n      id\n      name\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation AddAssetToPortfolio($input: PortfolioAssetInput!) {\n    addAssetToPortfolio(input: $input) {\n      asset {\n        id\n        name\n        symbol\n        currentValue\n        assetType {\n          id\n          name\n        }\n      }\n      quantity\n      averagePurchasePrice\n      ownershipPct\n    }\n  }\n"): (typeof documents)["\n  mutation AddAssetToPortfolio($input: PortfolioAssetInput!) {\n    addAssetToPortfolio(input: $input) {\n      asset {\n        id\n        name\n        symbol\n        currentValue\n        assetType {\n          id\n          name\n        }\n      }\n      quantity\n      averagePurchasePrice\n      ownershipPct\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation RemoveAssetFromPortfolio($portfolioID: ID!, $assetID: ID!) {\n    removeAssetFromPortfolio(portfolioID: $portfolioID, assetID: $assetID)\n  }\n"): (typeof documents)["\n  mutation RemoveAssetFromPortfolio($portfolioID: ID!, $assetID: ID!) {\n    removeAssetFromPortfolio(portfolioID: $portfolioID, assetID: $assetID)\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n\t\t\t\tfragment PortfolioFields on Portfolio {\n\t\t\t\t\tid\n\t\t\t\t\tname\n\t\t\t\t\tdescription\n\t\t\t\t\tcreatedAt\n\t\t\t\t\tupdatedAt\n\t\t\t\t}\n\t\t\t"): (typeof documents)["\n\t\t\t\tfragment PortfolioFields on Portfolio {\n\t\t\t\t\tid\n\t\t\t\t\tname\n\t\t\t\t\tdescription\n\t\t\t\t\tcreatedAt\n\t\t\t\t\tupdatedAt\n\t\t\t\t}\n\t\t\t"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query GetOptimizedDashboardData($userID: ID!) {\n    portfolios(filter: { userID: $userID }) {\n      id\n      name\n      assets {\n        asset {\n          id\n          name\n          symbol\n          currentValue\n          assetType {\n            name\n          }\n        }\n        quantity\n        averagePurchasePrice\n        ownershipPct\n      }\n    }\n    transactions(\n      filter: { userID: $userID }\n      pagination: { limit: 5 }\n      orderBy: { field: TRANSACTION_DATE, direction: DESC }\n    ) {\n      id\n      transactionType\n      quantity\n      pricePerUnit\n      transactionDate\n      asset {\n        id\n        name\n        symbol\n      }\n      portfolio {\n        id\n        name\n      }\n    }\n  }\n  "): (typeof documents)["\n  query GetOptimizedDashboardData($userID: ID!) {\n    portfolios(filter: { userID: $userID }) {\n      id\n      name\n      assets {\n        asset {\n          id\n          name\n          symbol\n          currentValue\n          assetType {\n            name\n          }\n        }\n        quantity\n        averagePurchasePrice\n        ownershipPct\n      }\n    }\n    transactions(\n      filter: { userID: $userID }\n      pagination: { limit: 5 }\n      orderBy: { field: TRANSACTION_DATE, direction: DESC }\n    ) {\n      id\n      transactionType\n      quantity\n      pricePerUnit\n      transactionDate\n      asset {\n        id\n        name\n        symbol\n      }\n      portfolio {\n        id\n        name\n      }\n    }\n  }\n  "];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query GetPortfolioCards($userID: ID!) {\n    portfolios(filter: { userID: $userID }) {\n      id\n      name\n      assets {\n        asset {\n          id\n          currentValue\n          assetType {\n            name\n          }\n        }\n        quantity\n        averagePurchasePrice\n        ownershipPct\n      }\n    }\n  }\n  "): (typeof documents)["\n  query GetPortfolioCards($userID: ID!) {\n    portfolios(filter: { userID: $userID }) {\n      id\n      name\n      assets {\n        asset {\n          id\n          currentValue\n          assetType {\n            name\n          }\n        }\n        quantity\n        averagePurchasePrice\n        ownershipPct\n      }\n    }\n  }\n  "];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query GetAssetPerformanceOptimized($userID: ID!, $limit: Int = 10) {\n    assets(\n      filter: { userID: $userID }\n      pagination: { limit: $limit }\n    ) {\n      id\n      name\n      symbol\n      currentValue\n      purchasePrice\n      assetType {\n        name\n      }\n      positions {\n        quantity\n        averagePurchasePrice\n        ownershipPct\n      }\n    }\n  }\n  "): (typeof documents)["\n  query GetAssetPerformanceOptimized($userID: ID!, $limit: Int = 10) {\n    assets(\n      filter: { userID: $userID }\n      pagination: { limit: $limit }\n    ) {\n      id\n      name\n      symbol\n      currentValue\n      purchasePrice\n      assetType {\n        name\n      }\n      positions {\n        quantity\n        averagePurchasePrice\n        ownershipPct\n      }\n    }\n  }\n  "];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query GetRecentTransactionsMinimal($userID: ID!, $limit: Int = 5) {\n    transactions(\n      filter: { userID: $userID }\n      pagination: { limit: $limit }\n      orderBy: { field: TRANSACTION_DATE, direction: DESC }\n    ) {\n      id\n      transactionType\n      quantity\n      pricePerUnit\n      transactionDate\n      asset {\n        name\n        symbol\n      }\n      portfolio {\n        name\n      }\n    }\n  }\n  "): (typeof documents)["\n  query GetRecentTransactionsMinimal($userID: ID!, $limit: Int = 5) {\n    transactions(\n      filter: { userID: $userID }\n      pagination: { limit: $limit }\n      orderBy: { field: TRANSACTION_DATE, direction: DESC }\n    ) {\n      id\n      transactionType\n      quantity\n      pricePerUnit\n      transactionDate\n      asset {\n        name\n        symbol\n      }\n      portfolio {\n        name\n      }\n    }\n  }\n  "];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  fragment PortfolioCoreFields on Portfolio {\n    id\n    name\n    assets {\n      asset {\n        id\n        name\n        symbol\n        currentValue\n        assetType {\n          name\n        }\n      }\n      quantity\n      averagePurchasePrice\n      ownershipPct\n    }\n  }\n  "): (typeof documents)["\n  fragment PortfolioCoreFields on Portfolio {\n    id\n    name\n    assets {\n      asset {\n        id\n        name\n        symbol\n        currentValue\n        assetType {\n          name\n        }\n      }\n      quantity\n      averagePurchasePrice\n      ownershipPct\n    }\n  }\n  "];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  fragment AssetCoreFields on Asset {\n    id\n    name\n    symbol\n    currentValue\n    assetType {\n      name\n    }\n  }\n  "): (typeof documents)["\n  fragment AssetCoreFields on Asset {\n    id\n    name\n    symbol\n    currentValue\n    assetType {\n      name\n    }\n  }\n  "];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  fragment TransactionCoreFields on Transaction {\n    id\n    transactionType\n    quantity\n    pricePerUnit\n    transactionDate\n    asset {\n      name\n      symbol\n    }\n    portfolio {\n      name\n    }\n  }\n  "): (typeof documents)["\n  fragment TransactionCoreFields on Transaction {\n    id\n    transactionType\n    quantity\n    pricePerUnit\n    transactionDate\n    asset {\n      name\n      symbol\n    }\n    portfolio {\n      name\n    }\n  }\n  "];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  fragment PortfolioCoreFields on Portfolio {\n    id\n    name\n    assets {\n      asset {\n        id\n        name\n        symbol\n        currentValue\n        assetType {\n          name\n        }\n      }\n      quantity\n      averagePurchasePrice\n      ownershipPct\n    }\n  }\n\n  fragment TransactionCoreFields on Transaction {\n    id\n    transactionType\n    quantity\n    pricePerUnit\n    transactionDate\n    asset {\n      name\n      symbol\n    }\n    portfolio {\n      name\n    }\n  }\n\n  query GetDashboardWithFragments($userID: ID!) {\n    portfolios(filter: { userID: $userID }) {\n      ...PortfolioCoreFields\n    }\n    transactions(\n      filter: { userID: $userID }\n      pagination: { limit: 5 }\n      orderBy: { field: TRANSACTION_DATE, direction: DESC }\n    ) {\n      ...TransactionCoreFields\n    }\n  }\n  "): (typeof documents)["\n  fragment PortfolioCoreFields on Portfolio {\n    id\n    name\n    assets {\n      asset {\n        id\n        name\n        symbol\n        currentValue\n        assetType {\n          name\n        }\n      }\n      quantity\n      averagePurchasePrice\n      ownershipPct\n    }\n  }\n\n  fragment TransactionCoreFields on Transaction {\n    id\n    transactionType\n    quantity\n    pricePerUnit\n    transactionDate\n    asset {\n      name\n      symbol\n    }\n    portfolio {\n      name\n    }\n  }\n\n  query GetDashboardWithFragments($userID: ID!) {\n    portfolios(filter: { userID: $userID }) {\n      ...PortfolioCoreFields\n    }\n    transactions(\n      filter: { userID: $userID }\n      pagination: { limit: 5 }\n      orderBy: { field: TRANSACTION_DATE, direction: DESC }\n    ) {\n      ...TransactionCoreFields\n    }\n  }\n  "];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  subscription DashboardDataUpdates($userID: ID!) {\n    portfolioUpdates(userID: $userID) {\n      type\n      portfolio {\n        id\n        name\n        assets {\n          asset {\n            id\n            name\n            symbol\n            currentValue\n            assetType {\n              name\n            }\n          }\n          quantity\n          averagePurchasePrice\n          ownershipPct\n        }\n      }\n    }\n  }\n  "): (typeof documents)["\n  subscription DashboardDataUpdates($userID: ID!) {\n    portfolioUpdates(userID: $userID) {\n      type\n      portfolio {\n        id\n        name\n        assets {\n          asset {\n            id\n            name\n            symbol\n            currentValue\n            assetType {\n              name\n            }\n          }\n          quantity\n          averagePurchasePrice\n          ownershipPct\n        }\n      }\n    }\n  }\n  "];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  subscription TransactionUpdates($userID: ID!) {\n    transactionUpdates(userID: $userID) {\n      type\n      transaction {\n        id\n        transactionType\n        quantity\n        pricePerUnit\n        transactionDate\n        asset {\n          id\n          name\n          symbol\n        }\n        portfolio {\n          id\n          name\n        }\n      }\n    }\n  }\n"): (typeof documents)["\n  subscription TransactionUpdates($userID: ID!) {\n    transactionUpdates(userID: $userID) {\n      type\n      transaction {\n        id\n        transactionType\n        quantity\n        pricePerUnit\n        transactionDate\n        asset {\n          id\n          name\n          symbol\n        }\n        portfolio {\n          id\n          name\n        }\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query GetDashboardCritical($userID: ID!) {\n    portfolios(filter: { userID: $userID }) {\n      id\n      name\n      assets {\n        asset {\n          id\n          name\n          symbol\n          currentValue\n          assetType {\n            name\n          }\n        }\n        quantity\n        averagePurchasePrice\n        ownershipPct\n      }\n    }\n  }\n  "): (typeof documents)["\n  query GetDashboardCritical($userID: ID!) {\n    portfolios(filter: { userID: $userID }) {\n      id\n      name\n      assets {\n        asset {\n          id\n          name\n          symbol\n          currentValue\n          assetType {\n            name\n          }\n        }\n        quantity\n        averagePurchasePrice\n        ownershipPct\n      }\n    }\n  }\n  "];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query GetDashboardSecondary($userID: ID!) {\n    transactions(\n      filter: { userID: $userID }\n      pagination: { limit: 5 }\n      orderBy: { field: TRANSACTION_DATE, direction: DESC }\n    ) {\n      id\n      transactionType\n      quantity\n      pricePerUnit\n      transactionDate\n      asset {\n        name\n        symbol\n      }\n      portfolio {\n        name\n      }\n    }\n  }\n  "): (typeof documents)["\n  query GetDashboardSecondary($userID: ID!) {\n    transactions(\n      filter: { userID: $userID }\n      pagination: { limit: 5 }\n      orderBy: { field: TRANSACTION_DATE, direction: DESC }\n    ) {\n      id\n      transactionType\n      quantity\n      pricePerUnit\n      transactionDate\n      asset {\n        name\n        symbol\n      }\n      portfolio {\n        name\n      }\n    }\n  }\n  "];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query GetPortfolioSummary($portfolioId: ID!) {\n    portfolio(id: $portfolioId) {\n      id\n      name\n      analytics {\n        totalValue\n        totalGainLoss\n        totalGainLossPercent\n      }\n    }\n  }\n"): (typeof documents)["\n  query GetPortfolioSummary($portfolioId: ID!) {\n    portfolio(id: $portfolioId) {\n      id\n      name\n      analytics {\n        totalValue\n        totalGainLoss\n        totalGainLossPercent\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  query GetAssetAllocation($portfolioId: ID!) {\n    portfolio(id: $portfolioId) {\n      id\n      analytics {\n        assetAllocation {\n          assetType\n          value\n          percentage\n          count\n        }\n      }\n    }\n  }\n"): (typeof documents)["\n  query GetAssetAllocation($portfolioId: ID!) {\n    portfolio(id: $portfolioId) {\n      id\n      analytics {\n        assetAllocation {\n          assetType\n          value\n          percentage\n          count\n        }\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation CreatePortfolio($input: CreatePortfolioInput!) {\n    createPortfolio(input: $input) {\n      id\n      name\n      description\n      createdAt\n      updatedAt\n    }\n  }\n"): (typeof documents)["\n  mutation CreatePortfolio($input: CreatePortfolioInput!) {\n    createPortfolio(input: $input) {\n      id\n      name\n      description\n      createdAt\n      updatedAt\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation UpdatePortfolio($id: ID!, $input: UpdatePortfolioInput!) {\n    updatePortfolio(id: $id, input: $input) {\n      id\n      name\n      description\n      updatedAt\n    }\n  }\n"): (typeof documents)["\n  mutation UpdatePortfolio($id: ID!, $input: UpdatePortfolioInput!) {\n    updatePortfolio(id: $id, input: $input) {\n      id\n      name\n      description\n      updatedAt\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation DeletePortfolio($id: ID!) {\n    deletePortfolio(id: $id)\n  }\n"): (typeof documents)["\n  mutation DeletePortfolio($id: ID!) {\n    deletePortfolio(id: $id)\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n  mutation DuplicatePortfolio($input: DuplicatePortfolioInput!) {\n    duplicatePortfolio(input: $input) {\n      id\n      name\n      description\n      createdAt\n      updatedAt\n      assets {\n        asset {\n          id\n          name\n          symbol\n          currentValue\n          assetType {\n            name\n          }\n        }\n        quantity\n        averagePurchasePrice\n        ownershipPct\n      }\n    }\n  }\n"): (typeof documents)["\n  mutation DuplicatePortfolio($input: DuplicatePortfolioInput!) {\n    duplicatePortfolio(input: $input) {\n      id\n      name\n      description\n      createdAt\n      updatedAt\n      assets {\n        asset {\n          id\n          name\n          symbol\n          currentValue\n          assetType {\n            name\n          }\n        }\n        quantity\n        averagePurchasePrice\n        ownershipPct\n      }\n    }\n  }\n"];
/**
 * The graphql function is used to parse GraphQL queries into a document that can be used by GraphQL clients.
 */
export function graphql(source: "\n\tquery GetPortfoliosWithAnalytics($userID: ID!) {\n\t\tportfolios(filter: { userID: $userID }) {\n\t\t\tid\n\t\t\tname\n\t\t\tdescription\n\t\t\tassets {\n\t\t\t\tquantity\n\t\t\t}\n\t\t\tanalytics {\n\t\t\t\ttotalValue\n\t\t\t\ttotalGainLossPercent\n\t\t\t}\n\t\t}\n\t}\n"): (typeof documents)["\n\tquery GetPortfoliosWithAnalytics($userID: ID!) {\n\t\tportfolios(filter: { userID: $userID }) {\n\t\t\tid\n\t\t\tname\n\t\t\tdescription\n\t\t\tassets {\n\t\t\t\tquantity\n\t\t\t}\n\t\t\tanalytics {\n\t\t\t\ttotalValue\n\t\t\t\ttotalGainLossPercent\n\t\t\t}\n\t\t}\n\t}\n"];

export function graphql(source: string) {
  return (documents as any)[source] ?? {};
}

export type DocumentType<TDocumentNode extends DocumentNode<any, any>> = TDocumentNode extends DocumentNode<  infer TType,  any>  ? TType  : never;