"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from grpc import aio as _aio
from proto import market_data_pb2 as _market_data_pb2
import abc as _abc_1
import grpc as _grpc
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import Self as _Self
else:
    from typing_extensions import Self as _Self

_T = _typing.TypeVar("_T")

class _MaybeAsyncIterator(_abc.AsyncIterator[_T], _abc.Iterator[_T], metaclass=_abc_1.ABCMeta): ...

class _ServicerContext(_grpc.ServicerContext, _aio.ServicerContext):  # type: ignore[misc, type-arg]
    ...

GRPC_GENERATED_VERSION: str
GRPC_VERSION: str

class MarketDataServiceStub:
    """MarketDataService provides market data via gRPC"""

    @_typing.overload
    def __new__(cls, channel: _grpc.Channel) -> _Self: ...
    @_typing.overload
    def __new__(cls, channel: _aio.Channel) -> MarketDataServiceAsyncStub: ...
    GetPrice: _grpc.UnaryUnaryMultiCallable[_market_data_pb2.PriceRequest, _market_data_pb2.PriceResponse]
    """GetPrice returns current price for a symbol"""
    GetHistory: _grpc.UnaryUnaryMultiCallable[_market_data_pb2.HistoryRequest, _market_data_pb2.HistoryResponse]
    """GetHistory returns historical OHLCV data"""
    GetInfo: _grpc.UnaryUnaryMultiCallable[_market_data_pb2.InfoRequest, _market_data_pb2.InfoResponse]
    """GetInfo returns company/fund information"""
    SearchInstruments: _grpc.UnaryUnaryMultiCallable[_market_data_pb2.SearchRequest, _market_data_pb2.SearchResponse]
    """SearchInstruments returns normalized instrument lookup results"""
    GetBatchPrices: _grpc.UnaryUnaryMultiCallable[_market_data_pb2.BatchPriceRequest, _market_data_pb2.BatchPriceResponse]
    """GetBatchPrices returns prices for multiple symbols"""

@_typing.type_check_only
class MarketDataServiceAsyncStub(MarketDataServiceStub):
    """MarketDataService provides market data via gRPC"""

    def __init__(self, channel: _aio.Channel) -> None: ...
    GetPrice: _aio.UnaryUnaryMultiCallable[_market_data_pb2.PriceRequest, _market_data_pb2.PriceResponse]  # type: ignore[assignment]
    """GetPrice returns current price for a symbol"""
    GetHistory: _aio.UnaryUnaryMultiCallable[_market_data_pb2.HistoryRequest, _market_data_pb2.HistoryResponse]  # type: ignore[assignment]
    """GetHistory returns historical OHLCV data"""
    GetInfo: _aio.UnaryUnaryMultiCallable[_market_data_pb2.InfoRequest, _market_data_pb2.InfoResponse]  # type: ignore[assignment]
    """GetInfo returns company/fund information"""
    SearchInstruments: _aio.UnaryUnaryMultiCallable[_market_data_pb2.SearchRequest, _market_data_pb2.SearchResponse]  # type: ignore[assignment]
    """SearchInstruments returns normalized instrument lookup results"""
    GetBatchPrices: _aio.UnaryUnaryMultiCallable[_market_data_pb2.BatchPriceRequest, _market_data_pb2.BatchPriceResponse]  # type: ignore[assignment]
    """GetBatchPrices returns prices for multiple symbols"""

class MarketDataServiceServicer(metaclass=_abc_1.ABCMeta):
    """MarketDataService provides market data via gRPC"""

    @_abc_1.abstractmethod
    def GetPrice(
        self,
        request: _market_data_pb2.PriceRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_market_data_pb2.PriceResponse, _abc.Awaitable[_market_data_pb2.PriceResponse]]:
        """GetPrice returns current price for a symbol"""

    @_abc_1.abstractmethod
    def GetHistory(
        self,
        request: _market_data_pb2.HistoryRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_market_data_pb2.HistoryResponse, _abc.Awaitable[_market_data_pb2.HistoryResponse]]:
        """GetHistory returns historical OHLCV data"""

    @_abc_1.abstractmethod
    def GetInfo(
        self,
        request: _market_data_pb2.InfoRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_market_data_pb2.InfoResponse, _abc.Awaitable[_market_data_pb2.InfoResponse]]:
        """GetInfo returns company/fund information"""

    @_abc_1.abstractmethod
    def SearchInstruments(
        self,
        request: _market_data_pb2.SearchRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_market_data_pb2.SearchResponse, _abc.Awaitable[_market_data_pb2.SearchResponse]]:
        """SearchInstruments returns normalized instrument lookup results"""

    @_abc_1.abstractmethod
    def GetBatchPrices(
        self,
        request: _market_data_pb2.BatchPriceRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_market_data_pb2.BatchPriceResponse, _abc.Awaitable[_market_data_pb2.BatchPriceResponse]]:
        """GetBatchPrices returns prices for multiple symbols"""

def add_MarketDataServiceServicer_to_server(servicer: MarketDataServiceServicer, server: _typing.Union[_grpc.Server, _aio.Server]) -> None: ...
