package graphql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.89

import (
	"context"
	"fmt"
	"log"
	"strings"
	"sigma_finance/internal/domain/model"
	gqlModel "sigma_finance/internal/handler/graphql/model"
	"sigma_finance/internal/handler/middleware"
	"sigma_finance/internal/service"
)

// Register is the resolver for the register field.
func (r *mutationResolver) Register(ctx context.Context, input gqlModel.RegisterInput) (*gqlModel.AuthResponse, error) {
	log.Printf("[INFO] [graphql] Register: started email=%s", maskEmail(input.Email))
	if r.AuthenticationService == nil {
		log.Printf("[ERROR] [graphql] Register: authentication service not configured")
		return nil, fmt.Errorf("authentication service not configured")
	}

	resp, err := r.AuthenticationService.Register(ctx, service.RegisterRequest{
		Email:    input.Email,
		Password: input.Password,
		Name:     input.Name,
	})
	if err != nil {
		log.Printf("[WARN] [graphql] Register: registration failed email=%s: %v", maskEmail(input.Email), err)
		return convertAuthErrorToGraphQL(err), nil
	}
	log.Printf("[INFO] [graphql] Register: completed user=%s", resp.User.ID)
	return mapAuthResponseToGQL(resp), nil
}

// Login is the resolver for the login field.
func (r *mutationResolver) Login(ctx context.Context, input gqlModel.LoginInput) (*gqlModel.AuthResponse, error) {
	log.Printf("[INFO] [graphql] Login: started email=%s", maskEmail(input.Email))
	if r.AuthenticationService == nil {
		log.Printf("[ERROR] [graphql] Login: authentication service not configured")
		return nil, fmt.Errorf("authentication service not configured")
	}

	resp, err := r.AuthenticationService.Login(ctx, service.LoginRequest{
		Email:     input.Email,
		Password:  input.Password,
		IPAddress: extractIPFromContext(ctx),
		UserAgent: extractUserAgentFromContext(ctx),
	})
	if err != nil {
		log.Printf("[WARN] [graphql] Login: login failed email=%s: %v", maskEmail(input.Email), err)
		return convertAuthErrorToGraphQL(err), nil
	}
	log.Printf("[INFO] [graphql] Login: completed user=%s", resp.User.ID)
	return mapAuthResponseToGQL(resp), nil
}

// Logout is the resolver for the logout field.
func (r *mutationResolver) Logout(ctx context.Context, input gqlModel.LogoutInput) (*gqlModel.LogoutResponse, error) {
	log.Printf("[INFO] [graphql] Logout: started")
	if r.AuthenticationService == nil {
		log.Printf("[ERROR] [graphql] Logout: authentication service not configured")
		return nil, fmt.Errorf("authentication service not configured")
	}

	userID := ""
	if user, err := middleware.RequireAuth(ctx); err == nil {
		userID = user.ID
	}

	if err := r.AuthenticationService.Logout(ctx, userID, input.Token); err != nil {
		log.Printf("[WARN] [graphql] Logout: logout failed user=%s: %v", userID, err)
		return convertLogoutErrorToGraphQL(err), nil
	}
	log.Printf("[INFO] [graphql] Logout: completed user=%s", userID)
	return &gqlModel.LogoutResponse{Success: true}, nil
}

// ResetPassword is the resolver for the resetPassword field.
func (r *mutationResolver) ResetPassword(ctx context.Context, input gqlModel.PasswordResetInput) (*gqlModel.PasswordResetResponse, error) {
	log.Printf("[INFO] [graphql] ResetPassword: started email=%s", maskEmail(input.Email))
	if r.AuthenticationService == nil {
		log.Printf("[ERROR] [graphql] ResetPassword: authentication service not configured")
		return nil, fmt.Errorf("authentication service not configured")
	}

	if err := r.AuthenticationService.ResetPassword(ctx, input.Email); err != nil {
		log.Printf("[WARN] [graphql] ResetPassword: reset failed email=%s: %v", maskEmail(input.Email), err)
		return convertPasswordResetErrorToGraphQL(err), nil
	}
	log.Printf("[INFO] [graphql] ResetPassword: completed email=%s", maskEmail(input.Email))
	return &gqlModel.PasswordResetResponse{Success: true}, nil
}

// ConfirmPasswordReset is the resolver for the confirmPasswordReset field.
func (r *mutationResolver) ConfirmPasswordReset(ctx context.Context, input gqlModel.PasswordResetConfirmInput) (*gqlModel.PasswordResetResponse, error) {
	log.Printf("[INFO] [graphql] ConfirmPasswordReset: started")
	if r.AuthenticationService == nil {
		log.Printf("[ERROR] [graphql] ConfirmPasswordReset: authentication service not configured")
		return nil, fmt.Errorf("authentication service not configured")
	}

	if err := r.AuthenticationService.ConfirmPasswordReset(ctx, input.Token, input.NewPassword); err != nil {
		log.Printf("[WARN] [graphql] ConfirmPasswordReset: reset failed: %v", err)
		return convertPasswordResetErrorToGraphQL(err), nil
	}
	log.Printf("[INFO] [graphql] ConfirmPasswordReset: completed")
	return &gqlModel.PasswordResetResponse{Success: true}, nil
}

// VerifyEmail is the resolver for the verifyEmail field.
func (r *mutationResolver) VerifyEmail(ctx context.Context, input gqlModel.EmailVerificationInput) (*gqlModel.EmailVerificationResponse, error) {
	log.Printf("[INFO] [graphql] VerifyEmail: started")
	if r.AuthenticationService == nil {
		log.Printf("[ERROR] [graphql] VerifyEmail: authentication service not configured")
		return nil, fmt.Errorf("authentication service not configured")
	}

	if err := r.AuthenticationService.VerifyEmail(ctx, input.Token); err != nil {
		log.Printf("[WARN] [graphql] VerifyEmail: verification failed: %v", err)
		return convertEmailVerificationErrorToGraphQL(err), nil
	}
	log.Printf("[INFO] [graphql] VerifyEmail: completed")
	return &gqlModel.EmailVerificationResponse{Success: true}, nil
}

// ResendVerification is the resolver for the resendVerification field.
func (r *mutationResolver) ResendVerification(ctx context.Context, input gqlModel.ResendVerificationInput) (*gqlModel.EmailVerificationResponse, error) {
	log.Printf("[INFO] [graphql] ResendVerification: started email=%s", maskEmail(input.Email))
	if r.AuthenticationService == nil {
		log.Printf("[ERROR] [graphql] ResendVerification: authentication service not configured")
		return nil, fmt.Errorf("authentication service not configured")
	}

	if err := r.AuthenticationService.ResendVerification(ctx, input.Email); err != nil {
		log.Printf("[WARN] [graphql] ResendVerification: resend failed email=%s: %v", maskEmail(input.Email), err)
		return convertEmailVerificationErrorToGraphQL(err), nil
	}
	log.Printf("[INFO] [graphql] ResendVerification: completed email=%s", maskEmail(input.Email))
	return &gqlModel.EmailVerificationResponse{Success: true}, nil
}

// RefreshToken is the resolver for the refreshToken field.
func (r *mutationResolver) RefreshToken(ctx context.Context, input gqlModel.RefreshTokenInput) (*gqlModel.AuthResponse, error) {
	log.Printf("[INFO] [graphql] RefreshToken: started")
	if r.AuthenticationService == nil {
		log.Printf("[ERROR] [graphql] RefreshToken: authentication service not configured")
		return nil, fmt.Errorf("authentication service not configured")
	}

	resp, err := r.AuthenticationService.RefreshToken(ctx, input.RefreshToken)
	if err != nil {
		log.Printf("[WARN] [graphql] RefreshToken: refresh failed: %v", err)
		return convertAuthErrorToGraphQL(err), nil
	}
	log.Printf("[INFO] [graphql] RefreshToken: completed user=%s", resp.User.ID)
	return mapAuthResponseToGQL(resp), nil
}

// Me is the resolver for the me field.
func (r *queryResolver) Me(ctx context.Context) (*gqlModel.AuthUser, error) {
	log.Printf("[INFO] [graphql] Me: started")
	authUser, err := middleware.RequireAuth(ctx)
	if err != nil {
		log.Printf("[WARN] [graphql] Me: auth required failed: %v", err)
		return nil, err
	}

	// Prefer canonical user data from user service when available.
	if r.UserService != nil {
		user, getErr := r.UserService.GetByID(ctx, authUser.ID)
		if getErr == nil && user != nil {
			return &gqlModel.AuthUser{
				ID:                  user.ID,
				Email:               user.Email,
				Name:                user.Name,
				EmailVerified:       user.EmailVerified,
				DisplayCurrency:     string(user.DisplayCurrency),
				ThemePreference:     string(user.ThemePreference),
				ThemeBaseColor:      string(user.ThemeBaseColor),
				ThemeAccentColor:    string(user.ThemeAccentColor),
				ThemeFontPreference: string(user.ThemeFontPreference),
				ThemeHeadingFont:    string(user.ThemeHeadingFont),
				ThemeMenuAccent:     string(user.ThemeMenuAccent),
				ThemeMenuColor:      string(user.ThemeMenuColor),
				ThemeStyle:          string(user.ThemeStyle),
				ThemeRadius:         user.ThemeRadius,
				ThemeRtl:            user.ThemeRTL,
			}, nil
		}
	}

	displayCurrency := "USD"
	themePreference := string(model.DefaultThemePreference)
	themeBaseColor := string(model.DefaultThemeBaseColor)
	themeAccentColor := string(model.DefaultThemeAccentColor)
	themeFontPreference := string(model.DefaultThemeFontPreference)
	themeHeadingFont := string(model.DefaultThemeHeadingFont)
	themeMenuAccent := string(model.DefaultThemeMenuAccent)
	themeMenuColor := string(model.DefaultThemeMenuColor)
	themeStyle := string(model.DefaultThemeStyle)
	themeRadius := model.DefaultThemeRadius
	themeRTL := model.DefaultThemeRTL
	return &gqlModel.AuthUser{
		ID:                  authUser.ID,
		Email:               authUser.Email,
		Name:                authUser.Name,
		EmailVerified:       authUser.EmailVerified,
		DisplayCurrency:     displayCurrency,
		ThemePreference:     themePreference,
		ThemeBaseColor:      themeBaseColor,
		ThemeAccentColor:    themeAccentColor,
		ThemeFontPreference: themeFontPreference,
		ThemeHeadingFont:    themeHeadingFont,
		ThemeMenuAccent:     themeMenuAccent,
		ThemeMenuColor:      themeMenuColor,
		ThemeStyle:          themeStyle,
		ThemeRadius:         themeRadius,
		ThemeRtl:            themeRTL,
	}, nil
}

// maskEmail masks an email address for logging purposes.
func maskEmail(email string) string {
	if len(email) < 8 {
		return "***"
	}
	return email[:3] + "***@" + email[strings.LastIndex(email, "@")+1:]
}
