package graphql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.89

import (
	"context"
	gqlModel "sigma_finance/internal/handler/graphql/model"
	"sigma_finance/internal/handler/middleware"
	"sigma_finance/internal/service"
)

// Register is the resolver for the register field.
func (r *mutationResolver) Register(ctx context.Context, input gqlModel.RegisterInput) (*gqlModel.AuthResponse, error) {
	req := service.RegisterRequest{
		Email:    input.Email,
		Password: input.Password,
		Name:     input.Name,
	}
	resp, err := r.AuthenticationService.Register(ctx, req)
	if err != nil {
		return convertAuthErrorToGraphQL(err), nil
	}
	return mapAuthResponseToGQL(resp), nil
}

// Login is the resolver for the login field.
func (r *mutationResolver) Login(ctx context.Context, input gqlModel.LoginInput) (*gqlModel.AuthResponse, error) {
	req := service.LoginRequest{
		Email:     input.Email,
		Password:  input.Password,
		IPAddress: extractIPFromContext(ctx),
		UserAgent: extractUserAgentFromContext(ctx),
	}
	resp, err := r.AuthenticationService.Login(ctx, req)
	if err != nil {
		return convertAuthErrorToGraphQL(err), nil
	}
	return mapAuthResponseToGQL(resp), nil
}

// Logout is the resolver for the logout field.
func (r *mutationResolver) Logout(ctx context.Context, input gqlModel.LogoutInput) (*gqlModel.LogoutResponse, error) {
	// Validate the JWT token to extract user_id
	if input.Token == "" {
		return &gqlModel.LogoutResponse{Success: false, Errors: []*gqlModel.AuthError{{Code: "UNAUTHORIZED", Message: "Token is required"}}}, nil
	}

	claims, err := r.SecurityService.ValidateJWT(input.Token)
	if err != nil {
		return &gqlModel.LogoutResponse{Success: false, Errors: []*gqlModel.AuthError{{Code: "UNAUTHORIZED", Message: "Invalid token"}}}, nil
	}

	err = r.AuthenticationService.Logout(ctx, claims.UserID, input.Token)
	if err != nil {
		return convertLogoutErrorToGraphQL(err), nil
	}
	return &gqlModel.LogoutResponse{Success: true}, nil
}

// ResetPassword is the resolver for the resetPassword field.
func (r *mutationResolver) ResetPassword(ctx context.Context, input gqlModel.PasswordResetInput) (*gqlModel.PasswordResetResponse, error) {
	err := r.AuthenticationService.ResetPassword(ctx, input.Email)
	if err != nil {
		return convertPasswordResetErrorToGraphQL(err), nil
	}
	return &gqlModel.PasswordResetResponse{Success: true}, nil
}

// ConfirmPasswordReset is the resolver for the confirmPasswordReset field.
func (r *mutationResolver) ConfirmPasswordReset(ctx context.Context, input gqlModel.PasswordResetConfirmInput) (*gqlModel.PasswordResetResponse, error) {
	err := r.AuthenticationService.ConfirmPasswordReset(ctx, input.Token, input.NewPassword)
	if err != nil {
		return convertPasswordResetErrorToGraphQL(err), nil
	}
	return &gqlModel.PasswordResetResponse{Success: true}, nil
}

// VerifyEmail is the resolver for the verifyEmail field.
func (r *mutationResolver) VerifyEmail(ctx context.Context, input gqlModel.EmailVerificationInput) (*gqlModel.EmailVerificationResponse, error) {
	err := r.AuthenticationService.VerifyEmail(ctx, input.Token)
	if err != nil {
		return convertEmailVerificationErrorToGraphQL(err), nil
	}
	return &gqlModel.EmailVerificationResponse{Success: true}, nil
}

// ResendVerification is the resolver for the resendVerification field.
func (r *mutationResolver) ResendVerification(ctx context.Context, input gqlModel.ResendVerificationInput) (*gqlModel.EmailVerificationResponse, error) {
	err := r.AuthenticationService.ResendVerification(ctx, input.Email)
	if err != nil {
		return convertEmailVerificationErrorToGraphQL(err), nil
	}
	return &gqlModel.EmailVerificationResponse{Success: true}, nil
}

// RefreshToken is the resolver for the refreshToken field.
func (r *mutationResolver) RefreshToken(ctx context.Context, input gqlModel.RefreshTokenInput) (*gqlModel.AuthResponse, error) {
	resp, err := r.AuthenticationService.RefreshToken(ctx, input.RefreshToken)
	if err != nil {
		return convertAuthErrorToGraphQL(err), nil
	}
	return mapAuthResponseToGQL(resp), nil
}

// Me is the resolver for the me field.
func (r *queryResolver) Me(ctx context.Context) (*gqlModel.AuthUser, error) {
	authUser, ok := ctx.Value(middleware.UserKey).(*middleware.AuthenticatedUser)
	if !ok || authUser == nil {
		return nil, nil // GraphQL convention for not authenticated
	}

	user, err := r.UserService.GetByID(ctx, authUser.ID)
	if err != nil {
		return nil, nil
	}

	return &gqlModel.AuthUser{
		ID:            user.ID,
		Email:         user.Email,
		Name:          user.Name,
		EmailVerified: user.EmailVerified,
	}, nil
}
