package graphql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.89

import (
	"context"
	"fmt"
	gqlModel "sigma_finance/internal/handler/graphql/model"
)

// ImportInstrumentFromCatalog is the resolver for the importInstrumentFromCatalog field.
func (r *mutationResolver) ImportInstrumentFromCatalog(ctx context.Context, source gqlModel.CatalogSource, externalID string, forceEnrich *bool) (*gqlModel.ImportInstrumentFromSourcePayload, error) {
	adminUser, authErr := requireCatalogAdmin(ctx, r.Resolver)
	if authErr != nil {
		return nil, authErr
	}

	userID := adminUser.ID
	var userPtr *string
	if userID != "" {
		userPtr = &userID
	}

	shouldEnrich := false
	if forceEnrich != nil {
		shouldEnrich = *forceEnrich
	}

	details, err := r.InstrumentService.ImportInstrumentFromCatalog(ctx, string(source), externalID, shouldEnrich, userPtr)
	if err != nil {
		return &gqlModel.ImportInstrumentFromSourcePayload{
			Success: false,
			Message: err.Error(),
		}, nil
	}

	return &gqlModel.ImportInstrumentFromSourcePayload{
		Success:    true,
		Message:    "Instrument imported from catalog",
		Instrument: mapInstrumentDetailsToGraphQL(details),
	}, nil
}

// ImportInstrumentFromSource is the resolver for the importInstrumentFromSource field.
func (r *mutationResolver) ImportInstrumentFromSource(ctx context.Context, input gqlModel.ImportInstrumentFromSourceInput) (*gqlModel.ImportInstrumentFromSourcePayload, error) {
	return r.ImportInstrumentFromCatalog(ctx, input.Source, input.ExternalID, input.ForceEnrich)
}

// CatalogSyncStatus is the resolver for the catalogSyncStatus field.
func (r *queryResolver) CatalogSyncStatus(ctx context.Context, source gqlModel.CatalogSource) (*gqlModel.CatalogSyncRun, error) {
	if _, authErr := requireCatalogAdmin(ctx, r.Resolver); authErr != nil {
		return nil, authErr
	}

	if r.InstrumentService == nil {
		return nil, fmt.Errorf("instrument service not configured")
	}

	run, err := r.InstrumentService.GetCatalogSyncStatus(ctx, string(source))
	if err != nil {
		return nil, nil
	}

	return mapCatalogSyncRun(run), nil
}
