package graphql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.89

import (
	"context"
	"fmt"
	gqlModel "sigma_finance/internal/handler/graphql/model"
)

// TriggerFinanceDatabaseSync is the resolver for the triggerFinanceDatabaseSync field.
func (r *mutationResolver) TriggerFinanceDatabaseSync(ctx context.Context, assetType gqlModel.AssetSyncType) (*gqlModel.TriggerFinanceDatabaseSyncPayload, error) {
	if r.InstrumentService == nil {
		return nil, fmt.Errorf("instrument service not configured")
	}
	status, err := r.InstrumentService.TriggerFinanceDatabaseSync(ctx, string(assetType))
	if err != nil {
		return nil, err
	}
	return &gqlModel.TriggerFinanceDatabaseSyncPayload{
		Success:    true,
		Message:    "Finance database sync completed",
		SyncStatus: mapFinanceDatabaseSyncItem(status),
	}, nil
}

// UpdateFinanceDatabaseSyncEnabled is the resolver for the updateFinanceDatabaseSyncEnabled field.
func (r *mutationResolver) UpdateFinanceDatabaseSyncEnabled(ctx context.Context, assetType gqlModel.AssetSyncType, enabled bool) (*gqlModel.FinanceDatabaseSyncItem, error) {
	if r.InstrumentService == nil {
		return nil, fmt.Errorf("instrument service not configured")
	}
	item, err := r.InstrumentService.UpdateFinanceDatabaseSyncEnabled(ctx, string(assetType), enabled)
	if err != nil {
		return nil, err
	}
	return mapFinanceDatabaseSyncItem(item), nil
}

// ImportFinanceDatabaseAssets is the resolver for the importFinanceDatabaseAssets field.
func (r *mutationResolver) ImportFinanceDatabaseAssets(ctx context.Context, assetType gqlModel.AssetSyncType, symbols []string) (*gqlModel.ImportFinanceDatabaseAssetsPayload, error) {
	if r.InstrumentService == nil {
		return nil, fmt.Errorf("instrument service not configured")
	}
	result, err := r.InstrumentService.ImportFinanceDatabaseAssets(ctx, string(assetType), symbols)
	if err != nil {
		return nil, err
	}
	errorsList := result.Errors
	if errorsList == nil {
		errorsList = []string{}
	}
	return &gqlModel.ImportFinanceDatabaseAssetsPayload{
		Success:       result.Success,
		ImportedCount: int32(result.ImportedCount),
		Errors:        errorsList,
	}, nil
}

// FinanceDatabaseSyncStatus is the resolver for the financeDatabaseSyncStatus field.
func (r *queryResolver) FinanceDatabaseSyncStatus(ctx context.Context) (*gqlModel.FinanceDatabaseSyncStatusPayload, error) {
	if r.InstrumentService == nil {
		return nil, fmt.Errorf("instrument service not configured")
	}
	payload, err := r.InstrumentService.GetFinanceDatabaseSyncStatus(ctx)
	if err != nil {
		return nil, err
	}
	return mapFinanceDatabaseSyncStatusPayload(payload), nil
}

// FinanceDatabaseSyncHistory is the resolver for the financeDatabaseSyncHistory field.
func (r *queryResolver) FinanceDatabaseSyncHistory(ctx context.Context, limit *int32) ([]*gqlModel.FinanceDatabaseSyncHistoryEntry, error) {
	if r.InstrumentService == nil {
		return nil, fmt.Errorf("instrument service not configured")
	}
	history, err := r.InstrumentService.GetFinanceDatabaseSyncHistory(ctx, intOrDefault(limit, 50))
	if err != nil {
		return nil, err
	}
	result := make([]*gqlModel.FinanceDatabaseSyncHistoryEntry, 0, len(history))
	for _, entry := range history {
		entryCopy := entry
		result = append(result, mapFinanceDatabaseSyncHistoryEntry(&entryCopy))
	}
	return result, nil
}

// FinanceDatabasePreview is the resolver for the financeDatabasePreview field.
func (r *queryResolver) FinanceDatabasePreview(ctx context.Context, assetType gqlModel.AssetSyncType, search *string, limit *int32) ([]*gqlModel.FinanceDatabasePreviewItem, error) {
	if r.InstrumentService == nil {
		return nil, fmt.Errorf("instrument service not configured")
	}
	items, err := r.InstrumentService.GetFinanceDatabasePreview(ctx, string(assetType), stringOrEmpty(search), intOrDefault(limit, 20))
	if err != nil {
		return nil, err
	}
	result := make([]*gqlModel.FinanceDatabasePreviewItem, 0, len(items))
	for _, item := range items {
		itemCopy := item
		result = append(result, mapFinanceDatabasePreviewItem(&itemCopy))
	}
	return result, nil
}
