package graphql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.89

import (
	"context"
	"errors"
	"fmt"
	"log"
	"sigma_finance/internal/domain/catalog"
	"sigma_finance/internal/domain/model"
	gqlModel "sigma_finance/internal/handler/graphql/model"
	"sigma_finance/internal/repository"
	"sigma_finance/internal/service"
	"strings"
)

func mapHistoricalBackfillJobToGraphQL(job *model.HistoricalDataBackfillJob) *gqlModel.HistoricalDataBackfillJob {
	if job == nil {
		return nil
	}
	return &gqlModel.HistoricalDataBackfillJob{
		ID:            job.ID,
		UserID:        job.UserID,
		PortfolioID:   job.PortfolioID,
		AssetID:       job.AssetID,
		InstrumentID:  job.InstrumentID,
		Provider:      job.Provider,
		Status:        job.Status,
		Step:          job.Step,
		Progress:      int32(job.Progress),
		RowsWritten:   int32(job.RowsWritten),
		ErrorCode:     job.ErrorCode,
		ErrorMessage:  job.ErrorMessage,
		RequestedFrom: job.RequestedFrom,
		RequestedTo:   job.RequestedTo,
		CreatedAt:     job.CreatedAt,
		StartedAt:     job.StartedAt,
		FinishedAt:    job.FinishedAt,
	}
}

// safeUserIDFromContext returns the user ID from context, logging a warning on failure.
func safeUserIDFromContext(ctx context.Context) string {
	userID, err := getUserIDFromContext(ctx)
	if err != nil {
		log.Printf("[ERROR] [instrument] getUserIDFromContext failed: %v", err)
	}
	return userID
}

// PersistDiscoveredInstrument is the resolver for the persistDiscoveredInstrument field.
func (r *mutationResolver) PersistDiscoveredInstrument(ctx context.Context, input gqlModel.PersistDiscoveredInstrumentInput) (*gqlModel.Instrument, error) {
	log.Printf("[INFO] [graphql] PersistDiscoveredInstrument: started")
	userID := safeUserIDFromContext(ctx)
	var userPtr *string
	if userID != "" {
		userPtr = &userID
	}

	payload := service.PersistDiscoveredInstrumentInput{
		Instrument: catalog.DiscoveryInstrument{
			Symbol:             input.Instrument.Symbol,
			Name:               input.Instrument.Name,
			Exchange:           input.Instrument.Exchange,
			ExchangeCode:       input.Instrument.ExchangeCode,
			Country:            input.Instrument.Country,
			Currency:           input.Instrument.Currency,
			AssetType:          mapGQLInstrumentAssetTypeToDomain(input.Instrument.AssetType),
			ProviderSource:     input.Instrument.ProviderSource,
			ProviderExternalID: input.Instrument.ProviderExternalID,
			ISIN:               input.Instrument.Isin,
			FIGI:               input.Instrument.Figi,
			CUSIP:              input.Instrument.Cusip,
		},
	}

	details, err := r.InstrumentService.PersistDiscoveredInstrument(ctx, payload, userPtr)
	if err != nil {
		return nil, err
	}
	return mapInstrumentDetailsToGraphQL(details), nil
}

// AddInstrumentToPortfolio is the resolver for the addInstrumentToPortfolio field.
func (r *mutationResolver) AddInstrumentToPortfolio(ctx context.Context, input gqlModel.AddInstrumentHoldingInput) (*gqlModel.PortfolioAsset, error) {
	userID := safeUserIDFromContext(ctx)
	var userPtr *string
	if userID != "" {
		userPtr = &userID
	}

	unitPriceCurrency := ""
	if input.UnitPriceCurrency != nil {
		unitPriceCurrency = *input.UnitPriceCurrency
	}
	holding, err := r.InstrumentService.AddInstrumentToPortfolio(ctx, input.PortfolioID, input.InstrumentID, input.Quantity, input.AveragePurchasePrice, unitPriceCurrency, input.PurchaseDate, userPtr)
	if err != nil {
		return nil, err
	}
	gqlAsset, gqlErr := r.getAssetWithDetails(ctx, holding.AssetID)
	if gqlErr != nil {
		log.Printf("[ERROR] [AddInstrumentToPortfolio] getAssetWithDetails failed for asset %s: %v", holding.AssetID, gqlErr)
	}
	return mapPortfolioAssetToGQLWithAssetAndInstrument(*holding, gqlAsset, holding.InstrumentID), nil
}

// UpdateManualInstrument is the resolver for the updateManualInstrument field.
func (r *mutationResolver) UpdateManualInstrument(ctx context.Context, id string, input gqlModel.UpdateManualInstrumentInput) (*gqlModel.Instrument, error) {
	log.Printf("[INFO] [graphql] AddInstrumentToPortfolio: started")
	userID := safeUserIDFromContext(ctx)
	var userPtr *string
	if userID != "" {
		userPtr = &userID
	}

	details, err := r.InstrumentService.UpdateManualInstrument(ctx, id, service.UpdateManualInstrumentInput{
		Symbol:           input.Symbol,
		Name:             input.Name,
		Exchange:         input.Exchange,
		ExchangeCode:     input.ExchangeCode,
		Country:          input.Country,
		Currency:         input.Currency,
		BaseCurrency:     input.BaseCurrency,
		QuoteCurrency:    input.QuoteCurrency,
		UnderlyingSymbol: input.UnderlyingSymbol,
		AssetType:        mapGQLInstrumentAssetTypeToDomain(input.AssetType),
		Summary:          input.Summary,
		Sector:           input.Sector,
		IndustryGroup:    input.IndustryGroup,
		Industry:         input.Industry,
		CategoryGroup:    input.CategoryGroup,
		Category:         input.Category,
		Family:           input.Family,
		Website:          input.Website,
		MarketCap:        input.MarketCap,
		State:            input.State,
		City:             input.City,
		Zipcode:          input.Zipcode,
	}, userPtr)
	if err != nil {
		return nil, err
	}
	return mapInstrumentDetailsToGraphQL(details), nil
}

// ArchiveManualInstrument is the resolver for the archiveManualInstrument field.
func (r *mutationResolver) ArchiveManualInstrument(ctx context.Context, id string) (*gqlModel.Instrument, error) {
	log.Printf("[INFO] [graphql] ArchiveManualInstrument: started")
	userID := safeUserIDFromContext(ctx)
	var userPtr *string
	if userID != "" {
		userPtr = &userID
	}

	details, err := r.InstrumentService.ArchiveManualInstrument(ctx, id, userPtr)
	if err != nil {
		return nil, err
	}
	return mapInstrumentDetailsToGraphQL(details), nil
}

// RestoreManualInstrument is the resolver for the restoreManualInstrument field.
func (r *mutationResolver) RestoreManualInstrument(ctx context.Context, id string) (*gqlModel.Instrument, error) {
	log.Printf("[INFO] [graphql] RestoreManualInstrument: started")
	userID := safeUserIDFromContext(ctx)
	var userPtr *string
	if userID != "" {
		userPtr = &userID
	}

	details, err := r.InstrumentService.RestoreManualInstrument(ctx, id, userPtr)
	if err != nil {
		return nil, err
	}
	return mapInstrumentDetailsToGraphQL(details), nil
}

// RetryHistoricalDataBackfillJob is the resolver for the retryHistoricalDataBackfillJob field.
func (r *mutationResolver) RetryHistoricalDataBackfillJob(ctx context.Context, id string) (*gqlModel.HistoricalDataBackfillJob, error) {
	log.Printf("[INFO] [graphql] RetryHistoricalDataBackfillJob: started")
	userID := safeUserIDFromContext(ctx)
	var userPtr *string
	if userID != "" {
		userPtr = &userID
	}
	includeAll := false
	if _, adminErr := requireCatalogAdmin(ctx, r.Resolver); adminErr == nil {
		includeAll = true
	}
	job, err := r.InstrumentService.RetryHistoricalDataBackfillJob(ctx, id, userPtr, includeAll)
	if err != nil {
		return nil, err
	}
	return mapHistoricalBackfillJobToGraphQL(job), nil
}

// Instrument is the resolver for the instrument field.
func (r *queryResolver) Instrument(ctx context.Context, id string) (*gqlModel.Instrument, error) {
	log.Printf("[INFO] [graphql] Instrument: started")
	if r.InstrumentService == nil {
		return nil, fmt.Errorf("instrument service not configured")
	}

	details, err := r.InstrumentService.GetInstrumentDetails(ctx, id)
	if err != nil {
		if errors.Is(err, repository.ErrNotFound) {
			return nil, nil
		}
		return nil, err
	}
	userID := safeUserIDFromContext(ctx)
	if details.Instrument != nil && strings.EqualFold(details.Instrument.ProviderSource, "manual") {
		if details.Instrument.OwnerUserID == nil || (userID != "" && *details.Instrument.OwnerUserID != userID) || userID == "" {
			return nil, fmt.Errorf("unauthorized: access denied to manual instrument")
		}
	}

	return mapInstrumentDetailsToGraphQL(details), nil
}

// SearchInstruments is the resolver for the searchInstruments field.
func (r *queryResolver) SearchInstruments(ctx context.Context, input gqlModel.InstrumentSearchInput) (*gqlModel.InstrumentSearchPayload, error) {
	log.Printf("[INFO] [graphql] SearchInstruments: started")
	filter := mapInstrumentSearchFilter(input)
	userID := safeUserIDFromContext(ctx)
	var userPtr *string
	if userID != "" {
		userPtr = &userID
	}
	payload, err := r.InstrumentService.SearchLocal(ctx, input.Query, filter, userPtr)
	if err != nil {
		return nil, err
	}
	return mapInstrumentSearchPayloadToGraphQL(payload), nil
}

// SearchInstrumentsOnline is the resolver for the searchInstrumentsOnline field.
func (r *queryResolver) SearchInstrumentsOnline(ctx context.Context, input gqlModel.InstrumentSearchInput) (*gqlModel.OnlineInstrumentSearchPayload, error) {
	log.Printf("[INFO] [graphql] SearchInstrumentsOnline: started")
	filter := mapInstrumentSearchFilter(input)
	userID := safeUserIDFromContext(ctx)
	var userPtr *string
	if userID != "" {
		userPtr = &userID
	}

	payload, err := r.InstrumentService.SearchOnline(ctx, input.Query, filter, userPtr)
	if err != nil {
		return nil, err
	}
	return mapOnlineSearchPayloadToGraphQL(payload), nil
}

// ManualInstruments is the resolver for the manualInstruments field.
func (r *queryResolver) ManualInstruments(ctx context.Context, filter *gqlModel.ManualInstrumentFilterInput, pagination *gqlModel.PaginationInput) (*gqlModel.ManualInstrumentPayload, error) {
	log.Printf("[INFO] [graphql] ManualInstruments: started")
	serviceFilter := service.ManualInstrumentFilter{}
	if filter != nil {
		serviceFilter.Query = ""
		if filter.Query != nil {
			serviceFilter.Query = *filter.Query
		}
		serviceFilter.IncludeArchived = filter.IncludeArchived != nil && *filter.IncludeArchived
		if len(filter.AssetTypes) > 0 {
			assetTypes := make([]model.InstrumentAssetType, 0, len(filter.AssetTypes))
			for _, assetType := range filter.AssetTypes {
				assetTypes = append(assetTypes, mapGQLInstrumentAssetTypeToDomain(assetType))
			}
			serviceFilter.AssetTypes = assetTypes
		}
	}
	if pagination != nil {
		if pagination.Limit != nil {
			serviceFilter.Limit = int(*pagination.Limit)
		}
		if pagination.Offset != nil {
			serviceFilter.Offset = int(*pagination.Offset)
		}
	}

	userID := safeUserIDFromContext(ctx)
	var userPtr *string
	if userID != "" {
		userPtr = &userID
	}

	payload, err := r.InstrumentService.ListManualInstruments(ctx, serviceFilter, userPtr)
	if err != nil {
		return nil, err
	}

	items := make([]*gqlModel.Instrument, 0, len(payload.Items))
	for i := range payload.Items {
		item := payload.Items[i]
		items = append(items, mapInstrumentDetailsToGraphQL(&item))
	}

	return &gqlModel.ManualInstrumentPayload{
		Items:   items,
		HasMore: payload.HasMore,
		Limit:   int32(payload.Limit),
		Offset:  int32(payload.Offset),
	}, nil
}

// HistoricalDataBackfillJob is the resolver for the historicalDataBackfillJob field.
func (r *queryResolver) HistoricalDataBackfillJob(ctx context.Context, id string) (*gqlModel.HistoricalDataBackfillJob, error) {
	log.Printf("[INFO] [graphql] HistoricalDataBackfillJob: started")
	userID := safeUserIDFromContext(ctx)
	var userPtr *string
	if userID != "" {
		userPtr = &userID
	}
	includeAll := false
	if _, adminErr := requireCatalogAdmin(ctx, r.Resolver); adminErr == nil {
		includeAll = true
	}
	job, err := r.InstrumentService.GetHistoricalDataBackfillJob(ctx, id, userPtr, includeAll)
	if err != nil {
		if errors.Is(err, repository.ErrNotFound) {
			return nil, nil
		}
		return nil, err
	}
	return mapHistoricalBackfillJobToGraphQL(job), nil
}

// LatestHistoricalDataBackfillJob is the resolver for the latestHistoricalDataBackfillJob field.
func (r *queryResolver) LatestHistoricalDataBackfillJob(ctx context.Context, portfolioID string, assetID string) (*gqlModel.HistoricalDataBackfillJob, error) {
	log.Printf("[INFO] [graphql] LatestHistoricalDataBackfillJob: started")
	userID := safeUserIDFromContext(ctx)
	var userPtr *string
	if userID != "" {
		userPtr = &userID
	}
	includeAll := false
	if _, adminErr := requireCatalogAdmin(ctx, r.Resolver); adminErr == nil {
		includeAll = true
	}
	job, err := r.InstrumentService.GetLatestHistoricalDataBackfillJob(ctx, portfolioID, assetID, userPtr, includeAll)
	if err != nil {
		if errors.Is(err, repository.ErrNotFound) {
			return nil, nil
		}
		return nil, err
	}
	return mapHistoricalBackfillJobToGraphQL(job), nil
}

// HistoricalDataBackfillJobs is the resolver for the historicalDataBackfillJobs field.
func (r *queryResolver) HistoricalDataBackfillJobs(ctx context.Context, filter *gqlModel.HistoricalDataBackfillJobFilterInput, pagination *gqlModel.PaginationInput) ([]*gqlModel.HistoricalDataBackfillJob, error) {
	log.Printf("[INFO] [graphql] HistoricalDataBackfillJobs: started")
	userID := safeUserIDFromContext(ctx)
	var userPtr *string
	if userID != "" {
		userPtr = &userID
	}
	includeAll := false
	if _, adminErr := requireCatalogAdmin(ctx, r.Resolver); adminErr == nil {
		includeAll = true
	}
	limit := 50
	offset := 0
	if pagination != nil {
		if pagination.Limit != nil {
			limit = int(*pagination.Limit)
		}
		if pagination.Offset != nil {
			offset = int(*pagination.Offset)
		}
	}
	repoFilter := repository.HistoricalDataBackfillJobFilter{Limit: limit, Offset: offset}
	if filter != nil {
		repoFilter.Status = filter.Status
		repoFilter.Provider = filter.Provider
	}
	rows, err := r.InstrumentService.ListHistoricalDataBackfillJobs(ctx, repoFilter, userPtr, includeAll)
	if err != nil {
		return nil, err
	}
	result := make([]*gqlModel.HistoricalDataBackfillJob, 0, len(rows))
	for i := range rows {
		result = append(result, mapHistoricalBackfillJobToGraphQL(&rows[i]))
	}
	return result, nil
}
