package graphql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.89

import (
	"context"
	"errors"
	"fmt"
	"sigma_finance/internal/domain/catalog"
	"sigma_finance/internal/domain/model"
	gqlModel "sigma_finance/internal/handler/graphql/model"
	"sigma_finance/internal/repository"
	"sigma_finance/internal/service"
	"strings"
)

// PersistDiscoveredInstrument is the resolver for the persistDiscoveredInstrument field.
func (r *mutationResolver) PersistDiscoveredInstrument(ctx context.Context, input gqlModel.PersistDiscoveredInstrumentInput) (*gqlModel.Instrument, error) {
	userID, _ := getUserIDFromContext(ctx)
	var userPtr *string
	if userID != "" {
		userPtr = &userID
	}

	payload := service.PersistDiscoveredInstrumentInput{
		Instrument: catalog.DiscoveryInstrument{
			Symbol:             input.Instrument.Symbol,
			Name:               input.Instrument.Name,
			Exchange:           input.Instrument.Exchange,
			ExchangeCode:       input.Instrument.ExchangeCode,
			Country:            input.Instrument.Country,
			Currency:           input.Instrument.Currency,
			AssetType:          mapGQLInstrumentAssetTypeToDomain(input.Instrument.AssetType),
			ProviderSource:     input.Instrument.ProviderSource,
			ProviderExternalID: input.Instrument.ProviderExternalID,
			ISIN:               input.Instrument.Isin,
			FIGI:               input.Instrument.Figi,
			CUSIP:              input.Instrument.Cusip,
		},
	}

	details, err := r.InstrumentService.PersistDiscoveredInstrument(ctx, payload, userPtr)
	if err != nil {
		return nil, err
	}
	return mapInstrumentDetailsToGraphQL(details), nil
}

// AddInstrumentToPortfolio is the resolver for the addInstrumentToPortfolio field.
func (r *mutationResolver) AddInstrumentToPortfolio(ctx context.Context, input gqlModel.AddInstrumentHoldingInput) (*gqlModel.PortfolioAsset, error) {
	userID, _ := getUserIDFromContext(ctx)
	var userPtr *string
	if userID != "" {
		userPtr = &userID
	}

	unitPriceCurrency := ""
	if input.UnitPriceCurrency != nil {
		unitPriceCurrency = *input.UnitPriceCurrency
	}
	holding, err := r.InstrumentService.AddInstrumentToPortfolio(ctx, input.PortfolioID, input.InstrumentID, input.Quantity, input.AveragePurchasePrice, unitPriceCurrency, input.PurchaseDate, userPtr)
	if err != nil {
		return nil, err
	}
	gqlAsset, _ := r.getAssetWithDetails(ctx, holding.AssetID)
	return mapPortfolioAssetToGQLWithAssetAndInstrument(*holding, gqlAsset, holding.InstrumentID), nil
}

// UpdateManualInstrument is the resolver for the updateManualInstrument field.
func (r *mutationResolver) UpdateManualInstrument(ctx context.Context, id string, input gqlModel.UpdateManualInstrumentInput) (*gqlModel.Instrument, error) {
	userID, _ := getUserIDFromContext(ctx)
	var userPtr *string
	if userID != "" {
		userPtr = &userID
	}

	details, err := r.InstrumentService.UpdateManualInstrument(ctx, id, service.UpdateManualInstrumentInput{
		Symbol:           input.Symbol,
		Name:             input.Name,
		Exchange:         input.Exchange,
		ExchangeCode:     input.ExchangeCode,
		Country:          input.Country,
		Currency:         input.Currency,
		BaseCurrency:     input.BaseCurrency,
		QuoteCurrency:    input.QuoteCurrency,
		UnderlyingSymbol: input.UnderlyingSymbol,
		AssetType:        mapGQLInstrumentAssetTypeToDomain(input.AssetType),
		Summary:          input.Summary,
		Sector:           input.Sector,
		IndustryGroup:    input.IndustryGroup,
		Industry:         input.Industry,
		CategoryGroup:    input.CategoryGroup,
		Category:         input.Category,
		Family:           input.Family,
		Website:          input.Website,
		MarketCap:        input.MarketCap,
		State:            input.State,
		City:             input.City,
		Zipcode:          input.Zipcode,
	}, userPtr)
	if err != nil {
		return nil, err
	}
	return mapInstrumentDetailsToGraphQL(details), nil
}

// ArchiveManualInstrument is the resolver for the archiveManualInstrument field.
func (r *mutationResolver) ArchiveManualInstrument(ctx context.Context, id string) (*gqlModel.Instrument, error) {
	userID, _ := getUserIDFromContext(ctx)
	var userPtr *string
	if userID != "" {
		userPtr = &userID
	}

	details, err := r.InstrumentService.ArchiveManualInstrument(ctx, id, userPtr)
	if err != nil {
		return nil, err
	}
	return mapInstrumentDetailsToGraphQL(details), nil
}

// RestoreManualInstrument is the resolver for the restoreManualInstrument field.
func (r *mutationResolver) RestoreManualInstrument(ctx context.Context, id string) (*gqlModel.Instrument, error) {
	userID, _ := getUserIDFromContext(ctx)
	var userPtr *string
	if userID != "" {
		userPtr = &userID
	}

	details, err := r.InstrumentService.RestoreManualInstrument(ctx, id, userPtr)
	if err != nil {
		return nil, err
	}
	return mapInstrumentDetailsToGraphQL(details), nil
}

// Instrument is the resolver for the instrument field.
func (r *queryResolver) Instrument(ctx context.Context, id string) (*gqlModel.Instrument, error) {
	if r.InstrumentService == nil {
		return nil, fmt.Errorf("instrument service not configured")
	}

	details, err := r.InstrumentService.GetInstrumentDetails(ctx, id)
	if err != nil {
		if errors.Is(err, repository.ErrNotFound) {
			return nil, nil
		}
		return nil, err
	}
	userID, _ := getUserIDFromContext(ctx)
	if details.Instrument != nil && strings.EqualFold(details.Instrument.ProviderSource, "manual") {
		if details.Instrument.OwnerUserID == nil || (userID != "" && *details.Instrument.OwnerUserID != userID) || userID == "" {
			return nil, fmt.Errorf("unauthorized: access denied to manual instrument")
		}
	}

	return mapInstrumentDetailsToGraphQL(details), nil
}

// SearchInstruments is the resolver for the searchInstruments field.
func (r *queryResolver) SearchInstruments(ctx context.Context, input gqlModel.InstrumentSearchInput) (*gqlModel.InstrumentSearchPayload, error) {
	filter := mapInstrumentSearchFilter(input)
	userID, _ := getUserIDFromContext(ctx)
	var userPtr *string
	if userID != "" {
		userPtr = &userID
	}
	payload, err := r.InstrumentService.SearchLocal(ctx, input.Query, filter, userPtr)
	if err != nil {
		return nil, err
	}
	return mapInstrumentSearchPayloadToGraphQL(payload), nil
}

// SearchInstrumentsOnline is the resolver for the searchInstrumentsOnline field.
func (r *queryResolver) SearchInstrumentsOnline(ctx context.Context, input gqlModel.InstrumentSearchInput) (*gqlModel.OnlineInstrumentSearchPayload, error) {
	filter := mapInstrumentSearchFilter(input)
	userID, _ := getUserIDFromContext(ctx)
	var userPtr *string
	if userID != "" {
		userPtr = &userID
	}

	payload, err := r.InstrumentService.SearchOnline(ctx, input.Query, filter, userPtr)
	if err != nil {
		return nil, err
	}
	return mapOnlineSearchPayloadToGraphQL(payload), nil
}

// ManualInstruments is the resolver for the manualInstruments field.
func (r *queryResolver) ManualInstruments(ctx context.Context, filter *gqlModel.ManualInstrumentFilterInput, pagination *gqlModel.PaginationInput) (*gqlModel.ManualInstrumentPayload, error) {
	serviceFilter := service.ManualInstrumentFilter{}
	if filter != nil {
		serviceFilter.Query = ""
		if filter.Query != nil {
			serviceFilter.Query = *filter.Query
		}
		serviceFilter.IncludeArchived = filter.IncludeArchived != nil && *filter.IncludeArchived
		if len(filter.AssetTypes) > 0 {
			assetTypes := make([]model.InstrumentAssetType, 0, len(filter.AssetTypes))
			for _, assetType := range filter.AssetTypes {
				assetTypes = append(assetTypes, mapGQLInstrumentAssetTypeToDomain(assetType))
			}
			serviceFilter.AssetTypes = assetTypes
		}
	}
	if pagination != nil {
		if pagination.Limit != nil {
			serviceFilter.Limit = int(*pagination.Limit)
		}
		if pagination.Offset != nil {
			serviceFilter.Offset = int(*pagination.Offset)
		}
	}

	userID, _ := getUserIDFromContext(ctx)
	var userPtr *string
	if userID != "" {
		userPtr = &userID
	}

	payload, err := r.InstrumentService.ListManualInstruments(ctx, serviceFilter, userPtr)
	if err != nil {
		return nil, err
	}

	items := make([]*gqlModel.Instrument, 0, len(payload.Items))
	for i := range payload.Items {
		item := payload.Items[i]
		items = append(items, mapInstrumentDetailsToGraphQL(&item))
	}

	return &gqlModel.ManualInstrumentPayload{
		Items:   items,
		HasMore: payload.HasMore,
		Limit:   int32(payload.Limit),
		Offset:  int32(payload.Offset),
	}, nil
}
