package graphql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.89

import (
	"context"
	"fmt"
	"sigma_finance/internal/domain/model"
	gqlModel "sigma_finance/internal/handler/graphql/model"
	"sigma_finance/internal/handler/middleware"
	"sigma_finance/internal/repository"
	"time"

	"github.com/google/uuid"
)

// UpsertMarketDataCredential is the resolver for the upsertMarketDataCredential field.
func (r *mutationResolver) UpsertMarketDataCredential(ctx context.Context, provider string, apiKey string) (*gqlModel.MarketDataCredential, error) {
	user, err := middleware.RequireAuth(ctx)
	if err != nil {
		return nil, err
	}
	uid := user.ID
	repo := r.Resolver.UOW.MarketDataCredential()
	existing, _ := repo.GetByUserAndProvider(ctx, uid, provider)
	now := time.Now()
	storedKey := apiKey
	if r.Resolver.SecurityService != nil {
		if enc, e := r.Resolver.SecurityService.EncryptString(apiKey); e == nil {
			storedKey = enc
		}
	}
	if existing != nil {
		existing.APIKey = storedKey
		existing.UpdatedAt = now
		if err := repo.Update(ctx, existing); err != nil {
			return nil, err
		}
		return &gqlModel.MarketDataCredential{ID: existing.ID, Provider: existing.Provider, CreatedAt: existing.CreatedAt, UpdatedAt: existing.UpdatedAt}, nil
	}
	cred := &model.MarketDataCredential{UserID: uid, Provider: provider, APIKey: storedKey, CreatedAt: now, UpdatedAt: now}
	created, err := repo.Create(ctx, cred)
	if err != nil {
		return nil, err
	}
	return &gqlModel.MarketDataCredential{ID: created.ID, Provider: created.Provider, CreatedAt: created.CreatedAt, UpdatedAt: created.UpdatedAt}, nil
}

// DeleteMarketDataCredential is the resolver for the deleteMarketDataCredential field.
func (r *mutationResolver) DeleteMarketDataCredential(ctx context.Context, provider string) (string, error) {
	user, err := middleware.RequireAuth(ctx)
	if err != nil {
		return "", err
	}
	uid := user.ID
	repo := r.Resolver.UOW.MarketDataCredential()
	existing, err := repo.GetByUserAndProvider(ctx, uid, provider)
	if err != nil {
		return "", err
	}
	if err := repo.Delete(ctx, existing.ID); err != nil {
		return "", err
	}
	return provider, nil
}

// ValidateProviderCredentials is the resolver for the validateProviderCredentials field.
func (r *mutationResolver) ValidateProviderCredentials(ctx context.Context, provider string, apiKey string) (*gqlModel.ValidationResult, error) {
	if apiKey == "" {
		return &gqlModel.ValidationResult{Valid: false, Message: stringPtr("API key is required")}, nil
	}

	err := r.Resolver.MarketDataService.ValidateProviderCredentials(ctx, "", provider, apiKey)
	if err != nil {
		return &gqlModel.ValidationResult{Valid: false, Message: stringPtr(err.Error())}, nil
	}

	return &gqlModel.ValidationResult{Valid: true, Message: stringPtr("API key is valid")}, nil
}

// RefreshAssetPrices is the resolver for the refreshAssetPrices field.
func (r *mutationResolver) RefreshAssetPrices(ctx context.Context, assetID *string) (*gqlModel.RefreshAssetPricesResult, error) {
	_, err := middleware.RequireAuth(ctx)
	if err != nil {
		return &gqlModel.RefreshAssetPricesResult{Success: false, Message: stringPtr("authentication required")}, nil
	}

	if assetID != nil && *assetID != "" {
		uid, err := uuid.Parse(*assetID)
		if err != nil {
			return &gqlModel.RefreshAssetPricesResult{Success: false, Message: stringPtr("invalid asset ID format")}, nil
		}
		_, err = r.Resolver.MarketDataService.UpdateAssetPrice(ctx, uid)
		if err != nil {
			zero := int32(0)
			return &gqlModel.RefreshAssetPricesResult{
				Success:      false,
				Message:      stringPtr(err.Error()),
				UpdatedCount: &zero,
			}, nil
		}
		one := int32(1)
		return &gqlModel.RefreshAssetPricesResult{
			Success:      true,
			Message:      stringPtr("price updated successfully"),
			UpdatedCount: &one,
		}, nil
	}

	err = r.Resolver.MarketDataService.UpdateAssetPrices(ctx)
	if err != nil {
		return &gqlModel.RefreshAssetPricesResult{
			Success: false,
			Message: stringPtr(err.Error()),
		}, nil
	}

	zero := int32(0)
	return &gqlModel.RefreshAssetPricesResult{
		Success:      true,
		Message:      stringPtr("all prices updated"),
		UpdatedCount: &zero,
	}, nil
}

// RefreshSingleAssetPrice is the resolver for the refreshSingleAssetPrice field.
func (r *mutationResolver) RefreshSingleAssetPrice(ctx context.Context, assetID string) (*gqlModel.AssetPricePoint, error) {
	_, err := middleware.RequireAuth(ctx)
	if err != nil {
		return nil, err
	}

	uid, err := uuid.Parse(assetID)
	if err != nil {
		return nil, fmt.Errorf("invalid asset ID format: %w", err)
	}

	priceData, err := r.Resolver.MarketDataService.UpdateAssetPrice(ctx, uid)
	if err != nil {
		return nil, fmt.Errorf("failed to refresh price: %w", err)
	}

	return &gqlModel.AssetPricePoint{
		ID:        assetID,
		AssetID:   priceData.AssetID.String(),
		Price:     priceData.Price.InexactFloat64(),
		Timestamp: priceData.Timestamp,
		Source:    priceData.Source,
	}, nil
}

// UpdateProviderRoutingPreferences is the resolver for the updateProviderRoutingPreferences field.
func (r *mutationResolver) UpdateProviderRoutingPreferences(ctx context.Context, input gqlModel.ProviderRoutingPreferencesInput) (*gqlModel.ProviderRoutingPreferences, error) {
	user, err := middleware.RequireAuth(ctx)
	if err != nil {
		return nil, err
	}

	now := time.Now()

	useIntelligentRouting := true
	if input.UseIntelligentRouting != nil {
		useIntelligentRouting = *input.UseIntelligentRouting
	}

	enableFallback := true
	if input.EnableFallback != nil {
		enableFallback = *input.EnableFallback
	}

	staleThreshold := int32(30)
	if input.StaleDataThresholdMinutes != nil {
		staleThreshold = *input.StaleDataThresholdMinutes
	}

	preferredProviders := make([]*gqlModel.ProviderPreference, len(input.PreferredProviders))
	for i, p := range input.PreferredProviders {
		preferredProviders[i] = &gqlModel.ProviderPreference{
			Provider: p.Provider,
			Priority: p.Priority,
			Enabled:  p.Enabled,
		}
	}

	return &gqlModel.ProviderRoutingPreferences{
		ID:                        fmt.Sprintf("pref_%s", user.ID[:8]),
		UserID:                    user.ID,
		PreferredProviders:        preferredProviders,
		UseIntelligentRouting:     useIntelligentRouting,
		EnableFallback:            enableFallback,
		StaleDataThresholdMinutes: staleThreshold,
		CreatedAt:                 now,
		UpdatedAt:                 now,
	}, nil
}

// Candles resolver
func (r *queryResolver) Candles(ctx context.Context, symbol string, assetType string, interval string, from time.Time, to time.Time, limit *int32) ([]*gqlModel.Candle, error) {
	lim := 500
	if limit != nil {
		lim = int(*limit)
	}
	user, _ := middleware.GetUserFromContext(ctx)
	uid := ""
	if user != nil {
		uid = user.ID
	}
	candles, err := r.Resolver.MarketDataService.GetCandles(ctx, uid, symbol, assetType, model.CandleInterval(interval), from, to, lim)
	if err != nil {
		return nil, err
	}
	out := make([]*gqlModel.Candle, 0, len(candles))
	for _, c := range candles {
		out = append(out, &gqlModel.Candle{Symbol: c.Symbol, AssetType: c.AssetType, Interval: string(c.Interval), Open: c.Open.ToFloat(), High: c.High.ToFloat(), Low: c.Low.ToFloat(), Close: c.Close.ToFloat(), Volume: &c.Volume, Timestamp: c.Timestamp, Source: c.Source})
	}
	return out, nil
}

// MarketDataCredentials resolver
func (r *queryResolver) MarketDataCredentials(ctx context.Context) ([]*gqlModel.MarketDataCredential, error) {
	user, err := middleware.RequireAuth(ctx)
	if err != nil {
		return nil, err
	}
	uid := user.ID
	creds, err := r.Resolver.UOW.MarketDataCredential().ListByUser(ctx, uid)
	if err != nil {
		return nil, err
	}
	out := make([]*gqlModel.MarketDataCredential, 0, len(creds))
	for _, c := range creds {
		out = append(out, &gqlModel.MarketDataCredential{ID: c.ID, Provider: c.Provider, CreatedAt: c.CreatedAt, UpdatedAt: c.UpdatedAt})
	}
	return out, nil
}

// SupportedProviders resolver
func (r *queryResolver) SupportedProviders(ctx context.Context, assetType *string) ([]*gqlModel.ProviderInfo, error) {
	_, err := middleware.RequireAuth(ctx)
	if err != nil {
		return nil, err
	}

	at := ""
	if assetType != nil {
		at = *assetType
	}

	providers := r.Resolver.MarketDataService.GetSupportedProviders(at)
	out := make([]*gqlModel.ProviderInfo, 0, len(providers))

	for _, p := range providers {
		rateLimit := &gqlModel.RateLimit{
			RequestsPerMinute: int32(p.RateLimit.RequestsPerMinute),
			RequestsPerDay:    int32(p.RateLimit.RequestsPerDay),
			BurstLimit:        int32(p.RateLimit.BurstLimit),
		}

		out = append(out, &gqlModel.ProviderInfo{
			ID:               p.ID,
			Name:             p.Name,
			Type:             p.Type,
			RequiresKey:      p.RequiresKey,
			Intervals:        p.Intervals,
			RateLimit:        rateLimit,
			SupportsRealtime: p.SupportsRT,
		})
	}

	return out, nil
}

// ProviderHealth resolver
func (r *queryResolver) ProviderHealth(ctx context.Context) ([]*gqlModel.ProviderHealth, error) {
	user, err := middleware.RequireAuth(ctx)
	if err != nil {
		return nil, err
	}

	healthEntries := r.Resolver.MarketDataService.GetProviderHealth(ctx)

	creds, err := r.Resolver.UOW.MarketDataCredential().ListByUser(ctx, user.ID)
	if err != nil {
		creds = nil
	}

	credMap := make(map[string]string)
	for _, cred := range creds {
		apiKey := cred.APIKey
		if r.Resolver.SecurityService != nil && apiKey != "" {
			if decrypted, err := r.Resolver.SecurityService.DecryptString(apiKey); err == nil {
				apiKey = decrypted
			}
		}
		credMap[cred.Provider] = apiKey
	}

	// Build a map of which providers require API keys (using all providers,
	// no need to iterate per asset type since RequiresKey is provider-level).
	providerRequiresKey := make(map[string]bool)
	for _, p := range r.Resolver.MarketDataService.GetSupportedProviders("") {
		providerRequiresKey[p.ID] = p.RequiresKey
	}

	// Validate API keys once per provider (not per asset type) to avoid
	// redundant validation calls when a provider supports multiple types.
	apiKeyValidMap := make(map[string]bool)
	for providerID, apiKey := range credMap {
		if providerRequiresKey[providerID] && apiKey != "" {
			apiKeyValidMap[providerID] = r.Resolver.MarketDataService.ValidateProviderCredentials(ctx, user.ID, providerID, apiKey) == nil
		}
	}

	out := make([]*gqlModel.ProviderHealth, 0, len(healthEntries))
	now := time.Now()
	for _, entry := range healthEntries {
		ph := &gqlModel.ProviderHealth{
			Provider:    entry.Provider,
			AssetType:   entry.AssetType,
			Healthy:     entry.Healthy,
			LastChecked: now,
		}

		if valid, exists := apiKeyValidMap[entry.Provider]; exists {
			ph.APIKeyValid = &valid
		}

		out = append(out, ph)
	}

	return out, nil
}

// RealTimePrice resolver
func (r *queryResolver) RealTimePrice(ctx context.Context, symbol string, assetType string) (*gqlModel.Candle, error) {
	user, _ := middleware.GetUserFromContext(ctx)
	uid := ""
	if user != nil {
		uid = user.ID
	}

	candle, err := r.Resolver.MarketDataService.GetRealTimePrice(ctx, uid, symbol, assetType)
	if err != nil {
		return nil, err
	}

	return &gqlModel.Candle{
		Symbol:    candle.Symbol,
		AssetType: candle.AssetType,
		Interval:  string(candle.Interval),
		Open:      candle.Open.ToFloat(),
		High:      candle.High.ToFloat(),
		Low:       candle.Low.ToFloat(),
		Close:     candle.Close.ToFloat(),
		Volume:    &candle.Volume,
		Timestamp: candle.Timestamp,
		Source:    candle.Source,
	}, nil
}

// AssetPriceHistory is the resolver for the assetPriceHistory field.
func (r *queryResolver) AssetPriceHistory(ctx context.Context, assetID string, from time.Time, to time.Time, limit *int32) ([]*gqlModel.AssetPricePoint, error) {
	_, err := middleware.RequireAuth(ctx)
	if err != nil {
		return nil, err
	}

	timeRange := repository.TimeRange{
		Start: from,
		End:   to,
	}

	prices, err := r.Resolver.UOW.AssetPrice().GetPriceHistory(ctx, assetID, timeRange)
	if err != nil {
		return nil, fmt.Errorf("failed to get price history: %w", err)
	}

	result := make([]*gqlModel.AssetPricePoint, 0, len(prices))
	for _, p := range prices {
		point := &gqlModel.AssetPricePoint{
			ID:        fmt.Sprintf("%d", p.ID),
			AssetID:   p.AssetID,
			Price:     p.Price.InexactFloat64(),
			Timestamp: p.Timestamp,
			Source:    p.Source,
		}
		if p.Volume != nil {
			volume := float64(*p.Volume)
			point.Volume = &volume
		}
		if p.MarketCap != nil {
			marketCap := float64(*p.MarketCap)
			point.MarketCap = &marketCap
		}
		result = append(result, point)
	}

	if limit != nil && len(result) > int(*limit) {
		result = result[:*limit]
	}

	return result, nil
}

// AssetPriceStatistics is the resolver for the assetPriceStatistics field.
func (r *queryResolver) AssetPriceStatistics(ctx context.Context, assetID string) (*gqlModel.AssetPriceStatistics, error) {
	_, err := middleware.RequireAuth(ctx)
	if err != nil {
		return nil, err
	}

	stats, err := r.Resolver.UOW.AssetPrice().GetPriceStatistics(ctx, assetID)
	if err != nil {
		return nil, fmt.Errorf("failed to get price statistics: %w", err)
	}

	staleThreshold := 15 * time.Minute
	isStale := time.Since(stats.LastUpdated) > staleThreshold

	return &gqlModel.AssetPriceStatistics{
		AssetID:       stats.AssetID,
		CurrentPrice:  stats.CurrentPrice.InexactFloat64(),
		PreviousPrice: stats.PreviousPrice.InexactFloat64(),
		Change:        stats.Change.InexactFloat64(),
		ChangePercent: stats.ChangePercent.InexactFloat64(),
		DayHigh:       stats.DayHigh.InexactFloat64(),
		DayLow:        stats.DayLow.InexactFloat64(),
		WeekHigh:      stats.WeekHigh.InexactFloat64(),
		WeekLow:       stats.WeekLow.InexactFloat64(),
		MonthHigh:     stats.MonthHigh.InexactFloat64(),
		MonthLow:      stats.MonthLow.InexactFloat64(),
		YearHigh:      stats.YearHigh.InexactFloat64(),
		YearLow:       stats.YearLow.InexactFloat64(),
		AverageVolume: func() *float64 {
			if stats.AverageVolume != nil {
				v := stats.AverageVolume.InexactFloat64()
				return &v
			}
			return nil
		}(),
		LastUpdated: stats.LastUpdated,
		IsStale:     isStale,
	}, nil
}

// TechnicalIndicator is the resolver for the technicalIndicator field.
func (r *queryResolver) TechnicalIndicator(ctx context.Context, symbol string, assetType string, indicator string, interval string, timePeriod int32, seriesType string, from *time.Time, to *time.Time) (*gqlModel.TechnicalIndicatorResponse, error) {
	user, _ := middleware.GetUserFromContext(ctx)
	uid := ""
	if user != nil {
		uid = user.ID
	}

	fromTime := time.Time{}
	toTime := time.Now()
	if from != nil {
		fromTime = *from
	}
	if to != nil {
		toTime = *to
	}

	resp, err := r.Resolver.MarketDataService.GetTechnicalIndicator(ctx, uid, symbol, assetType, indicator, model.CandleInterval(interval), int(timePeriod), seriesType, fromTime, toTime)
	if err != nil {
		return nil, err
	}

	points := make([]*gqlModel.TechnicalIndicatorPoint, 0, len(resp.Data))
	for _, p := range resp.Data {
		pt := &gqlModel.TechnicalIndicatorPoint{
			Timestamp: p.Timestamp,
			Value:     p.Value,
			Signal:    p.Signal,
			Histogram: p.Histogram,
			UpperBand: p.UpperBand,
			LowerBand: p.LowerBand,
		}
		points = append(points, pt)
	}

	return &gqlModel.TechnicalIndicatorResponse{
		Indicator: resp.Indicator,
		Symbol:    resp.Symbol,
		Data:      points,
		Source:    resp.Source,
		Timestamp: resp.Timestamp,
	}, nil
}

// ProviderRoutingPreferences is the resolver for the providerRoutingPreferences field.
func (r *queryResolver) ProviderRoutingPreferences(ctx context.Context) (*gqlModel.ProviderRoutingPreferences, error) {
	user, err := middleware.RequireAuth(ctx)
	if err != nil {
		return nil, err
	}

	// Get user's configured providers from stored credentials
	creds, err := r.Resolver.UOW.MarketDataCredential().ListByUser(ctx, user.ID)
	if err != nil {
		// Return defaults if we can't fetch credentials
		creds = nil
	}

	// Get supported providers to build default preferences
	providers := r.Resolver.MarketDataService.GetSupportedProviders("STOCK")

	// Build preferred providers list based on stored credentials and defaults
	preferredProviders := make([]*gqlModel.ProviderPreference, 0)
	enabledProviders := make(map[string]bool)
	for _, cred := range creds {
		enabledProviders[cred.Provider] = true
	}

	// Add all configured providers as enabled preferences
	for _, provider := range providers {
		if enabledProviders[provider.ID] {
			preferredProviders = append(preferredProviders, &gqlModel.ProviderPreference{
				Provider: provider.ID,
				Priority: int32(len(preferredProviders) + 1),
				Enabled:  true,
			})
		}
	}

	// If no preferences stored, use default priority from provider manager
	if len(preferredProviders) == 0 {
		for i, provider := range providers {
			preferredProviders = append(preferredProviders, &gqlModel.ProviderPreference{
				Provider: provider.ID,
				Priority: int32(i + 1),
				Enabled:  true,
			})
		}
	}

	now := time.Now()
	return &gqlModel.ProviderRoutingPreferences{
		ID:                        fmt.Sprintf("pref_%s", user.ID[:8]),
		UserID:                    user.ID,
		PreferredProviders:        preferredProviders,
		UseIntelligentRouting:     true,
		EnableFallback:            true,
		StaleDataThresholdMinutes: 30,
		CreatedAt:                 now,
		UpdatedAt:                 now,
	}, nil
}
