package graphql

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.55

import (
	"context"
	"fmt"
	"sigma_finance/internal/domain/model"
	gqlModel "sigma_finance/internal/handler/graphql/model"
	"sigma_finance/internal/handler/middleware"
	"strconv"
	"time"
)

// UpsertMarketDataCredential is the resolver for the upsertMarketDataCredential field.
func (r *mutationResolver) UpsertMarketDataCredential(ctx context.Context, provider string, apiKey string) (*gqlModel.MarketDataCredential, error) {
	user, err := middleware.RequireAuth(ctx)
	if err != nil {
		return nil, err
	}
	uid, _ := strconv.Atoi(user.ID)
	repo := r.Resolver.UOW.MarketDataCredential()
	existing, _ := repo.GetByUserAndProvider(ctx, uid, provider)
	now := time.Now()
	storedKey := apiKey
	if r.Resolver.SecurityService != nil {
		if enc, e := r.Resolver.SecurityService.EncryptString(apiKey); e == nil {
			storedKey = enc
		}
	}
	if existing != nil {
		existing.APIKey = storedKey
		existing.UpdatedAt = now
		if err := repo.Update(ctx, existing); err != nil {
			return nil, err
		}
		return &gqlModel.MarketDataCredential{ID: strconv.Itoa(existing.ID), Provider: existing.Provider, CreatedAt: existing.CreatedAt, UpdatedAt: existing.UpdatedAt}, nil
	}
	cred := &model.MarketDataCredential{UserID: uid, Provider: provider, APIKey: storedKey, CreatedAt: now, UpdatedAt: now}
	created, err := repo.Create(ctx, cred)
	if err != nil {
		return nil, err
	}
	return &gqlModel.MarketDataCredential{ID: strconv.Itoa(created.ID), Provider: created.Provider, CreatedAt: created.CreatedAt, UpdatedAt: created.UpdatedAt}, nil
}

// DeleteMarketDataCredential is the resolver for the deleteMarketDataCredential field.
func (r *mutationResolver) DeleteMarketDataCredential(ctx context.Context, provider string) (string, error) {
	user, err := middleware.RequireAuth(ctx)
	if err != nil {
		return "", err
	}
	uid, _ := strconv.Atoi(user.ID)
	repo := r.Resolver.UOW.MarketDataCredential()
	existing, err := repo.GetByUserAndProvider(ctx, uid, provider)
	if err != nil {
		return "", err
	}
	if err := repo.Delete(ctx, existing.ID); err != nil {
		return "", err
	}
	return provider, nil
}

// ValidateProviderCredentials is the resolver for the validateProviderCredentials field.
func (r *mutationResolver) ValidateProviderCredentials(ctx context.Context, provider string, apiKey string) (*gqlModel.ValidationResult, error) {
	panic(fmt.Errorf("not implemented: ValidateProviderCredentials - validateProviderCredentials"))
}

// Candles resolver
func (r *queryResolver) Candles(ctx context.Context, symbol string, assetType string, interval string, from time.Time, to time.Time, limit *int32) ([]*gqlModel.Candle, error) {
	lim := 500
	if limit != nil {
		lim = int(*limit)
	}
	user, _ := middleware.GetUserFromContext(ctx)
	uid := 0
	if user != nil {
		if parsed, err := strconv.Atoi(user.ID); err == nil {
			uid = parsed
		}
	}
	candles, err := r.Resolver.MarketDataService.GetCandles(ctx, uid, symbol, assetType, model.CandleInterval(interval), from, to, lim)
	if err != nil {
		return nil, err
	}
	out := make([]*gqlModel.Candle, 0, len(candles))
	for _, c := range candles {
		out = append(out, &gqlModel.Candle{Symbol: c.Symbol, AssetType: c.AssetType, Interval: string(c.Interval), Open: c.Open.ToFloat(), High: c.High.ToFloat(), Low: c.Low.ToFloat(), Close: c.Close.ToFloat(), Volume: &c.Volume, Timestamp: c.Timestamp, Source: c.Source})
	}
	return out, nil
}

// MarketDataCredentials resolver
func (r *queryResolver) MarketDataCredentials(ctx context.Context) ([]*gqlModel.MarketDataCredential, error) {
	user, err := middleware.RequireAuth(ctx)
	if err != nil {
		return nil, err
	}
	uid, _ := strconv.Atoi(user.ID)
	creds, err := r.Resolver.UOW.MarketDataCredential().ListByUser(ctx, uid)
	if err != nil {
		return nil, err
	}
	out := make([]*gqlModel.MarketDataCredential, 0, len(creds))
	for _, c := range creds {
		out = append(out, &gqlModel.MarketDataCredential{ID: strconv.Itoa(c.ID), Provider: c.Provider, CreatedAt: c.CreatedAt, UpdatedAt: c.UpdatedAt})
	}
	return out, nil
}

// SupportedProviders resolver
func (r *queryResolver) SupportedProviders(ctx context.Context, assetType string) ([]*gqlModel.ProviderInfo, error) {
	_, err := middleware.RequireAuth(ctx)
	if err != nil {
		return nil, err
	}

	providers := r.Resolver.MarketDataService.GetSupportedProviders(assetType)
	out := make([]*gqlModel.ProviderInfo, 0, len(providers))

	for _, p := range providers {
		rateLimit := &gqlModel.RateLimit{
			RequestsPerMinute: int32(p.RateLimit.RequestsPerMinute),
			RequestsPerDay:    int32(p.RateLimit.RequestsPerDay),
			BurstLimit:        int32(p.RateLimit.BurstLimit),
		}

		out = append(out, &gqlModel.ProviderInfo{
			ID:               p.ID,
			Name:             p.Name,
			Type:             p.Type,
			RequiresKey:      p.RequiresKey,
			Intervals:        p.Intervals,
			RateLimit:        rateLimit,
			SupportsRealtime: p.SupportsRT,
		})
	}

	return out, nil
}

// ProviderHealth resolver
func (r *queryResolver) ProviderHealth(ctx context.Context) ([]*gqlModel.ProviderHealth, error) {
	_, err := middleware.RequireAuth(ctx)
	if err != nil {
		return nil, err
	}

	health := r.Resolver.MarketDataService.GetProviderHealth(ctx)
	out := make([]*gqlModel.ProviderHealth, 0, len(health))

	now := time.Now()
	for provider, healthy := range health {
		out = append(out, &gqlModel.ProviderHealth{
			Provider:    provider,
			Healthy:     healthy,
			LastChecked: now,
		})
	}

	return out, nil
}

// RealTimePrice resolver
func (r *queryResolver) RealTimePrice(ctx context.Context, symbol string, assetType string) (*gqlModel.Candle, error) {
	user, _ := middleware.GetUserFromContext(ctx)
	uid := 0
	if user != nil {
		if parsed, err := strconv.Atoi(user.ID); err == nil {
			uid = parsed
		}
	}

	candle, err := r.Resolver.MarketDataService.GetRealTimePrice(ctx, uid, symbol, assetType)
	if err != nil {
		return nil, err
	}

	return &gqlModel.Candle{
		Symbol:    candle.Symbol,
		AssetType: candle.AssetType,
		Interval:  string(candle.Interval),
		Open:      candle.Open.ToFloat(),
		High:      candle.High.ToFloat(),
		Low:       candle.Low.ToFloat(),
		Close:     candle.Close.ToFloat(),
		Volume:    &candle.Volume,
		Timestamp: candle.Timestamp,
		Source:    candle.Source,
	}, nil
}
