package graphql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.89

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"sigma_finance/internal/domain/model"
	gqlModel "sigma_finance/internal/handler/graphql/model"
	"sigma_finance/internal/handler/middleware"
	"sigma_finance/internal/repository"
	"sigma_finance/internal/service"
	"strings"
	"time"
)

// CreateUser is the resolver for the createUser field.
func (r *mutationResolver) CreateUser(ctx context.Context, input gqlModel.CreateUserInput) (*gqlModel.User, error) {
	userInput := service.CreateUserInput{
		Username: input.Username,
		Email:    input.Email,
		Password: input.Password,
	}
	user, err := r.UserService.CreateUser(ctx, userInput)
	if err != nil {
		return nil, err
	}
	return mapUserToGQL(*user), nil
}

// UpdateUser is the resolver for the updateUser field.
func (r *mutationResolver) UpdateUser(ctx context.Context, id string, input gqlModel.UpdateUserInput) (*gqlModel.User, error) {
	userInput := service.UpdateUserInput{
		Username: input.Username,
		Email:    input.Email,
		Password: input.Password,
	}
	user, err := r.UserService.UpdateUser(ctx, id, userInput)
	if err != nil {
		return nil, err
	}
	return mapUserToGQL(*user), nil
}

// UpdateUserDisplayCurrency is the resolver for the updateUserDisplayCurrency field.
func (r *mutationResolver) UpdateUserDisplayCurrency(ctx context.Context, input gqlModel.UpdateUserDisplayCurrencyInput) (*gqlModel.User, error) {
	userID, err := getUserIDFromContext(ctx)
	if err != nil {
		return nil, err
	}
	displayCurrency := model.Currency(input.DisplayCurrency)
	if !displayCurrency.IsValid() {
		return nil, fmt.Errorf("invalid display currency: %s", input.DisplayCurrency)
	}

	// Update user's display currency via repository
	err = r.UOW.User().UpdateDisplayCurrency(ctx, userID, displayCurrency)
	if err != nil {
		return nil, err
	}

	// Return updated user
	user, err := r.UserService.GetByID(ctx, userID)
	if err != nil {
		return nil, err
	}
	return mapUserToGQL(*user), nil
}

// UpdateUserThemePreferences is the resolver for the updateUserThemePreferences field.
func (r *mutationResolver) UpdateUserThemePreferences(ctx context.Context, input gqlModel.UpdateUserThemePreferencesInput) (*gqlModel.User, error) {
	userID, err := getUserIDFromContext(ctx)
	if err != nil {
		return nil, err
	}

	preferences := model.UserThemePreferences{
		ThemePreference:     model.ThemePreference(strings.ToLower(input.ThemePreference)),
		ThemeBaseColor:      model.ThemeBaseColor(strings.ToLower(input.ThemeBaseColor)),
		ThemeAccentColor:    model.ThemeAccentColor(strings.ToLower(input.ThemeAccentColor)),
		ThemeFontPreference: model.ThemeFontPreference(strings.ToLower(input.ThemeFontPreference)),
		ThemeHeadingFont:    model.ThemeHeadingFont(strings.ToLower(input.ThemeHeadingFont)),
		ThemeMenuAccent:     model.ThemeMenuAccent(strings.ToLower(input.ThemeMenuAccent)),
		ThemeMenuColor:      model.ThemeMenuColor(strings.ToLower(input.ThemeMenuColor)),
		ThemeStyle:          model.ThemeStyle(strings.ToLower(input.ThemeStyle)),
		ThemeRadius:         input.ThemeRadius,
		ThemeRTL:            input.ThemeRtl,
	}

	if err := preferences.Validate(); err != nil {
		return nil, err
	}

	if err := r.UOW.User().UpdateThemePreferences(ctx, userID, preferences); err != nil {
		return nil, err
	}

	user, err := r.UserService.GetByID(ctx, userID)
	if err != nil {
		return nil, err
	}

	return mapUserToGQL(*user), nil
}

// DeleteUser is the resolver for the deleteUser field.
func (r *mutationResolver) DeleteUser(ctx context.Context, id string) (string, error) {
	err := r.UserService.DeleteUser(ctx, id)
	if err != nil {
		return "", err
	}
	return id, nil
}

// CreatePortfolio is the resolver for the createPortfolio field.
func (r *mutationResolver) CreatePortfolio(ctx context.Context, input gqlModel.CreatePortfolioInput) (*gqlModel.Portfolio, error) {
	authUser, err := middleware.RequireAuth(ctx)
	if err != nil {
		return nil, err
	}

	if input.UserID != authUser.ID {
		return nil, fmt.Errorf("unauthorized: cannot create portfolio for another user")
	}

	portfolioInput := service.CreatePortfolioInput{
		UserID:      authUser.ID, // Override with authenticated user ID
		Name:        input.Name,
		Description: input.Description,
	}
	portfolio, err := r.PortfolioService.CreatePortfolio(ctx, portfolioInput)
	if err != nil {
		return nil, err
	}
	return mapPortfolioToGQL(*portfolio), nil
}

// UpdatePortfolio is the resolver for the updatePortfolio field.
func (r *mutationResolver) UpdatePortfolio(ctx context.Context, id string, input gqlModel.UpdatePortfolioInput) (*gqlModel.Portfolio, error) {
	authUser, err := middleware.RequireAuth(ctx)
	if err != nil {
		return nil, err
	}

	if err := r.PortfolioService.ValidatePortfolioOwnership(ctx, id, authUser.ID); err != nil {
		return nil, err
	}

	var sortOrder *int
	if input.SortOrder != nil {
		val := int(*input.SortOrder)
		sortOrder = &val
	}

	portfolio, err := r.PortfolioService.UpdatePortfolio(ctx, id, service.UpdatePortfolioInput{
		Name:        input.Name,
		Description: input.Description,
		SortOrder:   sortOrder,
	})
	if err != nil {
		return nil, err
	}
	return mapPortfolioToGQL(*portfolio), nil
}

// DeletePortfolio is the resolver for the deletePortfolio field.
func (r *mutationResolver) DeletePortfolio(ctx context.Context, id string) (string, error) {
	authUser, err := middleware.RequireAuth(ctx)
	if err != nil {
		return "", err
	}

	if err := r.PortfolioService.ValidatePortfolioOwnership(ctx, id, authUser.ID); err != nil {
		return "", err
	}

	err = r.PortfolioService.DeletePortfolio(ctx, id)
	if err != nil {
		return "", err
	}
	return id, nil
}

// AddAssetToPortfolio is the resolver for the addAssetToPortfolio field.
func (r *mutationResolver) AddAssetToPortfolio(ctx context.Context, input gqlModel.PortfolioAssetInput) (*gqlModel.PortfolioAsset, error) {
	authUser, err := middleware.RequireAuth(ctx)
	if err != nil {
		return nil, err
	}
	if err := r.PortfolioService.ValidatePortfolioOwnership(ctx, input.PortfolioID, authUser.ID); err != nil {
		return nil, err
	}

	pa, err := r.PortfolioService.AddAssetToPortfolio(ctx, input.PortfolioID, input.AssetID, input.Quantity, getFloat64(input.AveragePurchasePrice))
	if err != nil {
		return nil, err
	}
	gqlAsset, _ := r.getAssetWithDetails(ctx, pa.AssetID)
	return mapPortfolioAssetToGQLWithAsset(*pa, gqlAsset), nil
}

// UpdateAssetInPortfolio is the resolver for the updateAssetInPortfolio field.
func (r *mutationResolver) UpdateAssetInPortfolio(ctx context.Context, input gqlModel.PortfolioAssetInput) (*gqlModel.PortfolioAsset, error) {
	authUser, err := middleware.RequireAuth(ctx)
	if err != nil {
		return nil, err
	}
	if err := r.PortfolioService.ValidatePortfolioOwnership(ctx, input.PortfolioID, authUser.ID); err != nil {
		return nil, err
	}

	pa, err := r.PortfolioService.UpdateAssetInPortfolio(ctx, input.PortfolioID, input.AssetID, input.Quantity, getFloat64(input.AveragePurchasePrice))
	if err != nil {
		return nil, err
	}
	gqlAsset, _ := r.getAssetWithDetails(ctx, pa.AssetID)
	return mapPortfolioAssetToGQLWithAsset(*pa, gqlAsset), nil
}

// RemoveAssetFromPortfolio is the resolver for the removeAssetFromPortfolio field.
func (r *mutationResolver) RemoveAssetFromPortfolio(ctx context.Context, portfolioID string, assetID string) (string, error) {
	authUser, err := middleware.RequireAuth(ctx)
	if err != nil {
		return "", err
	}
	if err := r.PortfolioService.ValidatePortfolioOwnership(ctx, portfolioID, authUser.ID); err != nil {
		return "", err
	}

	err = r.PortfolioService.RemoveAssetFromPortfolio(ctx, portfolioID, assetID)
	if err != nil {
		return "", err
	}
	return assetID, nil
}

// TagPortfolio is the resolver for the tagPortfolio field.
func (r *mutationResolver) TagPortfolio(ctx context.Context, portfolioID string, tagID string) (*gqlModel.Portfolio, error) {
	authUser, err := middleware.RequireAuth(ctx)
	if err != nil {
		return nil, err
	}
	if err := r.PortfolioService.ValidatePortfolioOwnership(ctx, portfolioID, authUser.ID); err != nil {
		return nil, err
	}

	err = r.TagService.TagPortfolio(ctx, portfolioID, tagID)
	if err != nil {
		return nil, err
	}
	p, err := r.PortfolioService.GetByID(ctx, portfolioID)
	if err != nil {
		return nil, err
	}
	return mapPortfolioToGQL(*p), nil
}

// UntagPortfolio is the resolver for the untagPortfolio field.
func (r *mutationResolver) UntagPortfolio(ctx context.Context, portfolioID string, tagID string) (*gqlModel.Portfolio, error) {
	authUser, err := middleware.RequireAuth(ctx)
	if err != nil {
		return nil, err
	}
	if err := r.PortfolioService.ValidatePortfolioOwnership(ctx, portfolioID, authUser.ID); err != nil {
		return nil, err
	}

	err = r.TagService.UntagPortfolio(ctx, portfolioID, tagID)
	if err != nil {
		return nil, err
	}
	p, err := r.PortfolioService.GetByID(ctx, portfolioID)
	if err != nil {
		return nil, err
	}
	return mapPortfolioToGQL(*p), nil
}

// DuplicatePortfolio is the resolver for the duplicatePortfolio field.
func (r *mutationResolver) DuplicatePortfolio(ctx context.Context, input gqlModel.DuplicatePortfolioInput) (*gqlModel.Portfolio, error) {
	authUser, err := middleware.RequireAuth(ctx)
	if err != nil {
		return nil, err
	}
	if err := r.PortfolioService.ValidatePortfolioOwnership(ctx, input.SourcePortfolioID, authUser.ID); err != nil {
		return nil, err
	}

	p, err := r.PortfolioService.DuplicatePortfolio(ctx, service.DuplicatePortfolioInput{
		SourcePortfolioID: input.SourcePortfolioID,
		NewName:           input.NewName,
		Description:       getStr(input.Description),
		CopyAssets:        input.CopyAssets,
	})
	if err != nil {
		return nil, err
	}
	return mapPortfolioToGQL(*p), nil
}

// ReorderPortfolios is the resolver for the reorderPortfolios field.
func (r *mutationResolver) ReorderPortfolios(ctx context.Context, input gqlModel.ReorderPortfoliosInput) ([]*gqlModel.Portfolio, error) {
	// ReorderPortfolios Input parsing might need loop
	orders := make([]service.PortfolioOrderInput, len(input.PortfolioOrders))
	for i, o := range input.PortfolioOrders {
		orders[i] = service.PortfolioOrderInput{
			PortfolioID: o.PortfolioID,
			SortOrder:   int(o.SortOrder),
		}
	}

	_, err := r.PortfolioService.ReorderPortfolios(ctx, input.UserID, orders)
	if err != nil {
		return nil, err
	}

	// Fetch all user portfolios to return updated list
	portfolios, err := r.PortfolioService.GetPortfoliosByUser(ctx, input.UserID, "sort_order")
	if err != nil {
		return nil, err
	}

	res := make([]*gqlModel.Portfolio, len(portfolios))
	for i, p := range portfolios {
		res[i] = mapPortfolioToGQL(p)
	}
	return res, nil
}

// ExportPortfolio is the resolver for the exportPortfolio field.
func (r *mutationResolver) ExportPortfolio(ctx context.Context, input gqlModel.ExportPortfolioInput) (*gqlModel.ExportResult, error) {
	return &gqlModel.ExportResult{
		Success: false,
		Error:   stringPtr("Export not yet implemented in service layer"),
	}, nil
}

// CreateStockAsset is the resolver for the createStockAsset field.
func (r *mutationResolver) CreateStockAsset(ctx context.Context, input gqlModel.CreateStockInput) (*gqlModel.Stock, error) {
	var asset *model.Asset
	var err error
	userID, _ := getUserIDFromContext(ctx)
	ownerPtr := (*string)(nil)
	if strings.TrimSpace(userID) != "" {
		ownerPtr = &userID
	}

	quoteCurrency := model.Currency(strings.ToUpper(strings.TrimSpace(input.QuoteCurrency)))
	if !quoteCurrency.IsValid() {
		return nil, fmt.Errorf("invalid quote currency: %s", input.QuoteCurrency)
	}

	metadata, marshalErr := json.Marshal(map[string]string{
		"currency": quoteCurrency.String(),
	})
	if marshalErr != nil {
		return nil, fmt.Errorf("failed to marshal stock metadata: %w", marshalErr)
	}

	err = r.UOW.Do(ctx, func(uow repository.IUnitOfWork) error {
		normalizedTicker := strings.ToUpper(strings.TrimSpace(input.Ticker))
		var linkedInstrumentID *string
		rows, searchErr := uow.Instrument().Search(ctx, normalizedTicker, repository.InstrumentSearchFilter{
			AssetTypes: []model.InstrumentAssetType{
				model.InstrumentAssetTypeStock,
				model.InstrumentAssetTypeETF,
				model.InstrumentAssetTypeFund,
			},
			OwnerUserID: ownerPtr,
			Limit:       5,
		})
		if searchErr != nil {
			return fmt.Errorf("failed to search instrument: %w", searchErr)
		}
		for _, row := range rows {
			if strings.EqualFold(strings.TrimSpace(row.Instrument.Symbol), normalizedTicker) {
				instrumentID := row.Instrument.ID
				linkedInstrumentID = &instrumentID
				break
			}
		}
		if linkedInstrumentID == nil {
			now := time.Now().UTC()
			manualInstrument := &model.Instrument{
				Symbol:           normalizedTicker,
				NormalizedSymbol: normalizedTicker,
				Name:             strings.TrimSpace(input.Name),
				NormalizedName:   strings.ToLower(strings.TrimSpace(input.Name)),
				Exchange:         "MANUAL",
				AssetType:        model.InstrumentAssetTypeStock,
				Status:           model.InstrumentStatusUnknown,
				ProviderSource:   "manual",
				OwnerUserID:      ownerPtr,
				FirstSeenAt:      now,
			}
			if manualInstrument.NormalizedName == "" {
				manualInstrument.NormalizedName = strings.ToLower(normalizedTicker)
			}
			createdInstrument, createInstrumentErr := uow.Instrument().Upsert(ctx, manualInstrument)
			if createInstrumentErr != nil {
				return fmt.Errorf("failed to create manual instrument for ticker %s: %w", normalizedTicker, createInstrumentErr)
			}
			if createdInstrument != nil && strings.TrimSpace(createdInstrument.ID) != "" {
				instrumentID := strings.TrimSpace(createdInstrument.ID)
				linkedInstrumentID = &instrumentID

				_, _ = uow.InstrumentProviderMapping().Upsert(ctx, &model.InstrumentProviderMapping{
					InstrumentID:    instrumentID,
					Provider:        "YFINANCE",
					ProviderAssetID: normalizedTicker,
					ProviderSymbol:  &normalizedTicker,
					QuoteCurrency:   stringPtr(quoteCurrency.String()),
					MappingStatus:   model.InstrumentProviderMappingStatusVerified,
					LastVerifiedAt:  &now,
				})
			}
		}

		asset, err = uow.Asset().Create(ctx, &model.Asset{
			InstrumentID: linkedInstrumentID,
			Name:         input.Name,
			Symbol:       &input.Ticker,
			Type:         model.AssetTypeStock,
			IsTradeable:  true,
			Metadata:     metadata,
		})
		if err != nil {
			return err
		}

		_, err = uow.Stock().Create(ctx, &model.Stock{
			AssetID:     asset.ID,
			Ticker:      input.Ticker,
			Quantity:    input.Quantity,
			BuyingPrice: getFloat64(input.PurchasePrice),
		})
		return err
	})

	if err != nil {
		return nil, err
	}

	tags, _ := r.TagService.GetAssetTags(ctx, asset.ID)
	// We need to load the stock details for mapping
	stockDetails, _ := r.UOW.Stock().GetByID(ctx, asset.ID)

	result := mapStockToGQL(*asset, stockDetails, tags, nil, nil, nil)
	// Set fields that come from input but aren't persisted in the assets table
	result.CurrentValue = input.CurrentValue
	result.PurchaseDate = input.PurchaseDate
	result.PurchasePrice = input.PurchasePrice

	r.triggerAssetPriceRefresh(asset)

	return result, nil
}

// CreateCryptoAsset is the resolver for the createCryptoAsset field.
func (r *mutationResolver) CreateCryptoAsset(ctx context.Context, input gqlModel.CreateCryptoInput) (*gqlModel.Crypto, error) {
	var asset *model.Asset
	var err error

	quoteCurrency := model.Currency(strings.ToUpper(strings.TrimSpace(input.QuoteCurrency)))
	if !quoteCurrency.IsValid() {
		return nil, fmt.Errorf("invalid quote currency: %s", input.QuoteCurrency)
	}

	metadataPayload := map[string]interface{}{
		"currency": quoteCurrency.String(),
	}
	if input.PurchaseDate != nil {
		metadataPayload["purchase_date"] = input.PurchaseDate.UTC().Format(time.RFC3339)
	}
	if input.BlockchainNetwork != nil {
		metadataPayload["blockchain"] = *input.BlockchainNetwork
	}
	if input.WalletAddress != nil {
		metadataPayload["wallet_address"] = *input.WalletAddress
	}
	metadata, marshalErr := json.Marshal(metadataPayload)
	if marshalErr != nil {
		return nil, fmt.Errorf("failed to marshal crypto metadata: %w", marshalErr)
	}

	err = r.UOW.Do(ctx, func(uow repository.IUnitOfWork) error {
		// Manual create path is non-tradeable. Tradeable crypto must use addInstrumentToPortfolio.
		asset, err = uow.Asset().Create(ctx, &model.Asset{
			Name:        input.Name,
			Symbol:      &input.Name, // Use name as symbol if ticker not provided
			Type:        model.AssetTypeCrypto,
			IsTradeable: false,
			Metadata:    metadata,
		})
		if err != nil {
			return err
		}

		_, err = uow.Crypto().Create(ctx, &model.Crypto{
			AssetID:           asset.ID,
			Quantity:          input.Quantity,
			WalletAddress:     getStr(input.WalletAddress),
			BlockchainNetwork: getStr(input.BlockchainNetwork),
		})
		return err
	})

	if err != nil {
		return nil, err
	}

	tags, _ := r.TagService.GetAssetTags(ctx, asset.ID)
	cryptoDetails, _ := r.UOW.Crypto().GetByID(ctx, asset.ID)

	result := mapCryptoToGQL(*asset, cryptoDetails, tags, nil, nil, nil)
	// Set fields that come from input but aren't persisted in the assets table
	result.CurrentValue = input.CurrentValue
	result.PurchaseDate = input.PurchaseDate
	result.PurchasePrice = input.PurchasePrice

	return result, nil
}

// CreateBankAccountAsset is the resolver for the createBankAccountAsset field.
func (r *mutationResolver) CreateBankAccountAsset(ctx context.Context, input gqlModel.CreateBankAccountInput) (*gqlModel.BankAccount, error) {
	var asset *model.Asset
	var err error

	// Build bank account metadata
	metadata := model.BankAccountMetadata{
		AccountType:   input.AccountType,
		Institution:   input.Institution,
		AccountNumber: input.AccountNumber,
		Currency:      input.Currency,
		InterestRate:  input.InterestRate,
	}
	metadataBytes, marshalErr := json.Marshal(metadata)
	if marshalErr != nil {
		return nil, fmt.Errorf("failed to marshal bank account metadata: %w", marshalErr)
	}

	err = r.UOW.Do(ctx, func(uow repository.IUnitOfWork) error {
		asset, err = uow.Asset().Create(ctx, &model.Asset{
			Name:        input.Name,
			Symbol:      &input.Institution, // Use institution as symbol for bank accounts
			Type:        model.AssetTypeBankAccount,
			IsTradeable: false,
			Metadata:    metadataBytes,
		})
		return err
	})

	if err != nil {
		return nil, err
	}

	tags, _ := r.TagService.GetAssetTags(ctx, asset.ID)

	result := mapBankAccountToGQL(*asset, tags, nil, nil, nil)
	// Set fields that come from input but aren't persisted in the assets table
	result.CurrentValue = input.CurrentValue
	result.PurchaseDate = input.PurchaseDate
	result.PurchasePrice = input.PurchasePrice
	result.Balance = input.CurrentValue // Balance equals current value for bank accounts

	return result, nil
}

// CreateRealEstateAsset is the resolver for the createRealEstateAsset field.
func (r *mutationResolver) CreateRealEstateAsset(ctx context.Context, input gqlModel.CreateRealEstateInput) (*gqlModel.RealEstate, error) {
	var asset *model.Asset
	var err error

	// Build real estate metadata
	metadata := model.RealEstateMetadata{
		PropertyType: input.PropertyType,
		Address:      input.Address,
		City:         input.City,
		State:        getStr(input.State),
		Country:      input.Country,
		ZipCode:      getStr(input.ZipCode),
		SquareFeet:   int32ToInt(input.SquareFeet),
		YearBuilt:    int32ToInt(input.YearBuilt),
		Bedrooms:     int32ToInt(input.Bedrooms),
		Bathrooms:    input.Bathrooms,
	}
	metadataBytes, marshalErr := json.Marshal(metadata)
	if marshalErr != nil {
		return nil, fmt.Errorf("failed to marshal real estate metadata: %w", marshalErr)
	}

	err = r.UOW.Do(ctx, func(uow repository.IUnitOfWork) error {
		asset, err = uow.Asset().Create(ctx, &model.Asset{
			Name:        input.Name,
			Symbol:      &input.Address, // Use address as symbol for real estate
			Type:        model.AssetTypeRealEstate,
			IsTradeable: false,
			Metadata:    metadataBytes,
		})
		return err
	})

	if err != nil {
		return nil, err
	}

	tags, _ := r.TagService.GetAssetTags(ctx, asset.ID)

	result := mapRealEstateToGQL(*asset, tags, nil, nil, nil)
	result.CurrentValue = input.CurrentValue
	result.PurchaseDate = input.PurchaseDate
	result.PurchasePrice = input.PurchasePrice

	return result, nil
}

// CreateLifeInsuranceAsset is the resolver for the createLifeInsuranceAsset field.
func (r *mutationResolver) CreateLifeInsuranceAsset(ctx context.Context, input gqlModel.CreateLifeInsuranceInput) (*gqlModel.LifeInsurance, error) {
	var asset *model.Asset
	var err error

	// Build life insurance metadata
	metadata := model.LifeInsuranceMetadata{
		PolicyNumber:     input.PolicyNumber,
		Insurer:          input.Insurer,
		PolicyType:       input.PolicyType,
		CoverageAmount:   int64(input.CoverageAmount * 100), // Convert to cents
		PremiumAmount:    int64(input.PremiumAmount * 100),  // Convert to cents
		PremiumFrequency: input.PremiumFrequency,
		Beneficiaries:    input.Beneficiaries,
		MaturityDate:     input.MaturityDate,
	}
	metadataBytes, marshalErr := json.Marshal(metadata)
	if marshalErr != nil {
		return nil, fmt.Errorf("failed to marshal life insurance metadata: %w", marshalErr)
	}

	err = r.UOW.Do(ctx, func(uow repository.IUnitOfWork) error {
		asset, err = uow.Asset().Create(ctx, &model.Asset{
			Name:        input.Name,
			Symbol:      &input.PolicyNumber, // Use policy number as symbol
			Type:        model.AssetTypeLifeInsurance,
			IsTradeable: false,
			Metadata:    metadataBytes,
		})
		return err
	})

	if err != nil {
		return nil, err
	}

	tags, _ := r.TagService.GetAssetTags(ctx, asset.ID)

	result := mapLifeInsuranceToGQL(*asset, tags, nil, nil, nil)
	result.CurrentValue = input.CurrentValue
	result.PurchaseDate = input.PurchaseDate
	result.PurchasePrice = input.PurchasePrice

	return result, nil
}

// CreateWatchAsset is the resolver for the createWatchAsset field.
func (r *mutationResolver) CreateWatchAsset(ctx context.Context, input gqlModel.CreateWatchInput) (*gqlModel.Watch, error) {
	var asset *model.Asset
	var err error

	// Build watch metadata
	metadata := model.WatchMetadata{
		Brand:           input.Brand,
		Model:           input.Model,
		SerialNumber:    input.SerialNumber,
		ReferenceNumber: input.ReferenceNumber,
		Condition:       input.Condition,
		YearMade:        int32ToInt(input.YearMade),
		Material:        input.Material,
		Movement:        input.Movement,
		CaseSize:        input.CaseSize,
		WaterResistance: int32ToInt(input.WaterResistance),
	}
	metadataBytes, marshalErr := json.Marshal(metadata)
	if marshalErr != nil {
		return nil, fmt.Errorf("failed to marshal watch metadata: %w", marshalErr)
	}

	err = r.UOW.Do(ctx, func(uow repository.IUnitOfWork) error {
		asset, err = uow.Asset().Create(ctx, &model.Asset{
			Name:        input.Name,
			Symbol:      stringPtr(input.Brand + " " + input.Model), // Use brand+model as symbol
			Type:        model.AssetTypeWatch,
			IsTradeable: false,
			Metadata:    metadataBytes,
		})
		return err
	})

	if err != nil {
		return nil, err
	}

	tags, _ := r.TagService.GetAssetTags(ctx, asset.ID)

	result := mapWatchToGQL(*asset, tags, nil, nil, nil)
	result.CurrentValue = input.CurrentValue
	result.PurchaseDate = input.PurchaseDate
	result.PurchasePrice = input.PurchasePrice

	return result, nil
}

// CreateLoanAsset is the resolver for the createLoanAsset field.
func (r *mutationResolver) CreateLoanAsset(ctx context.Context, input gqlModel.CreateLoanInput) (*gqlModel.Loan, error) {
	var asset *model.Asset
	var err error

	// Build loan metadata
	metadata := model.LoanMetadata{
		LoanType:         input.LoanType,
		LoanAmount:       int64(input.LoanAmount * 100),       // Convert to cents
		RemainingBalance: int64(input.RemainingBalance * 100), // Convert to cents
		InterestRate:     input.InterestRate,
		DurationMonths:   int(input.DurationMonths),
		MonthlyPayment:   int64(input.MonthlyPayment * 100), // Convert to cents
		StartDate:        input.StartDate,
		Lender:           input.Lender,
		Currency:         input.Currency,
		Status:           input.Status,
	}
	if input.Description != nil {
		metadata.Description = *input.Description
	}
	if input.EndDate != nil {
		metadata.EndDate = *input.EndDate
	}
	if input.LoanNumber != nil {
		metadata.LoanNumber = *input.LoanNumber
	}
	if input.DownPayment != nil {
		metadata.DownPayment = int64(*input.DownPayment * 100) // Convert to cents
	}
	if input.OwnershipMode != nil {
		metadata.OwnershipMode = *input.OwnershipMode
	}
	if input.ApplicationFee != nil {
		metadata.ApplicationFee = int64(*input.ApplicationFee * 100) // Convert to cents
	}
	if input.BrokerFee != nil {
		metadata.BrokerFee = int64(*input.BrokerFee * 100) // Convert to cents
	}
	if input.InsuranceFee != nil {
		metadata.InsuranceFee = int64(*input.InsuranceFee * 100) // Convert to cents
	}
	if input.OtherFees != nil {
		metadata.OtherFees = int64(*input.OtherFees * 100) // Convert to cents
	}
	if input.EarlyRepaymentFee != nil {
		metadata.EarlyRepaymentFee = *input.EarlyRepaymentFee
	}

	metadataBytes, marshalErr := json.Marshal(metadata)
	if marshalErr != nil {
		return nil, fmt.Errorf("failed to marshal loan metadata: %w", marshalErr)
	}

	err = r.UOW.Do(ctx, func(uow repository.IUnitOfWork) error {
		asset, err = uow.Asset().Create(ctx, &model.Asset{
			Name:        input.Name,
			Symbol:      stringPtr(input.Lender + " loan"), // Use lender as symbol hint
			Type:        model.AssetTypeLoan,
			IsTradeable: false,
			Metadata:    metadataBytes,
		})
		return err
	})

	if err != nil {
		return nil, err
	}

	tags, _ := r.TagService.GetAssetTags(ctx, asset.ID)

	result := mapLoanToGQL(*asset, tags, nil, nil, nil)
	result.CurrentValue = input.CurrentValue
	result.PurchaseDate = input.PurchaseDate
	result.PurchasePrice = input.PurchasePrice

	return result, nil
}

// TagAsset is the resolver for the tagAsset field.
func (r *mutationResolver) TagAsset(ctx context.Context, assetID string, tagID string) (gqlModel.Asset, error) {
	err := r.TagService.TagAsset(ctx, assetID, tagID)
	if err != nil {
		return nil, err
	}
	return r.getAssetWithDetails(ctx, assetID)
}

// UntagAsset is the resolver for the untagAsset field.
func (r *mutationResolver) UntagAsset(ctx context.Context, assetID string, tagID string) (gqlModel.Asset, error) {
	err := r.TagService.UntagAsset(ctx, assetID, tagID)
	if err != nil {
		return nil, err
	}
	return r.getAssetWithDetails(ctx, assetID)
}

// CreateWatchlist is the resolver for the createWatchlist field.
func (r *mutationResolver) CreateWatchlist(ctx context.Context, input gqlModel.CreateWatchlistInput) (*gqlModel.Watchlist, error) {
	wlInput := service.CreateWatchlistInput{
		UserID: input.UserID,
		Name:   input.Name,
	}
	wl, err := r.WatchlistService.CreateWatchlist(ctx, wlInput)
	if err != nil {
		return nil, err
	}
	return mapWatchlistToGQL(*wl), nil
}

// DeleteWatchlist is the resolver for the deleteWatchlist field.
func (r *mutationResolver) DeleteWatchlist(ctx context.Context, id string) (string, error) {
	err := r.WatchlistService.DeleteWatchlist(ctx, id)
	if err != nil {
		return "", err
	}
	return id, nil
}

// AddAssetToWatchlist is the resolver for the addAssetToWatchlist field.
func (r *mutationResolver) AddAssetToWatchlist(ctx context.Context, watchlistID string, assetID string) (*gqlModel.Watchlist, error) {
	err := r.WatchlistService.AddAssetToWatchlist(ctx, watchlistID, assetID)
	if err != nil {
		return nil, err
	}
	wl, err := r.WatchlistService.GetByID(ctx, watchlistID)
	if err != nil {
		return nil, err
	}
	return mapWatchlistToGQL(*wl), nil
}

// RemoveAssetFromWatchlist is the resolver for the removeAssetFromWatchlist field.
func (r *mutationResolver) RemoveAssetFromWatchlist(ctx context.Context, watchlistID string, assetID string) (*gqlModel.Watchlist, error) {
	err := r.WatchlistService.RemoveAssetFromWatchlist(ctx, watchlistID, assetID)
	if err != nil {
		return nil, err
	}
	wl, err := r.WatchlistService.GetByID(ctx, watchlistID)
	if err != nil {
		return nil, err
	}
	return mapWatchlistToGQL(*wl), nil
}

// User is the resolver for the user field.
func (r *queryResolver) User(ctx context.Context, id string) (*gqlModel.User, error) {
	user, err := r.UserService.GetByID(ctx, id)
	if err != nil {
		if errors.Is(err, repository.ErrNotFound) {
			return nil, nil
		}
		return nil, err
	}
	return mapUserToGQL(*user), nil
}

// Users is the resolver for the users field.
func (r *queryResolver) Users(ctx context.Context, filter *gqlModel.UserFilter, pagination *gqlModel.PaginationInput, orderBy *gqlModel.UserOrder) ([]*gqlModel.User, error) {
	opts := []repository.QueryOption{}
	if filter != nil {
		if filter.Email != nil {
			opts = append(opts, repository.ByColumn("email", *filter.Email))
		}
		if filter.UsernameContains != nil {
			opts = append(opts, repository.ByColumnLike("username", "%"+*filter.UsernameContains+"%"))
		}
	}
	if orderBy != nil {
		opts = append(opts, repository.WithOrderBy(buildUserOrderString(orderBy.Field, orderBy.Direction)))
	}
	if pagination != nil {
		if pagination.Limit != nil {
			opts = append(opts, repository.WithLimit(int(*pagination.Limit)))
		}
		if pagination.Offset != nil {
			opts = append(opts, repository.WithOffset(int(*pagination.Offset)))
		}
	}

	users, err := r.UserService.FindAll(ctx, opts...)
	if err != nil {
		return nil, err
	}

	res := make([]*gqlModel.User, len(users))
	for i, u := range users {
		res[i] = mapUserToGQL(u)
	}
	return res, nil
}

// Portfolio is the resolver for the portfolio field.
func (r *queryResolver) Portfolio(ctx context.Context, id string) (*gqlModel.Portfolio, error) {
	p, err := r.PortfolioService.GetByID(ctx, id)
	if err != nil {
		if errors.Is(err, repository.ErrNotFound) || errors.Is(err, service.ErrPortfolioNotFound) {
			return nil, nil
		}
		return nil, err
	}
	gqlP := mapPortfolioToGQL(*p)

	// Get user's display currency for analytics
	displayCurrency, err := r.Resolver.getDisplayCurrencyFromContext(ctx)
	if err != nil {
		displayCurrency = model.CurrencyUSD // Default to USD
	}

	analytics, err := r.PortfolioService.GetPortfolioAnalytics(ctx, p.ID, displayCurrency)
	if err == nil {
		gqlP.Analytics = mapPortfolioValuationToGQL(analytics)
	}

	gqlP.Assets = r.buildPortfolioAssets(ctx, p.ID)

	return gqlP, nil
}

// GetPortfoliosWithAnalytics is the resolver for the GetPortfoliosWithAnalytics field.
func (r *queryResolver) GetPortfoliosWithAnalytics(ctx context.Context, userID string) ([]*gqlModel.Portfolio, error) {
	portfolios, err := r.PortfolioService.GetPortfoliosByUser(ctx, userID, "sort_order")
	if err != nil {
		return nil, err
	}

	// Get user's display currency for analytics
	displayCurrency, err := r.Resolver.getDisplayCurrencyFromContext(ctx)
	if err != nil {
		displayCurrency = model.CurrencyUSD // Default to USD
	}

	res := make([]*gqlModel.Portfolio, len(portfolios))
	for i, p := range portfolios {
		gqlP := mapPortfolioToGQL(p)

		analytics, err := r.PortfolioService.GetPortfolioAnalytics(ctx, p.ID, displayCurrency)
		if err == nil {
			gqlP.Analytics = mapPortfolioValuationToGQL(analytics)
		}

		gqlP.Assets = r.buildPortfolioAssets(ctx, p.ID)

		res[i] = gqlP
	}
	return res, nil
}

// Portfolios is the resolver for the portfolios field.
func (r *queryResolver) Portfolios(ctx context.Context, filter *gqlModel.PortfolioFilter, pagination *gqlModel.PaginationInput, orderBy *gqlModel.PortfolioOrder) ([]*gqlModel.Portfolio, error) {
	opts := []repository.QueryOption{}
	if filter != nil {
		if filter.UserID != nil {
			opts = append(opts, repository.ByColumn("user_id", *filter.UserID))
		}
		if filter.NameContains != nil {
			opts = append(opts, repository.ByColumnLike("name", "%"+*filter.NameContains+"%"))
		}
	}
	if orderBy != nil {
		opts = append(opts, repository.WithOrderBy(buildPortfolioOrderString(orderBy.Field, orderBy.Direction)))
	}
	if pagination != nil {
		if pagination.Limit != nil {
			opts = append(opts, repository.WithLimit(int(*pagination.Limit)))
		}
		if pagination.Offset != nil {
			opts = append(opts, repository.WithOffset(int(*pagination.Offset)))
		}
	}

	portfolios, err := r.PortfolioService.FindAll(ctx, opts...)
	if err != nil {
		return nil, err
	}

	// Get user's display currency for analytics
	displayCurrency, err := r.Resolver.getDisplayCurrencyFromContext(ctx)
	if err != nil {
		displayCurrency = model.CurrencyUSD // Default to USD
	}

	res := make([]*gqlModel.Portfolio, len(portfolios))
	for i, p := range portfolios {
		gqlP := mapPortfolioToGQL(p)

		// Fetch analytics for each portfolio
		analytics, err := r.PortfolioService.GetPortfolioAnalytics(ctx, p.ID, displayCurrency)
		if err == nil {
			gqlP.Analytics = mapPortfolioValuationToGQL(analytics)
		}

		gqlP.Assets = r.buildPortfolioAssets(ctx, p.ID)

		res[i] = gqlP
	}
	return res, nil
}

// Asset is the resolver for the asset field.
func (r *queryResolver) Asset(ctx context.Context, id string) (gqlModel.Asset, error) {
	return r.getAssetWithDetails(ctx, id)
}

// Assets is the resolver for the assets field.
func (r *queryResolver) Assets(ctx context.Context, filter *gqlModel.AssetFilter, pagination *gqlModel.PaginationInput, orderBy *gqlModel.AssetOrder) ([]gqlModel.Asset, error) {
	serviceFilter := service.AssetFilter{}
	if filter != nil {
		if filter.AssetTypeID != nil {
			at := model.AssetType(*filter.AssetTypeID)
			serviceFilter.AssetType = &at
		}
		serviceFilter.SearchTerm = filter.NameContains
	}
	if pagination != nil {
		if pagination.Limit != nil {
			l := int(*pagination.Limit)
			serviceFilter.Limit = &l
		}
		if pagination.Offset != nil {
			o := int(*pagination.Offset)
			serviceFilter.Offset = &o
		}
	}

	assets, err := r.AssetService.ListAssets(ctx, serviceFilter)
	if err != nil {
		return nil, err
	}

	res := make([]gqlModel.Asset, len(assets))
	for i, a := range assets {
		tags, _ := r.TagService.GetAssetTags(ctx, a.ID)
		if a.Type == model.AssetTypeStock {
			stockDetails, _ := r.UOW.Stock().GetByID(ctx, a.ID)
			res[i] = mapStockToGQL(*a, stockDetails, tags, nil, nil, nil)
		} else if a.Type == model.AssetTypeCrypto {
			cryptoDetails, _ := r.UOW.Crypto().GetByID(ctx, a.ID)
			res[i] = mapCryptoToGQL(*a, cryptoDetails, tags, nil, nil, nil)
		} else if a.Type == model.AssetTypeFund {
			fundDetails, _ := r.UOW.Fund().GetByID(ctx, a.ID)
			res[i] = mapFundToGQL(*a, fundDetails, tags, nil, nil, nil)
		} else if a.Type == model.AssetTypeBankAccount {
			res[i] = mapBankAccountToGQL(*a, tags, nil, nil, nil)
		} else if a.Type == model.AssetTypeRealEstate {
			res[i] = mapRealEstateToGQL(*a, tags, nil, nil, nil)
		} else if a.Type == model.AssetTypeLifeInsurance {
			res[i] = mapLifeInsuranceToGQL(*a, tags, nil, nil, nil)
		} else if a.Type == model.AssetTypeWatch {
			res[i] = mapWatchToGQL(*a, tags, nil, nil, nil)
		} else if a.Type == model.AssetTypeLoan {
			res[i] = mapLoanToGQL(*a, tags, nil, nil, nil)
		} else {
			// Generic mapping if needed
			res[i] = mapStockToGQL(*a, nil, tags, nil, nil, nil) // Fallback
		}
	}
	return res, nil
}

// AssetTypes is the resolver for the assetTypes field.
func (r *queryResolver) AssetTypes(ctx context.Context) ([]*gqlModel.AssetType, error) {
	types := []model.AssetType{model.AssetTypeStock, model.AssetTypeCrypto, model.AssetTypeBankAccount, model.AssetTypeRealEstate, model.AssetTypeLifeInsurance, model.AssetTypeWatch, model.AssetTypeLoan}
	res := make([]*gqlModel.AssetType, len(types))
	for i, t := range types {
		res[i] = mapAssetTypeToGQL(t)
	}
	return res, nil
}

// Tag is the resolver for the tag field.
func (r *queryResolver) Tag(ctx context.Context, id string) (*gqlModel.Tag, error) {
	tag, err := r.TagService.GetByID(ctx, id)
	if err != nil {
		return nil, err
	}
	return mapTagToGQL(*tag), nil
}

// Tags is the resolver for the tags field.
func (r *queryResolver) Tags(ctx context.Context) ([]*gqlModel.Tag, error) {
	user, err := middleware.RequireAuth(ctx)
	if err != nil {
		return nil, err
	}
	tags, err := r.TagService.FindAllByUserID(ctx, user.ID)
	if err != nil {
		return nil, err
	}
	res := make([]*gqlModel.Tag, len(tags))
	for i, t := range tags {
		res[i] = mapTagToGQL(t)
	}
	return res, nil
}

// Watchlist is the resolver for the watchlist field.
func (r *queryResolver) Watchlist(ctx context.Context, id string) (*gqlModel.Watchlist, error) {
	wl, err := r.WatchlistService.GetByID(ctx, id)
	if err != nil {
		if errors.Is(err, repository.ErrNotFound) {
			return nil, nil
		}
		return nil, err
	}
	return mapWatchlistToGQL(*wl), nil
}

// Watchlists is the resolver for the watchlists field.
func (r *queryResolver) Watchlists(ctx context.Context, filter *gqlModel.WatchlistFilter, pagination *gqlModel.PaginationInput) ([]*gqlModel.Watchlist, error) {
	opts := []repository.QueryOption{}
	if filter != nil {
		opts = append(opts, repository.ByColumn("user_id", filter.UserID))
	}
	if pagination != nil {
		if pagination.Limit != nil {
			opts = append(opts, repository.WithLimit(int(*pagination.Limit)))
		}
		if pagination.Offset != nil {
			opts = append(opts, repository.WithOffset(int(*pagination.Offset)))
		}
	}

	watchlists, err := r.WatchlistService.FindAll(ctx, opts...)
	if err != nil {
		return nil, err
	}

	res := make([]*gqlModel.Watchlist, len(watchlists))
	for i, w := range watchlists {
		res[i] = mapWatchlistToGQL(w)
	}
	return res, nil
}

// Transaction is the resolver for the transaction field.
func (r *queryResolver) Transaction(ctx context.Context, id string) (*gqlModel.Transaction, error) {
	t, err := r.TransactionService.GetTransaction(ctx, id)
	if err != nil {
		return nil, err
	}
	mapped := r.buildGraphQLTransaction(ctx, t)
	if mapped == nil {
		return nil, nil
	}
	return mapped, nil
}

// Transactions is the resolver for the transactions field.
func (r *queryResolver) Transactions(ctx context.Context, filter *gqlModel.TransactionFilter, pagination *gqlModel.PaginationInput, orderBy *gqlModel.TransactionOrder) ([]*gqlModel.Transaction, error) {
	serviceFilter := service.TransactionFilter{}
	if filter != nil {
		serviceFilter.UserID = filter.UserID
		serviceFilter.PortfolioID = filter.PortfolioID
		serviceFilter.AssetID = filter.AssetID
		if filter.TransactionType != nil {
			tt := model.TransactionType(*filter.TransactionType)
			serviceFilter.TransactionType = &tt
		}
	}
	if pagination != nil {
		if pagination.Limit != nil {
			l := int(*pagination.Limit)
			serviceFilter.Limit = &l
		}
		if pagination.Offset != nil {
			o := int(*pagination.Offset)
			serviceFilter.Offset = &o
		}
	}

	transactions, err := r.TransactionService.GetTransactionHistory(ctx, serviceFilter)
	if err != nil {
		return nil, err
	}

	res := make([]*gqlModel.Transaction, 0, len(transactions))
	for _, t := range transactions {
		mapped := r.buildGraphQLTransaction(ctx, t)
		if mapped == nil {
			continue
		}
		res = append(res, mapped)
	}
	return res, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }

// !!! WARNING !!!
// The code below was going to be deleted when updating resolvers. It has been copied here so you have
// one last chance to move it out of harms way if you want. There are two reasons this happens:
//  - When renaming or deleting a resolver the old code will be put in here. You can safely delete
//    it when you're done.
//  - You have helper methods in this file. Move them out to keep these resolver files clean.
/*
	func (r *mutationResolver) triggerAssetPriceRefresh(asset *model.Asset) {
	if r == nil || r.MarketDataService == nil || asset == nil || !asset.IsTradeable {
		return
	}

	assetID, err := uuid.Parse(asset.ID)
	if err != nil {
		log.Printf("[graphql] skipping async price refresh for asset %s: invalid uuid: %v", asset.ID, err)
		return
	}

	go func(assetID uuid.UUID, assetName string) {
		ctx, cancel := context.WithTimeout(context.Background(), 2*time.Minute)
		defer cancel()

		if _, refreshErr := r.MarketDataService.UpdateAssetPrice(ctx, assetID); refreshErr != nil {
			log.Printf("[graphql] async price refresh failed for asset %s: %v", assetName, refreshErr)
		}
	}(assetID, asset.Name)
}
*/
