package graphql

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.55

import (
	"context"
	"fmt"
	gqlModel "sigma_finance/internal/handler/graphql/model"
)

// PortfolioUpdates is the resolver for the portfolioUpdates field.
func (r *subscriptionResolver) PortfolioUpdates(ctx context.Context, userID string) (<-chan *gqlModel.PortfolioUpdatePayload, error) {
	panic(fmt.Errorf("not implemented: PortfolioUpdates - portfolioUpdates"))
}

// TransactionUpdates is the resolver for the transactionUpdates field.
func (r *subscriptionResolver) TransactionUpdates(ctx context.Context, userID string) (<-chan *gqlModel.TransactionUpdatePayload, error) {
	panic(fmt.Errorf("not implemented: TransactionUpdates - transactionUpdates"))
}

// Subscription returns SubscriptionResolver implementation.
func (r *Resolver) Subscription() SubscriptionResolver { return &subscriptionResolver{r} }

type subscriptionResolver struct{ *Resolver }
