// TODO: This GraphQL layer needs to be updated for the new asset management schema
// Temporarily excluded from build until GraphQL layer task is implemented
//go:build ignore

package graphql

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.55

import (
	"context"
	gqlModel "sigma_finance/internal/handler/graphql/model"
)

// PortfolioUpdates is the resolver for the portfolioUpdates field.
func (r *subscriptionResolver) PortfolioUpdates(ctx context.Context, userID string) (<-chan *gqlModel.PortfolioUpdatePayload, error) {
	updates := make(chan *gqlModel.PortfolioUpdatePayload, 1)
	r.Resolver.BroadcasterMu.Lock()
	r.Resolver.PortfolioSubscribers[userID] = append(r.Resolver.PortfolioSubscribers[userID], updates)
	r.Resolver.BroadcasterMu.Unlock()

	go func() {
		<-ctx.Done()
		// Remove channel from subscribers on disconnect
		r.Resolver.BroadcasterMu.Lock()
		subs := r.Resolver.PortfolioSubscribers[userID]
		for i, ch := range subs {
			if ch == updates {
				r.Resolver.PortfolioSubscribers[userID] = append(subs[:i], subs[i+1:]...)
				break
			}
		}
		r.Resolver.BroadcasterMu.Unlock()
		close(updates)
	}()
	return updates, nil
}

// TransactionUpdates is the resolver for the transactionUpdates field.
func (r *subscriptionResolver) TransactionUpdates(ctx context.Context, userID string) (<-chan *gqlModel.TransactionUpdatePayload, error) {
	updates := make(chan *gqlModel.TransactionUpdatePayload, 1)
	r.Resolver.BroadcasterMu.Lock()
	r.Resolver.TransactionSubscribers[userID] = append(r.Resolver.TransactionSubscribers[userID], updates)
	r.Resolver.BroadcasterMu.Unlock()

	go func() {
		<-ctx.Done()
		// Remove channel from subscribers on disconnect
		r.Resolver.BroadcasterMu.Lock()
		subs := r.Resolver.TransactionSubscribers[userID]
		for i, ch := range subs {
			if ch == updates {
				r.Resolver.TransactionSubscribers[userID] = append(subs[:i], subs[i+1:]...)
				break
			}
		}
		r.Resolver.BroadcasterMu.Unlock()
		close(updates)
	}()
	return updates, nil
}

// Subscription returns SubscriptionResolver implementation.
func (r *Resolver) Subscription() SubscriptionResolver { return &subscriptionResolver{r} }

type subscriptionResolver struct{ *Resolver }
