package graphql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.89

import (
	"context"
	"fmt"
	"sigma_finance/internal/domain/model"
	gqlModel "sigma_finance/internal/handler/graphql/model"
	"sigma_finance/internal/service"

	"github.com/shopspring/decimal"
)

// UpdateTransaction is the resolver for the updateTransaction field.
func (r *mutationResolver) UpdateTransaction(ctx context.Context, id string, input gqlModel.UpdateTransactionInput) (*gqlModel.Transaction, error) {
	userID, err := getUserIDFromContext(ctx)
	if err != nil {
		return nil, err
	}

	existing, err := r.TransactionService.GetTransaction(ctx, id)
	if err != nil {
		return nil, err
	}
	if existing.UserID != userID {
		return nil, fmt.Errorf("transaction not found")
	}

	req := service.UpdateTransactionRequest{}
	if input.Quantity != nil {
		quantity := decimal.NewFromFloat(*input.Quantity)
		req.Quantity = &quantity
	}
	if input.UnitPriceAmount != nil {
		unitPriceAmount := decimal.NewFromFloat(*input.UnitPriceAmount)
		req.UnitPriceAmount = &unitPriceAmount
	}
	if input.FeesAmount != nil {
		fees := model.FromFloat(*input.FeesAmount)
		req.FeesAmount = &fees
	}
	if input.ExecutedAt != nil {
		req.ExecutedAt = input.ExecutedAt
	}
	if input.Notes != nil {
		req.Notes = input.Notes
	}

	effectiveQuantity := existing.Quantity
	if req.Quantity != nil {
		effectiveQuantity = req.Quantity
	}
	effectiveUnitPrice := existing.UnitPriceAmount
	if req.UnitPriceAmount != nil {
		effectiveUnitPrice = req.UnitPriceAmount
	}
	if effectiveQuantity != nil && effectiveUnitPrice != nil {
		amount := model.FromDecimal(effectiveQuantity.Mul(*effectiveUnitPrice))
		if !existing.Type.IsPositiveAmount() {
			amount = -amount
		}
		req.Amount = &amount
	}

	updated, err := r.TransactionService.UpdateTransaction(ctx, id, req)
	if err != nil {
		return nil, err
	}

	return mapTransactionToGQL(*updated), nil
}
