# internal/handler/graphql/schema/transaction.graphqls

type Transaction {
    id: ID!
    portfolio: Portfolio!
    asset: Asset!
    transactionType: TransactionType!
    quantity: Float!
    unitPriceAmount: Float
    unitPriceCurrency: String!
    feesAmount: Float!
    feesCurrency: String!
    executedAt: Time!
    notes: String
}


enum TransactionType {
    BUY
    SELL
}

input TransactionFilter {
    userID: ID
    portfolioID: ID
    assetID: ID
    transactionType: TransactionType
    dateFrom: Time
    dateTo: Time
}

input TransactionOrder {
    field: TransactionOrderField! = EXECUTED_AT
    direction: SortDirection! = DESC
}

enum TransactionOrderField {
    EXECUTED_AT
    UNIT_PRICE_AMOUNT
    QUANTITY
}

input UpdateTransactionInput {
    quantity: Float
    unitPriceAmount: Float
    feesAmount: Float
    executedAt: Time
    notes: String
}

extend type Mutation {
    updateTransaction(id: ID!, input: UpdateTransactionInput!): Transaction! @auth
}
