# internal/handler/graphql/schema/user.graphqls

type User {
    id: ID!
    username: String!
    email: String!
    createdAt: Time!
    updatedAt: Time!
    portfolios: [Portfolio!]!
    watchlists: [Watchlist!]!
    displayCurrency: String!
    themePreference: String!
    themeBaseColor: String!
    themeAccentColor: String!
    themeFontPreference: String!
    themeHeadingFont: String!
    themeMenuAccent: String!
    themeMenuColor: String!
    themeStyle: String!
    themeRadius: Float!
    themeRTL: Boolean!
}

# --- Inputs & Enums for User ---

input CreateUserInput {
    username: String!
    email: String!
    password: String!
}

input UpdateUserInput {
    username: String
    email: String
    password: String
}

input UpdateUserDisplayCurrencyInput {
    displayCurrency: String!
}

input UpdateUserThemePreferencesInput {
    themePreference: String!
    themeBaseColor: String!
    themeAccentColor: String!
    themeFontPreference: String!
    themeHeadingFont: String!
    themeMenuAccent: String!
    themeMenuColor: String!
    themeStyle: String!
    themeRadius: Float!
    themeRTL: Boolean!
}

input UserFilter {
    id: ID
    usernameContains: String
    email: String
}

input UserOrder {
    field: UserOrderField! = CREATED_AT
    direction: SortDirection! = DESC
}

enum UserOrderField {
    USERNAME
    EMAIL
    CREATED_AT
}
