// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package gqlModel

import (
	"fmt"
	"io"
	"strconv"
	"time"
)

type Asset interface {
	IsAsset()
	GetID() string
	GetName() string
	GetSymbol() *string
	GetAssetType() *AssetType
	GetCurrentValue() *float64
	GetPurchaseDate() *time.Time
	GetPurchasePrice() *float64
	GetTags() []*Tag
	GetPositions() []*Position
}

type AssetAllocation struct {
	AssetType  string  `json:"assetType"`
	Value      float64 `json:"value"`
	Percentage float64 `json:"percentage"`
	Count      int32   `json:"count"`
}

type AssetFilter struct {
	UserID       *string  `json:"userID,omitempty"`
	AssetTypeID  *string  `json:"assetTypeID,omitempty"`
	NameContains *string  `json:"nameContains,omitempty"`
	HasTagIDs    []string `json:"hasTagIDs,omitempty"`
}

type AssetOrder struct {
	Field     AssetOrderField `json:"field"`
	Direction SortDirection   `json:"direction"`
}

type AssetType struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

type CreateCryptoInput struct {
	Name              string     `json:"name"`
	AssetTypeID       string     `json:"assetTypeID"`
	CurrentValue      *float64   `json:"currentValue,omitempty"`
	PurchaseDate      *time.Time `json:"purchaseDate,omitempty"`
	PurchasePrice     *float64   `json:"purchasePrice,omitempty"`
	WalletAddress     *string    `json:"walletAddress,omitempty"`
	BlockchainNetwork *string    `json:"blockchainNetwork,omitempty"`
	Quantity          float64    `json:"quantity"`
}

type CreatePortfolioInput struct {
	UserID      string  `json:"userID"`
	Name        string  `json:"name"`
	Description *string `json:"description,omitempty"`
}

type CreateStockInput struct {
	Name          string     `json:"name"`
	AssetTypeID   string     `json:"assetTypeID"`
	CurrentValue  *float64   `json:"currentValue,omitempty"`
	PurchaseDate  *time.Time `json:"purchaseDate,omitempty"`
	PurchasePrice *float64   `json:"purchasePrice,omitempty"`
	Ticker        string     `json:"ticker"`
	Quantity      float64    `json:"quantity"`
}

type CreateUserInput struct {
	Username string `json:"username"`
	Email    string `json:"email"`
	Password string `json:"password"`
}

type CreateWatchlistInput struct {
	UserID string `json:"userID"`
	Name   string `json:"name"`
}

type Crypto struct {
	ID                string      `json:"id"`
	Name              string      `json:"name"`
	Symbol            *string     `json:"symbol,omitempty"`
	AssetType         *AssetType  `json:"assetType"`
	CurrentValue      *float64    `json:"currentValue,omitempty"`
	PurchaseDate      *time.Time  `json:"purchaseDate,omitempty"`
	PurchasePrice     *float64    `json:"purchasePrice,omitempty"`
	Tags              []*Tag      `json:"tags"`
	WalletAddress     *string     `json:"walletAddress,omitempty"`
	BlockchainNetwork *string     `json:"blockchainNetwork,omitempty"`
	Quantity          float64     `json:"quantity"`
	Positions         []*Position `json:"positions"`
}

func (Crypto) IsAsset()                         {}
func (this Crypto) GetID() string               { return this.ID }
func (this Crypto) GetName() string             { return this.Name }
func (this Crypto) GetSymbol() *string          { return this.Symbol }
func (this Crypto) GetAssetType() *AssetType    { return this.AssetType }
func (this Crypto) GetCurrentValue() *float64   { return this.CurrentValue }
func (this Crypto) GetPurchaseDate() *time.Time { return this.PurchaseDate }
func (this Crypto) GetPurchasePrice() *float64  { return this.PurchasePrice }
func (this Crypto) GetTags() []*Tag {
	if this.Tags == nil {
		return nil
	}
	interfaceSlice := make([]*Tag, 0, len(this.Tags))
	for _, concrete := range this.Tags {
		interfaceSlice = append(interfaceSlice, concrete)
	}
	return interfaceSlice
}
func (this Crypto) GetPositions() []*Position {
	if this.Positions == nil {
		return nil
	}
	interfaceSlice := make([]*Position, 0, len(this.Positions))
	for _, concrete := range this.Positions {
		interfaceSlice = append(interfaceSlice, concrete)
	}
	return interfaceSlice
}

type DuplicatePortfolioInput struct {
	SourcePortfolioID string  `json:"sourcePortfolioID"`
	NewName           string  `json:"newName"`
	Description       *string `json:"description,omitempty"`
	CopyAssets        bool    `json:"copyAssets"`
}

type ExportPortfolioInput struct {
	PortfolioID         string       `json:"portfolioID"`
	Format              ExportFormat `json:"format"`
	IncludeTransactions bool         `json:"includeTransactions"`
	IncludeAnalytics    bool         `json:"includeAnalytics"`
}

type ExportResult struct {
	Success     bool    `json:"success"`
	DownloadURL *string `json:"downloadUrl,omitempty"`
	Error       *string `json:"error,omitempty"`
}

type Mutation struct {
}

type Ownership struct {
	User                *User   `json:"user"`
	Asset               Asset   `json:"asset"`
	OwnershipPercentage float64 `json:"ownershipPercentage"`
}

type PaginationInput struct {
	Limit  *int32 `json:"limit,omitempty"`
	Offset *int32 `json:"offset,omitempty"`
}

type PerformancePoint struct {
	Date  time.Time `json:"date"`
	Value float64   `json:"value"`
}

type Portfolio struct {
	ID           string              `json:"id"`
	Name         string              `json:"name"`
	Description  *string             `json:"description,omitempty"`
	SortOrder    int32               `json:"sortOrder"`
	CreatedAt    time.Time           `json:"createdAt"`
	UpdatedAt    time.Time           `json:"updatedAt"`
	User         *User               `json:"user"`
	Tags         []*Tag              `json:"tags"`
	Assets       []*PortfolioAsset   `json:"assets"`
	Transactions []*Transaction      `json:"transactions"`
	Analytics    *PortfolioAnalytics `json:"analytics,omitempty"`
}

type PortfolioAnalytics struct {
	TotalValue           float64             `json:"totalValue"`
	TotalCost            float64             `json:"totalCost"`
	TotalGainLoss        float64             `json:"totalGainLoss"`
	TotalGainLossPercent float64             `json:"totalGainLossPercent"`
	AssetAllocation      []*AssetAllocation  `json:"assetAllocation"`
	RiskMetrics          *RiskMetrics        `json:"riskMetrics"`
	PerformanceHistory   []*PerformancePoint `json:"performanceHistory"`
}

type PortfolioAsset struct {
	Asset                Asset    `json:"asset"`
	Quantity             float64  `json:"quantity"`
	AveragePurchasePrice *float64 `json:"averagePurchasePrice,omitempty"`
	CurrentValue         *float64 `json:"currentValue,omitempty"`
	OwnershipPct         *float64 `json:"ownershipPct,omitempty"`
}

type PortfolioAssetInput struct {
	PortfolioID          string   `json:"portfolioID"`
	AssetID              string   `json:"assetID"`
	Quantity             float64  `json:"quantity"`
	AveragePurchasePrice *float64 `json:"averagePurchasePrice,omitempty"`
}

type PortfolioFilter struct {
	UserID       *string  `json:"userID,omitempty"`
	NameContains *string  `json:"nameContains,omitempty"`
	HasTagIDs    []string `json:"hasTagIDs,omitempty"`
}

type PortfolioOrder struct {
	Field     PortfolioOrderField `json:"field"`
	Direction SortDirection       `json:"direction"`
}

type PortfolioOrderInput struct {
	PortfolioID string `json:"portfolioID"`
	SortOrder   int32  `json:"sortOrder"`
}

type PortfolioUpdatePayload struct {
	Type      string     `json:"type"`
	Portfolio *Portfolio `json:"portfolio"`
}

type Position struct {
	ID                   string     `json:"id"`
	Portfolio            *Portfolio `json:"portfolio"`
	Asset                Asset      `json:"asset"`
	Quantity             float64    `json:"quantity"`
	AveragePurchasePrice *float64   `json:"averagePurchasePrice,omitempty"`
	OwnershipPct         *float64   `json:"ownershipPct,omitempty"`
}

type Query struct {
}

type ReorderPortfoliosInput struct {
	UserID          string                 `json:"userID"`
	PortfolioOrders []*PortfolioOrderInput `json:"portfolioOrders"`
}

type RiskMetrics struct {
	Volatility      float64 `json:"volatility"`
	SharpeRatio     float64 `json:"sharpeRatio"`
	MaxDrawdown     float64 `json:"maxDrawdown"`
	Diversification float64 `json:"diversification"`
}

type Stock struct {
	ID            string      `json:"id"`
	Name          string      `json:"name"`
	Symbol        *string     `json:"symbol,omitempty"`
	AssetType     *AssetType  `json:"assetType"`
	CurrentValue  *float64    `json:"currentValue,omitempty"`
	PurchaseDate  *time.Time  `json:"purchaseDate,omitempty"`
	PurchasePrice *float64    `json:"purchasePrice,omitempty"`
	Tags          []*Tag      `json:"tags"`
	Ticker        string      `json:"ticker"`
	Quantity      float64     `json:"quantity"`
	BuyingPrice   *float64    `json:"buyingPrice,omitempty"`
	Positions     []*Position `json:"positions"`
}

func (Stock) IsAsset()                         {}
func (this Stock) GetID() string               { return this.ID }
func (this Stock) GetName() string             { return this.Name }
func (this Stock) GetSymbol() *string          { return this.Symbol }
func (this Stock) GetAssetType() *AssetType    { return this.AssetType }
func (this Stock) GetCurrentValue() *float64   { return this.CurrentValue }
func (this Stock) GetPurchaseDate() *time.Time { return this.PurchaseDate }
func (this Stock) GetPurchasePrice() *float64  { return this.PurchasePrice }
func (this Stock) GetTags() []*Tag {
	if this.Tags == nil {
		return nil
	}
	interfaceSlice := make([]*Tag, 0, len(this.Tags))
	for _, concrete := range this.Tags {
		interfaceSlice = append(interfaceSlice, concrete)
	}
	return interfaceSlice
}
func (this Stock) GetPositions() []*Position {
	if this.Positions == nil {
		return nil
	}
	interfaceSlice := make([]*Position, 0, len(this.Positions))
	for _, concrete := range this.Positions {
		interfaceSlice = append(interfaceSlice, concrete)
	}
	return interfaceSlice
}

type Subscription struct {
}

type Tag struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

type Transaction struct {
	ID              string          `json:"id"`
	Portfolio       *Portfolio      `json:"portfolio"`
	Asset           Asset           `json:"asset"`
	TransactionType TransactionType `json:"transactionType"`
	Quantity        float64         `json:"quantity"`
	PricePerUnit    float64         `json:"pricePerUnit"`
	TransactionDate time.Time       `json:"transactionDate"`
	Notes           *string         `json:"notes,omitempty"`
}

type TransactionFilter struct {
	UserID          *string          `json:"userID,omitempty"`
	PortfolioID     *string          `json:"portfolioID,omitempty"`
	AssetID         *string          `json:"assetID,omitempty"`
	TransactionType *TransactionType `json:"transactionType,omitempty"`
	DateFrom        *time.Time       `json:"dateFrom,omitempty"`
	DateTo          *time.Time       `json:"dateTo,omitempty"`
}

type TransactionOrder struct {
	Field     TransactionOrderField `json:"field"`
	Direction SortDirection         `json:"direction"`
}

type TransactionUpdatePayload struct {
	Type        string       `json:"type"`
	Transaction *Transaction `json:"transaction"`
}

type UpdatePortfolioInput struct {
	Name        *string `json:"name,omitempty"`
	Description *string `json:"description,omitempty"`
	SortOrder   *int32  `json:"sortOrder,omitempty"`
}

type UpdateUserInput struct {
	Username *string `json:"username,omitempty"`
	Email    *string `json:"email,omitempty"`
	Password *string `json:"password,omitempty"`
}

type User struct {
	ID         string       `json:"id"`
	Username   string       `json:"username"`
	Email      string       `json:"email"`
	CreatedAt  time.Time    `json:"createdAt"`
	UpdatedAt  time.Time    `json:"updatedAt"`
	Portfolios []*Portfolio `json:"portfolios"`
	Watchlists []*Watchlist `json:"watchlists"`
}

type UserFilter struct {
	ID               *string `json:"id,omitempty"`
	UsernameContains *string `json:"usernameContains,omitempty"`
	Email            *string `json:"email,omitempty"`
}

type UserOrder struct {
	Field     UserOrderField `json:"field"`
	Direction SortDirection  `json:"direction"`
}

type Watchlist struct {
	ID        string    `json:"id"`
	Name      string    `json:"name"`
	CreatedAt time.Time `json:"createdAt"`
	UpdatedAt time.Time `json:"updatedAt"`
	User      *User     `json:"user"`
	Assets    []Asset   `json:"assets"`
}

type WatchlistFilter struct {
	UserID string `json:"userID"`
}

type AssetOrderField string

const (
	AssetOrderFieldName         AssetOrderField = "NAME"
	AssetOrderFieldCurrentValue AssetOrderField = "CURRENT_VALUE"
	AssetOrderFieldPurchaseDate AssetOrderField = "PURCHASE_DATE"
)

var AllAssetOrderField = []AssetOrderField{
	AssetOrderFieldName,
	AssetOrderFieldCurrentValue,
	AssetOrderFieldPurchaseDate,
}

func (e AssetOrderField) IsValid() bool {
	switch e {
	case AssetOrderFieldName, AssetOrderFieldCurrentValue, AssetOrderFieldPurchaseDate:
		return true
	}
	return false
}

func (e AssetOrderField) String() string {
	return string(e)
}

func (e *AssetOrderField) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = AssetOrderField(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid AssetOrderField", str)
	}
	return nil
}

func (e AssetOrderField) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

type ExportFormat string

const (
	ExportFormatCSV   ExportFormat = "CSV"
	ExportFormatPDF   ExportFormat = "PDF"
	ExportFormatExcel ExportFormat = "EXCEL"
)

var AllExportFormat = []ExportFormat{
	ExportFormatCSV,
	ExportFormatPDF,
	ExportFormatExcel,
}

func (e ExportFormat) IsValid() bool {
	switch e {
	case ExportFormatCSV, ExportFormatPDF, ExportFormatExcel:
		return true
	}
	return false
}

func (e ExportFormat) String() string {
	return string(e)
}

func (e *ExportFormat) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = ExportFormat(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid ExportFormat", str)
	}
	return nil
}

func (e ExportFormat) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

type PortfolioOrderField string

const (
	PortfolioOrderFieldName      PortfolioOrderField = "NAME"
	PortfolioOrderFieldSortOrder PortfolioOrderField = "SORT_ORDER"
	PortfolioOrderFieldCreatedAt PortfolioOrderField = "CREATED_AT"
	PortfolioOrderFieldUpdatedAt PortfolioOrderField = "UPDATED_AT"
)

var AllPortfolioOrderField = []PortfolioOrderField{
	PortfolioOrderFieldName,
	PortfolioOrderFieldSortOrder,
	PortfolioOrderFieldCreatedAt,
	PortfolioOrderFieldUpdatedAt,
}

func (e PortfolioOrderField) IsValid() bool {
	switch e {
	case PortfolioOrderFieldName, PortfolioOrderFieldSortOrder, PortfolioOrderFieldCreatedAt, PortfolioOrderFieldUpdatedAt:
		return true
	}
	return false
}

func (e PortfolioOrderField) String() string {
	return string(e)
}

func (e *PortfolioOrderField) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = PortfolioOrderField(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid PortfolioOrderField", str)
	}
	return nil
}

func (e PortfolioOrderField) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

type SortDirection string

const (
	SortDirectionAsc  SortDirection = "ASC"
	SortDirectionDesc SortDirection = "DESC"
)

var AllSortDirection = []SortDirection{
	SortDirectionAsc,
	SortDirectionDesc,
}

func (e SortDirection) IsValid() bool {
	switch e {
	case SortDirectionAsc, SortDirectionDesc:
		return true
	}
	return false
}

func (e SortDirection) String() string {
	return string(e)
}

func (e *SortDirection) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = SortDirection(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid SortDirection", str)
	}
	return nil
}

func (e SortDirection) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

type TransactionOrderField string

const (
	TransactionOrderFieldTransactionDate TransactionOrderField = "TRANSACTION_DATE"
	TransactionOrderFieldPricePerUnit    TransactionOrderField = "PRICE_PER_UNIT"
	TransactionOrderFieldQuantity        TransactionOrderField = "QUANTITY"
)

var AllTransactionOrderField = []TransactionOrderField{
	TransactionOrderFieldTransactionDate,
	TransactionOrderFieldPricePerUnit,
	TransactionOrderFieldQuantity,
}

func (e TransactionOrderField) IsValid() bool {
	switch e {
	case TransactionOrderFieldTransactionDate, TransactionOrderFieldPricePerUnit, TransactionOrderFieldQuantity:
		return true
	}
	return false
}

func (e TransactionOrderField) String() string {
	return string(e)
}

func (e *TransactionOrderField) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = TransactionOrderField(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid TransactionOrderField", str)
	}
	return nil
}

func (e TransactionOrderField) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

type TransactionType string

const (
	TransactionTypeBuy  TransactionType = "BUY"
	TransactionTypeSell TransactionType = "SELL"
)

var AllTransactionType = []TransactionType{
	TransactionTypeBuy,
	TransactionTypeSell,
}

func (e TransactionType) IsValid() bool {
	switch e {
	case TransactionTypeBuy, TransactionTypeSell:
		return true
	}
	return false
}

func (e TransactionType) String() string {
	return string(e)
}

func (e *TransactionType) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = TransactionType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid TransactionType", str)
	}
	return nil
}

func (e TransactionType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

type UserOrderField string

const (
	UserOrderFieldUsername  UserOrderField = "USERNAME"
	UserOrderFieldEmail     UserOrderField = "EMAIL"
	UserOrderFieldCreatedAt UserOrderField = "CREATED_AT"
)

var AllUserOrderField = []UserOrderField{
	UserOrderFieldUsername,
	UserOrderFieldEmail,
	UserOrderFieldCreatedAt,
}

func (e UserOrderField) IsValid() bool {
	switch e {
	case UserOrderFieldUsername, UserOrderFieldEmail, UserOrderFieldCreatedAt:
		return true
	}
	return false
}

func (e UserOrderField) String() string {
	return string(e)
}

func (e *UserOrderField) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = UserOrderField(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid UserOrderField", str)
	}
	return nil
}

func (e UserOrderField) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}
